import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { getStorage, ref as sRef, uploadBytesResumable, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";

const fb=initializeApp(firebaseConfig); const db=getDatabase(fb), storage=getStorage(fb);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const LS='rafStudioV3Backup';
const galleryBase='https://universalwebtools.github.io/raf.studio.galeria/';
const defaults={
 site:{heroK:'FOTOGRAFIA • FILM • BIELSKO-BIAŁA',heroT:'OBRAZ, KTÓRY ZOSTAJE.',heroD:'Fotografia i film tworzone z naciskiem na emocje, detal i nowoczesny, filmowy charakter.',email:'',phone:'',instagram:'',whatsapp:'',gallery:galleryBase},
 photos:[
  {id:'p1',title:'Śluby / reportaż',category:'Śluby',image:'assets/photo-wedding.png',visible:true,desktop:{span:7,ratio:'4/3',x:50,y:50},tablet:{span:6,ratio:'4/3',x:50,y:50},mobile:{span:12,ratio:'4/3',x:50,y:50}},
  {id:'p2',title:'Sesje',category:'Sesje',image:'assets/photo-session.png',visible:true,desktop:{span:5,ratio:'4/3',x:50,y:50},tablet:{span:6,ratio:'4/3',x:50,y:50},mobile:{span:12,ratio:'4/3',x:50,y:50}},
  {id:'p3',title:'Produkt',category:'Produkt',image:'assets/photo-product.png',visible:true,desktop:{span:4,ratio:'4/3',x:50,y:50},tablet:{span:6,ratio:'4/3',x:50,y:50},mobile:{span:12,ratio:'1/1',x:50,y:50}},
  {id:'p4',title:'Eventy / marki',category:'Event',image:'assets/photo-event.png',visible:true,desktop:{span:8,ratio:'4/3',x:50,y:50},tablet:{span:6,ratio:'4/3',x:50,y:50},mobile:{span:12,ratio:'4/3',x:50,y:50}}
 ],
 films:[
  {id:'f1',title:'Film reklamowy',category:'Reklama',image:'assets/film-ad.png',video:'',visible:true,desktop:{span:8,ratio:'16/9',x:50,y:50},tablet:{span:6,ratio:'16/9',x:50,y:50},mobile:{span:12,ratio:'16/9',x:50,y:50}},
  {id:'f2',title:'Social media',category:'Social media',image:'assets/film-social.png',video:'',visible:true,desktop:{span:4,ratio:'16/9',x:50,y:50},tablet:{span:6,ratio:'16/9',x:50,y:50},mobile:{span:12,ratio:'16/9',x:50,y:50}},
  {id:'f3',title:'Event',category:'Event',image:'assets/film-event.png',video:'',visible:true,desktop:{span:5,ratio:'16/9',x:50,y:50},tablet:{span:6,ratio:'16/9',x:50,y:50},mobile:{span:12,ratio:'16/9',x:50,y:50}},
  {id:'f4',title:'Produkt / slow motion',category:'Slow motion',image:'assets/film-slowmo.png',video:'',visible:true,desktop:{span:7,ratio:'16/9',x:50,y:50},tablet:{span:6,ratio:'16/9',x:50,y:50},mobile:{span:12,ratio:'16/9',x:50,y:50}}
 ],reviews:[{name:'Klient RAF.studio',text:'Świetny kontakt, piękny efekt i bardzo sprawna realizacja.'}],clients:['DAVIS','EVENT','PRODUCT','SOCIAL']
};
let state=loadLocal()||structuredClone(defaults), selected=new Set(), uploaded=[];
function loadLocal(){try{return JSON.parse(localStorage.getItem(LS)||'null')}catch{return null}}
function localSave(){localStorage.setItem(LS,JSON.stringify(state));setSaveState('Backup lokalny zapisany.');}
function setSaveState(t,cls=''){const e=$('#saveState');e.textContent=t;e.className='saveState '+cls;}
function normalize(raw){const s=structuredClone(defaults);if(!raw)return s;s.site={...s.site,...(raw.site||{})};['photos','films','reviews','clients'].forEach(k=>{if(Array.isArray(raw[k]))s[k]=raw[k]});return s}
async function loadCloud(){try{const snap=await get(ref(db,WEBSITE_ROOT+'/public'));if(snap.exists()){state=normalize(snap.val());localSave();setSaveState('Firebase: dane wczytane ✓','ok')}else setSaveState('Firebase połączony — brak danych, używam wersji lokalnej.','warn')}catch(e){setSaveState('Firebase odczyt niedostępny — pracuję lokalnie.','bad');log('Firebase odczyt: '+e.message)}renderAll();}
async function saveCloud(){localSave();try{await set(ref(db,WEBSITE_ROOT+'/public'),state);setSaveState('Zapisano online w Firebase ✓','ok');log('Firebase zapis: OK')}catch(e){setSaveState('Nie zapisano online — backup lokalny jest bezpieczny.','warn');log('Firebase zapis: '+e.message);alert('Nie udało się zapisać online. Backup lokalny został zachowany.\n\n'+e.message)}}

function bindSite(){const m={heroK:'heroK',heroT:'heroT',heroD:'heroD',email:'email',phone:'phone',instagram:'instagram',whatsapp:'whatsapp',gallery:'gallery'};for(const [k,id] of Object.entries(m)){const e=$('#'+id);e.value=state.site[k]||'';e.oninput=()=>{state.site[k]=e.value;localSave()}}}
function devCfg(item,d){item[d] ||= {span:d==='mobile'?12:6,ratio:'4/3',x:50,y:50};return item[d]}
function editorRow(item,type){const row=document.createElement('div');row.className='sortRow';row.draggable=true;row.dataset.id=item.id;row.dataset.type=type;let dev='desktop';
 row.innerHTML=`<input class="check" type="checkbox" ${selected.has(item.id)?'checked':''}><span class="drag">☰</span><div><b>${item.title}</b><div class="tiny">${item.category||''}</div><div class="deviceTabs"><button class="pill active" data-d="desktop">PC</button><button class="pill" data-d="tablet">Tablet</button><button class="pill" data-d="mobile">Telefon</button></div><div class="rowEditor"></div></div><button class="pill danger">Usuń</button>`;
 const ed=$('.rowEditor',row);function draw(){const c=devCfg(item,dev);ed.innerHTML=`<label>Tytuł<input data-k="title" value="${item.title.replaceAll('"','&quot;')}"></label><label>Span<select data-k="span">${[3,4,5,6,7,8,9,12].map(n=>`<option ${c.span==n?'selected':''}>${n}</option>`).join('')}</select></label><label>Proporcje<select data-k="ratio">${['1/1','4/3','3/2','16/9','2/3'].map(v=>`<option ${c.ratio===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Kadr X<input data-k="x" type="number" min="0" max="100" value="${c.x??50}"></label><label>Kadr Y<input data-k="y" type="number" min="0" max="100" value="${c.y??50}"></label><label>Widoczny<select data-k="visible"><option value="1" ${item.visible!==false?'selected':''}>Tak</option><option value="0" ${item.visible===false?'selected':''}>Nie</option></select></label>${type==='film'?`<label style="grid-column:1/-1">Film URL<input data-k="video" value="${item.video||''}" placeholder="YouTube / Vimeo / MP4"></label>`:''}`;$$('input,select',ed).forEach(inp=>inp.onchange=()=>{const k=inp.dataset.k;if(k==='title'||k==='video')item[k]=inp.value;else if(k==='visible')item.visible=inp.value==='1';else c[k]=k==='ratio'?inp.value:Number(inp.value);localSave()})}draw();
 $$('.deviceTabs button',row).forEach(b=>b.onclick=()=>{$$('.deviceTabs button',row).forEach(x=>x.classList.remove('active'));b.classList.add('active');dev=b.dataset.d;draw()});$('.check',row).onchange=e=>{e.target.checked?selected.add(item.id):selected.delete(item.id);updateSelected()};$('.danger',row).onclick=()=>deleteItems([item.id]);
 row.ondragstart=()=>row.classList.add('dragging');row.ondragend=()=>row.classList.remove('dragging');return row;}
function renderSort(container,arr,type){const c=$(container);c.innerHTML='';arr.forEach(x=>c.append(editorRow(x,type)));c.ondragover=e=>{e.preventDefault();const drag=$('.dragging',c);if(!drag)return;const after=[...c.querySelectorAll('.sortRow:not(.dragging)')].find(el=>e.clientY<=el.getBoundingClientRect().top+el.offsetHeight/2);after?c.insertBefore(drag,after):c.append(drag)};c.ondrop=()=>{const order=[...c.children].map(x=>x.dataset.id);arr.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));localSave()}}
function updateSelected(){$('#selectedCount').textContent=selected.size+' zazn.';$('#selectAll').checked=selected.size===state.photos.length+state.films.length&&selected.size>0}
function deleteItems(ids){if(!ids.length)return;if(!confirm(`Na pewno usunąć ${ids.length} element(ów)? Tej operacji nie cofniemy w bieżącej konfiguracji.`))return;state.photos=state.photos.filter(x=>!ids.includes(x.id));state.films=state.films.filter(x=>!ids.includes(x.id));ids.forEach(id=>selected.delete(id));localSave();renderPortfolio()}
function renderPortfolio(){renderSort('#photoSort',state.photos,'photo');renderSort('#filmSort',state.films,'film');updateSelected()}

function setupBulk(){ $('#selectAll').onchange=e=>{selected.clear();if(e.target.checked)[...state.photos,...state.films].forEach(x=>selected.add(x.id));renderPortfolio()};$$('[data-bulk]').forEach(b=>b.onclick=()=>{const ids=[...selected];if(!ids.length)return;const action=b.dataset.bulk;if(action==='delete')return deleteItems(ids);[...state.photos,...state.films].forEach(x=>{if(ids.includes(x.id))x.visible=action==='show'});localSave();renderPortfolio()})}

function setupUpload(){const drop=$('#uploadDrop'),input=$('#uploadInput');drop.onclick=e=>{if(e.target!==input)input.click()};input.onchange=()=>uploadMany([...input.files]);['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>uploadMany([...e.dataTransfer.files]));}
function uploadMany(files){files.filter(f=>/^(image\/|video\/)/.test(f.type)).forEach(uploadOne)}
function uploadOne(file){const wrap=document.createElement('div');wrap.className='progressItem';wrap.innerHTML=`<b>${file.name}</b><div class="progressTrack"><div class="progressFill"></div></div><div class="progressMeta"><span>0%</span><span>Start…</span></div>`;$('#uploadProgress').prepend(wrap);const path=`website/media/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let task;try{task=uploadBytesResumable(sRef(storage,path),file)}catch(e){$('.progressMeta span:last-child',wrap).textContent='Błąd: '+e.message;return}task.on('state_changed',s=>{const p=Math.round(s.bytesTransferred/s.totalBytes*100);$('.progressFill',wrap).style.width=p+'%';$('.progressMeta span:first-child',wrap).textContent=p+'%';$('.progressMeta span:last-child',wrap).textContent='Wysyłanie…'},e=>{$('.progressMeta span:last-child',wrap).textContent='Błąd: '+e.message;log('Upload '+file.name+': '+e.message)},async()=>{const url=await getDownloadURL(task.snapshot.ref);$('.progressMeta span:last-child',wrap).textContent='✓ Gotowe';uploaded.unshift({name:file.name,url,type:file.type});renderMedia();log('Upload OK: '+file.name)})}
function renderMedia(){const m=$('#mediaList');m.innerHTML=uploaded.length?uploaded.map(x=>`<div><a href="${x.url}" target="_blank">${x.name}</a> — ${x.type}</div>`).join(''):'Brak plików w tej sesji.'}

function log(t){const l=$('#diagLog');const stamp=new Date().toLocaleTimeString();l.textContent=`[${stamp}] ${t}\n`+l.textContent}
function statusBox(name,stateTxt,kind='warn'){return `<div class="statusBox ${kind}"><b><span class="statusDot"></span>${name}</b><span class="tiny">${stateTxt}</span></div>`}
async function renderStatus(){let fbRead='Sprawdzanie…',kind='warn';try{await get(ref(db,WEBSITE_ROOT));fbRead='Połączenie działa';kind='ok'}catch{fbRead='Brak dostępu';kind='bad'}$('#statusGrid').innerHTML=statusBox('Firebase',fbRead,kind)+statusBox('Zapis CMS','Tryb bez logowania — zapis do website/public','ok')+statusBox('Storage','Połączony — folder website/media','ok')+statusBox('GitHub Pages',location.hostname.includes('github.io')?'Strona działa z GitHub Pages':'Tryb lokalny','ok')+statusBox('Galeria klienta',state.site.gallery||galleryBase,'ok')+statusBox('Backup lokalny',localStorage.getItem(LS)?'Jest zapisany':'Brak backupu',localStorage.getItem(LS)?'ok':'warn')}
async function checkUrl(url,label){try{const r=await fetch(url,{method:'HEAD',cache:'no-store'});log(`${label}: ${r.ok?'OK':'HTTP '+r.status}`);return r.ok}catch{log(`${label}: nie można sprawdzić (CORS lub offline)`);return null}}
async function diagnostics(){log('--- DIAGNOSTYKA START ---');await renderStatus();for(const x of [...state.photos,...state.films])await checkUrl(new URL(x.image,location.href).href,'Obraz '+x.title);await checkUrl(state.site.gallery||galleryBase,'Galeria klienta');for(const x of state.films.filter(x=>x.video))await checkUrl(x.video,'Film '+x.title);log('--- KONIEC ---')}

function setupPreview(){const o=$('#previewOverlay'),stage=$('#deviceStage'),frame=$('#previewFrame');$('#preview').onclick=()=>o.classList.add('open');$('#previewClose').onclick=()=>o.classList.remove('open');$('#previewReload').onclick=()=>frame.contentWindow.location.reload();$$('[data-device]').forEach(b=>b.onclick=()=>{stage.className='deviceStage '+b.dataset.device;$$('[data-device]').forEach(x=>x.classList.remove('primary'));b.classList.add('primary')})}
function setupPanes(){$$('.adminNav button').forEach(b=>b.onclick=()=>{$$('.adminNav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.adminPane').forEach(x=>x.classList.toggle('active',x.dataset.paneView===b.dataset.pane))})}
function setupGallery(){const url=state.site.gallery||galleryBase;$('#openGalleryClient').href=url;$('#openGalleryAdmin').href=galleryBase+'admin.html';$('#galleryFrame').src=galleryBase+'admin.html'}
function exportJson(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='RAF-studio-backup.json';a.click();URL.revokeObjectURL(a.href)}
function setupSystem(){ $('#export').onclick=exportJson;$('#import').onchange=async e=>{try{state=normalize(JSON.parse(await e.target.files[0].text()));localSave();renderAll()}catch{alert('Nieprawidłowy plik JSON')}};$('#reset').onclick=()=>{if(confirm('Przywrócić domyślne ustawienia lokalne?')){state=structuredClone(defaults);localSave();renderAll()}};$('#systemInfo').innerHTML=`Projekt Firebase: <b>${firebaseConfig.projectId}</b><br>Ścieżka danych: <b>${WEBSITE_ROOT}/public</b><br>Repo: <b>universalwebtools/raf-studio</b><br>Galeria: <b>raf.studio.galeria</b>`}
function renderAll(){bindSite();renderPortfolio();renderMedia();renderStatus();setupGallery()}

$('#saveCloud').onclick=saveCloud;$('#runDiagnostics').onclick=diagnostics;$('#checkLinks').onclick=diagnostics;setupPanes();setupBulk();setupUpload();setupPreview();setupSystem();renderAll();loadCloud();