const RAF_DEFAULTS={
  contact:{email:'kontakt@raf-studio.pl',phone:'+48 000 000 000',instagram:'#',whatsapp:'#',gallery:'https://universalwebtools.github.io/raf.studio.galeria/'},
  hero:{kicker:'FOTOGRAFIA • FILM • BIELSKO-BIAŁA',title:'OBRAZ, KTÓRY ZOSTAJE.',text:'Fotografia i film tworzone z naciskiem na emocje, detal i nowoczesny, filmowy charakter.'},
  photo:[
   {id:'wedding',title:'Śluby / reportaż',cat:'Śluby',img:'assets/photo-wedding.png',span:7,ratio:'4/3',x:50,y:50,visible:true},
   {id:'session',title:'Sesje',cat:'Sesje',img:'assets/photo-session.png',span:5,ratio:'4/3',x:50,y:46,visible:true},
   {id:'product',title:'Produkt',cat:'Produkt',img:'assets/photo-product.png',span:4,ratio:'1/1',x:50,y:50,visible:true},
   {id:'event',title:'Eventy / marki',cat:'Eventy',img:'assets/photo-event.png',span:8,ratio:'16/9',x:50,y:50,visible:true}],
  film:[
   {id:'ad',title:'Film reklamowy',cat:'Reklama',img:'assets/film-ad.png',span:8,ratio:'16/9',x:50,y:50,url:'',visible:true},
   {id:'social',title:'Social media',cat:'Social media',img:'assets/film-social.png',span:4,ratio:'9/16',x:50,y:50,url:'',visible:true},
   {id:'eventfilm',title:'Event',cat:'Event',img:'assets/film-event.png',span:5,ratio:'16/9',x:50,y:50,url:'',visible:true},
   {id:'slowmo',title:'Produkt / slow motion',cat:'Produkt',img:'assets/film-slowmo.png',span:7,ratio:'16/9',x:50,y:50,url:'',visible:true}],
  reviews:[
   {text:'Bardzo sprawna współpraca, świetny kontakt i materiał oddany w dokładnie takim stylu, jaki ustaliliśmy.',name:'Klient fotograficzny'},
   {text:'Film wygląda nowocześnie i profesjonalnie. Cały proces od pomysłu do finalnego pliku był bardzo konkretny.',name:'Klient biznesowy'},
   {text:'Naturalne zdjęcia, bez sztucznego pozowania. Dokładnie o taki reportaż nam chodziło.',name:'Para młoda'}],
  clients:['DAVIS FABRICS','BRAND ONE','STUDIO X','EVENT LAB','LOCAL BUSINESS']
};
function rafCfg(){try{return {...RAF_DEFAULTS,...JSON.parse(localStorage.getItem('rafstudio_v2')||'{}')}}catch(e){return structuredClone(RAF_DEFAULTS)}}
function saveCfg(c){localStorage.setItem('rafstudio_v2',JSON.stringify(c));window.dispatchEvent(new Event('raf-config-changed'))}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nav(){const c=rafCfg();return `<nav class="nav"><div class="wrap navin"><a class="brand" href="index.html">RAF<span>.studio</span></a><div class="navlinks"><a class="hideMob" href="fotografia.html">Fotografia</a><a class="hideMob" href="film.html">Film</a><a class="hideMob" href="index.html#omnie">O mnie</a><a class="hideMob" href="index.html#kontakt">Kontakt</a><a class="pill hideMob" href="${esc(c.contact.gallery)}">Strefa klienta</a><a class="pill keep" href="admin.html">⚙ Admin</a></div></div></nav>`}
function footer(){return `<footer class="wrap"><span>© ${new Date().getFullYear()} RAF.studio</span><span><a href="privacy.html">Polityka prywatności</a> • Fotografia • Film</span></footer>`}
function floating(){const c=rafCfg();return `<div class="floatContact"><a class="dark" href="tel:${esc(c.contact.phone.replace(/\s/g,''))}" title="Telefon">☎</a><a href="${esc(c.contact.whatsapp)}" title="WhatsApp">W</a></div>`}
function tileHTML(item,type){if(item.visible===false)return '';return `<article class="tile fade" data-id="${item.id}" data-type="${type}" style="--span:${item.span};--ratio:${item.ratio};--pos:${item.x}% ${item.y}%"><img src="${item.img}" alt="${esc(item.title)}"><div class="tileMeta"><div><div class="eyebrow">${type==='photo'?'Fotografia':'Film'} / ${esc(item.cat)}</div><div class="tileTitle">${esc(item.title)}</div></div>${type==='film'?'<div class="play">▶</div>':''}</div></article>`}
function renderTiles(container,items,type,cat='Wszystkie'){container.innerHTML=items.filter(x=>cat==='Wszystkie'||x.cat===cat).map(x=>tileHTML(x,type)).join('');bindTiles(container,items,type);observe()}
function bindTiles(container,items,type){container.querySelectorAll('.tile').forEach(el=>el.addEventListener('click',()=>{const item=items.find(x=>x.id===el.dataset.id);if(type==='film')openVideo(item);else openViewer(items.filter(x=>x.visible!==false),item.id)}))}
function buildFilters(el,items,callback){const cats=['Wszystkie',...new Set(items.map(x=>x.cat))];el.innerHTML=cats.map((x,i)=>`<button class="filter ${i===0?'active':''}" data-cat="${esc(x)}">${esc(x)}</button>`).join('');el.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{el.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');callback(b.dataset.cat)})}
let viewerItems=[],viewerIndex=0;
function ensureModals(){if(!document.querySelector('#rafViewer'))document.body.insertAdjacentHTML('beforeend',`<div class="viewer" id="rafViewer"><div class="viewerShell"><div class="viewerTop"><b id="viewerTitle">Zdjęcie</b><div class="viewerNav"><button class="iconBtn" id="viewerPrev">←</button><button class="iconBtn" id="viewerNext">→</button><button class="iconBtn" id="viewerClose">✕</button></div></div><div class="viewerMedia"><img id="viewerImg"></div></div></div><div class="videoModal" id="rafVideo"><div class="videoShell"><div class="videoTop"><b id="videoTitle">Film</b><button class="iconBtn" id="videoClose">✕</button></div><div class="videoStage" id="videoStage"></div></div></div>`);
 const v=document.querySelector('#rafViewer');document.querySelector('#viewerClose').onclick=()=>v.classList.remove('open');document.querySelector('#viewerPrev').onclick=()=>showViewer(viewerIndex-1);document.querySelector('#viewerNext').onclick=()=>showViewer(viewerIndex+1);v.onclick=e=>{if(e.target===v)v.classList.remove('open')};const m=document.querySelector('#rafVideo');document.querySelector('#videoClose').onclick=()=>closeVideo();m.onclick=e=>{if(e.target===m)closeVideo()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){v.classList.remove('open');closeVideo()}})}
function openViewer(items,id){ensureModals();viewerItems=items;viewerIndex=Math.max(0,items.findIndex(x=>x.id===id));showViewer(viewerIndex);document.querySelector('#rafViewer').classList.add('open')}
function showViewer(i){viewerIndex=(i+viewerItems.length)%viewerItems.length;const item=viewerItems[viewerIndex];document.querySelector('#viewerImg').src=item.img;document.querySelector('#viewerTitle').textContent=item.title}
function youtubeEmbed(url){let m=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([^?&/]+)/);return m?`https://www.youtube.com/embed/${m[1]}?autoplay=1`:null}
function vimeoEmbed(url){let m=url.match(/vimeo\.com\/(?:video\/)?(\d+)/);return m?`https://player.vimeo.com/video/${m[1]}?autoplay=1`:null}
function openVideo(item){ensureModals();const stage=document.querySelector('#videoStage');document.querySelector('#videoTitle').textContent=item.title;stage.innerHTML='';const src=item.url||'';const yt=youtubeEmbed(src),vi=vimeoEmbed(src);if(yt||vi){stage.innerHTML=`<iframe allow="autoplay; fullscreen; picture-in-picture" allowfullscreen src="${yt||vi}"></iframe>`}else if(src){stage.innerHTML=`<video src="${esc(src)}" controls autoplay playsinline></video>`}else{stage.innerHTML=`<div style="height:100%;display:grid;place-items:center;color:#999;text-align:center;padding:30px">Ten film nie ma jeszcze podpiętego linku.<br>Dodasz go w panelu administratora.</div>`}document.querySelector('#rafVideo').classList.add('open')}
function closeVideo(){const m=document.querySelector('#rafVideo');if(!m)return;const v=m.querySelector('video');if(v)v.pause();m.classList.remove('open');document.querySelector('#videoStage').innerHTML=''}
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.08});document.querySelectorAll('.fade:not(.show)').forEach(x=>io.observe(x))}
function hydrateChrome(){document.querySelectorAll('[data-raf-nav]').forEach(x=>x.outerHTML=nav());document.querySelectorAll('[data-raf-footer]').forEach(x=>x.outerHTML=footer());document.body.insertAdjacentHTML('beforeend',floating());ensureModals();observe()}
document.addEventListener('DOMContentLoaded',hydrateChrome);