import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";
const EDITOR_MODE=new URLSearchParams(location.search).has('editor');
const app=initializeApp(firebaseConfig),db=getDatabase(app);const dev=()=>innerWidth<=640?'mobile':innerWidth<=980?'tablet':'desktop';let current={};
function cfgFor(byDev={},d=dev()){const desk=byDev.desktop||{};if(d==='desktop')return desk;const c=byDev[d]||{};return c.inherit===false?c:{...desk,...c}}
function applyElementStyle(el,c={}){if(!el)return;el.style.background=c.background||'';el.style.color=c.color||'';el.style.borderColor=c.borderColor||'';el.style.borderStyle=c.borderColor?'solid':'';el.style.borderWidth=c.borderColor?'1px':'';el.style.borderRadius=c.radius!=null?`${c.radius}px`:'';el.style.paddingLeft=c.paddingX!=null?`${c.paddingX}px`:'';el.style.paddingRight=c.paddingX!=null?`${c.paddingX}px`:'';el.style.paddingTop=c.paddingY!=null?`${c.paddingY}px`:'';el.style.paddingBottom=c.paddingY!=null?`${c.paddingY}px`:'';el.style.fontSize=c.fontSize!=null?`${c.fontSize}px`:'';el.style.opacity=c.opacity!=null?String(c.opacity):'';el.style.zIndex=c.zIndex!=null?String(c.zIndex):'';el.style.position=c.zIndex!=null?'relative':'';el.style.display=c.hidden===true?'none':'';el.dataset.rafAnimation=c.animation||'';el.style.setProperty('--raf-anim-duration',`${c.animationDuration||700}ms`)}
function applyElements(builder){for(const [key,byDev] of Object.entries(builder.elements||{})){const el=document.querySelector(`[data-raf-element="${CSS.escape(key)}"]`);if(!el)continue;const c=cfgFor(byDev);if(c.text!=null)el.textContent=c.text;if(c.href!=null&&'href'in el)el.href=c.href;if(key==='brandLogo'){const img=el.querySelector('img');if(img){if(c.logoUrl)img.src=c.logoUrl;if(c.logoWidth)img.style.width=`${c.logoWidth}px`}}applyElementStyle(el,c)}}
function sectionNode(key){return key==='Hero'?document.querySelector('header.hero'):document.querySelector(`[data-raf-section="${CSS.escape(key)}"]`)}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function youtubeId(url=''){const m=String(url).match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([A-Za-z0-9_-]{6,})/);return m?.[1]||''}
function vimeoId(url=''){const m=String(url).match(/vimeo\.com\/(?:video\/)?(\d+)/);return m?.[1]||''}
function videoMarkup(url=''){const y=youtubeId(url),v=vimeoId(url);if(y)return `<div class="rafVideoEmbed"><iframe src="https://www.youtube-nocookie.com/embed/${y}" title="YouTube video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`;if(v)return `<div class="rafVideoEmbed"><iframe src="https://player.vimeo.com/video/${v}" title="Vimeo video" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>`;if(url)return `<video src="${esc(url)}" controls playsinline class="rafDirectVideo"></video>`;return ''}
function renderCustomSection(s){const sec=document.createElement('section');sec.className='section raf-custom-section';sec.dataset.rafSection=s.id;sec.dataset.customSection='1';const img=s.imageUrl?`<div class="portrait"><img data-custom-field="image" data-custom-id="${esc(s.id)}" src="${esc(s.imageUrl)}" alt="" loading="lazy" style="width:100%;height:100%;object-fit:cover"></div>`:'';const btn=s.buttonText?`<a class="btn primary" data-custom-field="button" data-custom-id="${esc(s.id)}" href="${esc(s.buttonUrl||'#')}">${esc(s.buttonText)}</a>`:'';const title=`<h2 data-custom-field="title" data-custom-id="${esc(s.id)}">${esc(s.title||'NOWA SEKCJA.')}</h2>`;const text=`<p data-custom-field="text" data-custom-id="${esc(s.id)}">${esc(s.text||'')}</p>`;if(s.type==='gallery'){const urls=(s.images?.length?s.images:(s.imageUrl?[s.imageUrl]:[]));const imgs=urls.map(u=>`<img data-custom-field="image" data-custom-id="${esc(s.id)}" src="${esc(u)}" loading="lazy" alt="" style="width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:18px">`).join('');sec.innerHTML=`<div class="wrap"><div class="sectionHead">${title}${text}</div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px">${imgs}</div>${btn}</div>`}else if(s.type==='video'){sec.innerHTML=`<div class="wrap"><div class="sectionHead">${title}${text}</div><div data-custom-field="video" data-custom-id="${esc(s.id)}">${videoMarkup(s.videoUrl||'')}</div>${btn}</div>`}else if(s.type==='cta'){sec.innerHTML=`<div class="wrap contactBox"><div>${title}${text}</div><div>${btn}</div></div>`}else{sec.innerHTML=`<div class="wrap about">${img}<div>${title}${text}${btn}</div></div>`}if(s.hidden)sec.style.display='none';return sec}
function applySections(builder){document.querySelectorAll('.raf-custom-section').forEach(x=>x.remove());const main=document.querySelector('#rafMain')||document.querySelector('main');if(!main)return;const customMap={};for(const s of builder.customSections||[]){const node=renderCustomSection(s);customMap[s.id]=node;main.appendChild(node)}const order=builder.sectionOrder||['Hero','TwoWorlds','About','Reviews','Brands','Contact'];for(const key of order){if(key==='Hero')continue;const n=sectionNode(key)||customMap[key];if(n)main.appendChild(n)}for(const s of builder.customSections||[]){if(!order.includes(s.id)&&customMap[s.id])main.appendChild(customMap[s.id])}}
function sourceForClone(c){if(c.sourceKey==='heroK'||c.sourceKey==='heroT'||c.sourceKey==='heroD')return document.getElementById(c.sourceKey);return document.querySelector(`[data-home-text="${CSS.escape(c.sourceKey||'')}"]`)}
function renderClones(builder){document.querySelectorAll('[data-raf-clone]').forEach(x=>x.remove());for(const c of builder.clones||[]){const src=sourceForClone(c);if(!src||!src.parentElement)continue;const el=src.cloneNode(true);el.removeAttribute('id');el.removeAttribute('data-home-text');el.dataset.rafClone=c.id;el.textContent=c.text??src.textContent;const s=cfgFor(c.styles||{});el.style.position='relative';el.style.transformOrigin='center center';el.style.transform=`translate(${Number(s.moveX)||0}px,${Number(s.moveY)||0}px) rotate(${Number(s.rotate)||0}deg) scale(${Number(s.scale)||1})`;if(s.width)el.style.width=`${s.width}px`;if(s.fontSize)el.style.fontSize=`${s.fontSize}px`;if(s.color)el.style.color=s.color;if(s.zIndex!=null)el.style.zIndex=String(s.zIndex);if(s.hidden)el.style.display='none';src.parentElement.appendChild(el)}}
function applyAnimations(){document.querySelectorAll('[data-raf-animation]').forEach(el=>{const a=el.dataset.rafAnimation;if(!a)return;el.style.animation='none';void el.offsetWidth;const map={fade:'rafFadeIn',slide:'rafSlideIn',zoom:'rafZoomIn'};if(map[a])el.style.animation=`${map[a]} var(--raf-anim-duration,700ms) both`})}
function ensureAnimationCSS(){if(document.querySelector('#rafBuilderAnimCss'))return;const s=document.createElement('style');s.id='rafBuilderAnimCss';s.textContent='@keyframes rafFadeIn{from{opacity:0}to{opacity:1}}@keyframes rafSlideIn{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:none}}@keyframes rafZoomIn{from{opacity:0;transform:scale(.94)}to{opacity:1;transform:none}}.rafVideoEmbed{width:100%;aspect-ratio:16/9;border-radius:18px;overflow:hidden;background:#080808;border:1px solid #ffffff16}.rafVideoEmbed iframe{display:block;width:100%;height:100%;border:0}.rafDirectVideo{display:block;width:100%;aspect-ratio:16/9;border-radius:18px;background:#080808}';document.head.appendChild(s)}
function render(raw={}){current=raw;ensureAnimationCSS();applyElements(raw);applySections(raw);renderClones(raw);applyAnimations()}
if(!EDITOR_MODE)onValue(ref(db,`${WEBSITE_ROOT}/public/builder`),s=>render(s.val()||{}));addEventListener('resize',()=>{if(!EDITOR_MODE)render(current)});
