import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { getStorage, ref as sRef, listAll, getDownloadURL, uploadBytesResumable } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";

const app=initializeApp(firebaseConfig);
const db=getDatabase(app),storage=getStorage(app);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clone=x=>JSON.parse(JSON.stringify(x));
const device=()=>innerWidth<=640?'mobile':innerWidth<=980?'tablet':'desktop';
const baseMedia=()=>({x:50,y:50,zoom:1});
const baseTransform=()=>({moveX:0,moveY:0,scale:1,rotate:0,width:null,fontSize:null,color:null,textAlign:null,fontFamily:null,fontWeight:null,lineHeight:null,letterSpacing:null});
const mediaDefaults={heroMedia:{url:''},photoPortal:{url:'assets/portal-photo.png'},filmPortal:{url:'assets/portal-film.png'},aboutPortrait:{url:'assets/about-portrait.jpg'}};
let draft=null,selected=null,overlay=null,saveTimer=null,drag=null,library=[];

function textKey(el){if(!el)return'';if(['heroK','heroT','heroD'].includes(el.id))return el.id;return el.dataset.homeText||''}
function mediaKey(el){return el?.dataset?.homeMedia||''}
function sectionKey(el){if(!el)return'';return el.matches('header.hero')?'Hero':(el.dataset.homeSection||'')}
function normalize(raw={}){return{site:raw.site||{},homeContent:raw.homeContent||{},homeMedia:raw.homeMedia||{},visualStyles:raw.visualStyles||{texts:{},sections:{}}}}
function ensure(){draft.site||={};draft.homeContent||={};draft.homeMedia||={};draft.visualStyles||={};draft.visualStyles.texts||={};draft.visualStyles.sections||={};for(const[k,v]of Object.entries(mediaDefaults)){draft.homeMedia[k]||={url:v.url,desktop:baseMedia(),tablet:baseMedia(),mobile:baseMedia()};for(const d of['desktop','tablet','mobile'])draft.homeMedia[k][d]={...baseMedia(),...(draft.homeMedia[k][d]||{})}}}
function tcfg(k){const d=device();draft.visualStyles.texts[k]||={};draft.visualStyles.texts[k][d]={...baseTransform(),...(draft.visualStyles.texts[k][d]||{})};return draft.visualStyles.texts[k][d]}
function scfg(k){const d=device();draft.visualStyles.sections[k]||={};draft.visualStyles.sections[k][d]||={};return draft.visualStyles.sections[k][d]}
function getText(k){return ['heroK','heroT','heroD'].includes(k)?(draft.site[k]??''):(draft.homeContent[k]??'')}
function setText(k,v){if(['heroK','heroT','heroD'].includes(k))draft.site[k]=v;else draft.homeContent[k]=v}
function status(t){const el=$('#rafEditorStatus');if(el)el.textContent=t}
function scheduleSave(){status('Zapisywanie…');clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,400)}
async function saveDraft(){try{await set(ref(db,`${WEBSITE_ROOT}/public/editorDraft`),draft);status('Wersja robocza ✓')}catch(e){console.error(e);status('Błąd zapisu')}}
function toHex(c){if(/^#[0-9a-f]{6}$/i.test(c||''))return c;const m=String(c||'').match(/\d+/g);return m?'#'+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,'0')).join(''):'#ffffff'}

function applyTextStyle(el,k){const c=draft.visualStyles?.texts?.[k]?.[device()]||{};el.style.fontSize=c.fontSize!=null?`${c.fontSize}px`:'';el.style.letterSpacing=c.letterSpacing!=null?`${c.letterSpacing}px`:'';el.style.lineHeight=c.lineHeight!=null?String(c.lineHeight):'';el.style.fontFamily=c.fontFamily||'';el.style.fontWeight=c.fontWeight||'';el.style.color=c.color||'';el.style.textAlign=c.textAlign||'';el.style.width=c.width?`${c.width}px`:'';el.style.maxWidth=c.width?`${c.width}px`:'';el.style.transformOrigin='center center';el.style.transform=`translate(${Number(c.moveX)||0}px,${Number(c.moveY)||0}px) rotate(${Number(c.rotate)||0}deg) scale(${Number(c.scale)||1})`;el.style.position='relative';el.style.zIndex='5'}
function applyAll(){
  $$('[data-home-text],#heroK,#heroT,#heroD').forEach(el=>{if(!el.isContentEditable){const k=textKey(el),v=getText(k);if(v!==''&&v!=null){if(el.dataset.multiline==='1'||k==='heroT')el.innerHTML=String(v).replace(/\n/g,'<br>');else el.textContent=v}}applyTextStyle(el,textKey(el))});
  $$('[data-home-media]').forEach(el=>{const k=mediaKey(el),m=draft.homeMedia[k];if(!m)return;const c={...baseMedia(),...(m[device()]||{})};if(m.url)el.src=m.url;el.style.objectFit='cover';el.style.objectPosition=`${c.x}% ${c.y}%`;el.style.transformOrigin=`${c.x}% ${c.y}%`;el.style.transform=`scale(${c.zoom})`;if(k==='heroMedia'&&m.url)el.style.opacity='1'});
  $$('[data-home-section],header.hero').forEach(el=>{const c=draft.visualStyles.sections?.[sectionKey(el)]?.[device()]||{};el.style.paddingTop=c.paddingTop!=null?`${c.paddingTop}px`:'';el.style.paddingBottom=c.paddingBottom!=null?`${c.paddingBottom}px`:'';el.style.background=c.background||'';el.style.display=c.hidden===true?'none':''});
  updateOverlay();
}

function injectUI(){
  const style=document.createElement('style');style.id='rafDirectEditorStyle';style.textContent=`
  body.raf-direct-edit [data-home-text],body.raf-direct-edit #heroK,body.raf-direct-edit #heroT,body.raf-direct-edit #heroD,body.raf-direct-edit [data-home-media]{cursor:pointer}
  body.raf-direct-edit .raf-direct-selected{outline:2px solid #18a7ff!important;outline-offset:4px}
  #rafEditorTop{position:fixed;left:50%;top:10px;transform:translateX(-50%);z-index:1000001;background:#111e;border:1px solid #ffffff24;border-radius:14px;padding:7px 9px;display:flex;gap:7px;align-items:center;box-shadow:0 10px 35px #0009;backdrop-filter:blur(18px);font:13px system-ui;color:#fff}
  #rafEditorTop button{border:1px solid #ffffff22;background:#ffffff0b;color:#fff;border-radius:9px;padding:8px 11px;cursor:pointer;font-weight:700}#rafEditorTop .publish{background:#fff;color:#111}#rafEditorTop .dev{color:#9b9ba0;font-size:11px;padding:0 4px}
  #rafEditorPanel{position:fixed;right:10px;top:68px;bottom:10px;width:310px;z-index:1000000;background:#111e;border:1px solid #ffffff24;border-radius:16px;padding:14px;overflow:auto;box-shadow:0 14px 50px #000b;backdrop-filter:blur(20px);font:13px system-ui;color:#fff}
  #rafEditorPanel h3{margin:3px 0 10px;font-size:18px}#rafEditorPanel .type{font-size:9px;letter-spacing:.16em;color:#999;text-transform:uppercase}#rafEditorPanel label{display:block;color:#aaa;font-size:11px;margin:11px 0 5px}#rafEditorPanel input,#rafEditorPanel select,#rafEditorPanel textarea{width:100%;background:#09090a;color:#fff;border:1px solid #343438;border-radius:9px;padding:9px;font:inherit}#rafEditorPanel textarea{min-height:82px;resize:vertical}#rafEditorPanel .row{display:grid;grid-template-columns:1fr 1fr;gap:8px}#rafEditorPanel button{border:1px solid #ffffff22;background:#ffffff0b;color:#fff;border-radius:9px;padding:9px 10px;cursor:pointer;margin-top:8px}#rafEditorPanel .primary{background:#fff;color:#111;font-weight:800}
  #rafEditorNav{position:fixed;left:10px;top:68px;z-index:1000000;width:160px;background:#111e;border:1px solid #ffffff24;border-radius:14px;padding:10px;backdrop-filter:blur(20px);font:12px system-ui;color:#fff}#rafEditorNav button{display:block;width:100%;text-align:left;border:1px solid #ffffff1d;background:#ffffff08;color:#fff;border-radius:8px;padding:8px;margin:5px 0;cursor:pointer}
  .raf-direct-box{position:absolute;z-index:999999;border:2px solid #18a7ff;box-sizing:border-box;pointer-events:none}.raf-direct-move,.raf-direct-scale,.raf-direct-rotate{pointer-events:auto;touch-action:none;user-select:none}.raf-direct-move{position:absolute;left:4px;top:-31px;background:#168ee6;color:#fff;border-radius:7px;padding:5px 9px;font:700 12px system-ui;cursor:move}.raf-direct-scale,.raf-direct-rotate{position:absolute;width:16px;height:16px;border-radius:50%;background:#fff;border:2px solid #168ee6;box-sizing:border-box}.raf-direct-scale{right:-9px;bottom:-9px;cursor:nwse-resize}.raf-direct-rotate{left:50%;top:-39px;transform:translateX(-50%);cursor:grab}.raf-direct-rotate:after{content:'';position:absolute;left:6px;top:14px;height:22px;border-left:2px solid #18a7ff}.raf-direct-size{position:absolute;right:4px;top:-28px;background:#111;color:#fff;border:1px solid #ffffff30;border-radius:5px;padding:3px 6px;font:11px system-ui}
  #rafMediaModal{position:fixed;inset:70px 40px 40px;z-index:1000003;background:#111;border:1px solid #ffffff25;border-radius:18px;padding:14px;display:none;grid-template-rows:auto 1fr;color:#fff;font:13px system-ui}#rafMediaModal.open{display:grid}.rafMediaHead{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.rafMediaGrid{overflow:auto;display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.rafMediaItem{border:1px solid #ffffff20;border-radius:10px;overflow:hidden;cursor:pointer}.rafMediaItem img{display:block;width:100%;aspect-ratio:1;object-fit:cover}.rafMediaItem div{padding:6px;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  @media(max-width:900px){#rafEditorNav{display:none}#rafEditorPanel{left:8px;right:8px;top:auto;bottom:8px;width:auto;height:290px}#rafEditorTop{left:8px;right:8px;transform:none;justify-content:center;flex-wrap:wrap}.rafMediaGrid{grid-template-columns:repeat(3,minmax(0,1fr))}}
  `;document.head.appendChild(style);document.body.classList.add('raf-direct-edit');
  const top=document.createElement('div');top.id='rafEditorTop';top.innerHTML=`<b>RAF.studio EDYTOR</b><span class="dev">${device().toUpperCase()} • prawdziwa strona 1:1</span><span id="rafEditorStatus">Ładowanie…</span><button id="rafPreviewBtn">Podgląd</button><button id="rafExitBtn">Wyjdź</button><button id="rafPublishBtn" class="publish">OPUBLIKUJ</button>`;document.body.appendChild(top);
  const nav=document.createElement('div');nav.id='rafEditorNav';nav.innerHTML=`<b>Strona główna</b><button data-jump="hero">01 Hero</button><button data-jump="TwoWorlds">02 Dwa światy</button><button data-jump="About">03 O mnie</button><button data-jump="Reviews">04 Opinie</button><button data-jump="Brands">05 Marki</button><button data-jump="Contact">06 Kontakt</button>`;document.body.appendChild(nav);
  const panel=document.createElement('div');panel.id='rafEditorPanel';panel.innerHTML='<div class="type">EDYTOR</div><h3>Kliknij element</h3><p style="color:#999">1 klik = zaznacz • 2 klik tekstu = pisz bezpośrednio.</p>';document.body.appendChild(panel);
  const media=document.createElement('div');media.id='rafMediaModal';media.innerHTML=`<div class="rafMediaHead"><b>Biblioteka zdjęć</b><div><label style="cursor:pointer;border:1px solid #ffffff22;border-radius:9px;padding:8px 10px">+ Wgraj<input id="rafMediaUpload" type="file" accept="image/*" multiple hidden></label> <button id="rafMediaClose">✕</button></div></div><div class="rafMediaGrid" id="rafMediaGrid"></div>`;document.body.appendChild(media);
  $('#rafExitBtn').onclick=()=>location.href='index.html';
  $('#rafPreviewBtn').onclick=()=>togglePreview();
  $('#rafPublishBtn').onclick=publish;
  $('#rafMediaClose').onclick=()=>media.classList.remove('open');
  $('#rafMediaUpload').onchange=uploadMedia;
  $$('[data-jump]',nav).forEach(b=>b.onclick=()=>{const k=b.dataset.jump,el=k==='hero'?$('header.hero'):$(`[data-home-section="${k}"]`);el?.scrollIntoView({behavior:'smooth',block:'start'})});
}

function bindPage(){
  for(const el of $$('[data-home-text],[data-home-media],[data-home-section],#heroK,#heroT,#heroD,header.hero')){
    if(el.dataset.directBound==='1')continue;el.dataset.directBound='1';
    el.addEventListener('click',e=>{if(document.body.classList.contains('raf-preview-mode'))return;e.preventDefault();e.stopPropagation();const t=e.target.closest('[data-home-text],[data-home-media],#heroK,#heroT,#heroD')||e.target.closest('[data-home-section],header.hero')||el;select(t)});
    if(el.matches('[data-home-text],#heroK,#heroT,#heroD'))el.addEventListener('dblclick',e=>{if(document.body.classList.contains('raf-preview-mode'))return;e.preventDefault();e.stopPropagation();select(el);inlineEdit(el)});
  }
  document.addEventListener('click',e=>{if(document.body.classList.contains('raf-preview-mode'))return;const a=e.target.closest('a');if(a&&!e.target.closest('#rafEditorTop,#rafEditorPanel,#rafEditorNav,#rafMediaModal')){e.preventDefault();e.stopPropagation()}},true);
  document.addEventListener('pointermove',pointerMove,true);document.addEventListener('pointerup',pointerUp,true);document.addEventListener('pointercancel',pointerUp,true);addEventListener('scroll',updateOverlay,{passive:true});addEventListener('resize',()=>{applyAll();updateOverlay();const d=$('#rafEditorTop .dev');if(d)d.textContent=`${device().toUpperCase()} • prawdziwa strona 1:1`});
}
function select(el){$$('.raf-direct-selected').forEach(x=>x.classList.remove('raf-direct-selected'));el.classList.add('raf-direct-selected');selected=el;renderPanel();renderOverlay()}
function inlineEdit(el){removeOverlay();el.contentEditable='true';el.focus();const k=textKey(el);const inp=()=>{setText(k,el.innerText);scheduleSave()};const done=()=>{el.contentEditable='false';el.removeEventListener('input',inp);el.removeEventListener('blur',done);setText(k,el.innerText);scheduleSave();renderPanel();renderOverlay()};el.addEventListener('input',inp);el.addEventListener('blur',done)}
function removeOverlay(){overlay?.remove();overlay=null}
function renderOverlay(){removeOverlay();if(!selected||document.body.classList.contains('raf-preview-mode')||!selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return;overlay=document.createElement('div');overlay.className='raf-direct-box';overlay.innerHTML='<div class="raf-direct-move">✥ PRZESUŃ</div><div class="raf-direct-size"></div><div class="raf-direct-rotate"></div><div class="raf-direct-scale"></div>';document.body.appendChild(overlay);$('.raf-direct-move',overlay).onpointerdown=e=>beginTransform('move',e);$('.raf-direct-scale',overlay).onpointerdown=e=>beginTransform('scale',e);$('.raf-direct-rotate',overlay).onpointerdown=e=>beginTransform('rotate',e);updateOverlay()}
function updateOverlay(){if(!overlay||!selected?.isConnected)return;const r=selected.getBoundingClientRect();overlay.style.left=`${r.left+scrollX}px`;overlay.style.top=`${r.top+scrollY}px`;overlay.style.width=`${r.width}px`;overlay.style.height=`${r.height}px`;$('.raf-direct-size',overlay).textContent=`${Math.round(r.width)} × ${Math.round(r.height)}`}
function beginTransform(mode,e){if(!selected)return;e.preventDefault();e.stopPropagation();const c=tcfg(textKey(selected)),r=selected.getBoundingClientRect();drag={mode,pid:e.pointerId,sx:e.clientX,sy:e.clientY,start:{...c},cx:r.left+r.width/2,cy:r.top+r.height/2,dist:Math.max(10,Math.hypot(e.clientX-(r.left+r.width/2),e.clientY-(r.top+r.height/2))),angle:Math.atan2(e.clientY-(r.top+r.height/2),e.clientX-(r.left+r.width/2))};try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}}
function pointerMove(e){if(!drag||e.pointerId!==drag.pid||!selected)return;e.preventDefault();const c=tcfg(textKey(selected));if(drag.mode==='move'){c.moveX=drag.start.moveX+(e.clientX-drag.sx);c.moveY=drag.start.moveY+(e.clientY-drag.sy)}else if(drag.mode==='scale'){const dist=Math.max(10,Math.hypot(e.clientX-drag.cx,e.clientY-drag.cy));c.scale=Math.max(.2,Math.min(4,drag.start.scale*(dist/drag.dist)))}else{const a=Math.atan2(e.clientY-drag.cy,e.clientX-drag.cx);c.rotate=drag.start.rotate+(a-drag.angle)*180/Math.PI;if(e.shiftKey)c.rotate=Math.round(c.rotate/15)*15}applyTextStyle(selected,textKey(selected));syncTransformFields();updateOverlay()}
function pointerUp(e){if(!drag||e.pointerId!==drag.pid)return;drag=null;scheduleSave();renderPanel();updateOverlay()}
function syncTransformFields(){if(!selected)return;const c=tcfg(textKey(selected));if($('#deX'))$('#deX').value=Math.round(c.moveX);if($('#deY'))$('#deY').value=Math.round(c.moveY);if($('#deScale'))$('#deScale').value=Number(c.scale).toFixed(2);if($('#deRotate'))$('#deRotate').value=Math.round(c.rotate)}

function renderPanel(){const p=$('#rafEditorPanel');if(!selected){p.innerHTML='<div class="type">EDYTOR</div><h3>Kliknij element</h3>';return}if(selected.matches('[data-home-media]'))return renderImagePanel();if(selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return renderTextPanel();return renderSectionPanel()}
function renderTextPanel(){const p=$('#rafEditorPanel'),k=textKey(selected),c=tcfg(k),cs=getComputedStyle(selected);p.innerHTML=`<div class="type">TEKST / POLE</div><h3>${k}</h3><label>Treść</label><textarea id="deText"></textarea><div class="row"><div><label>X</label><input id="deX" type="number"></div><div><label>Y</label><input id="deY" type="number"></div></div><div class="row"><div><label>Skala</label><input id="deScale" type="number" min=".2" max="4" step=".05"></div><div><label>Obrót°</label><input id="deRotate" type="number"></div></div><label>Szerokość pola px</label><input id="deWidth" type="number" min="0"><div class="row"><div><label>Rozmiar px</label><input id="deSize" type="number" min="8" max="220"></div><div><label>Grubość</label><select id="deWeight"><option>300</option><option>400</option><option>500</option><option>600</option><option>700</option><option>800</option><option>900</option></select></div></div><label>Czcionka</label><select id="deFont"><option value="Inter,system-ui,Arial,sans-serif">Inter / system</option><option value="Arial,sans-serif">Arial</option><option value="Trebuchet MS,sans-serif">Trebuchet</option><option value="Verdana,sans-serif">Verdana</option><option value="Georgia,serif">Georgia</option></select><div class="row"><div><label>Kolor</label><input id="deColor" type="color"></div><div><label>Wyrównanie</label><select id="deAlign"><option value="left">Lewo</option><option value="center">Środek</option><option value="right">Prawo</option></select></div></div><div class="row"><div><label>Interlinia</label><input id="deLine" type="number" min=".6" max="3" step=".05"></div><div><label>Litery px</label><input id="deLetter" type="number" min="-10" max="30" step=".5"></div></div><button id="deReset">Reset pozycji</button>`;
  $('#deText').value=getText(k)||selected.innerText;$('#deX').value=Math.round(c.moveX);$('#deY').value=Math.round(c.moveY);$('#deScale').value=c.scale;$('#deRotate').value=Math.round(c.rotate);$('#deWidth').value=c.width||0;$('#deSize').value=c.fontSize||Math.round(parseFloat(cs.fontSize));$('#deWeight').value=c.fontWeight||cs.fontWeight;$('#deFont').value=c.fontFamily||'Inter,system-ui,Arial,sans-serif';$('#deColor').value=toHex(c.color||cs.color);$('#deAlign').value=c.textAlign||cs.textAlign||'left';$('#deLine').value=c.lineHeight||1;$('#deLetter').value=c.letterSpacing||0;
  const apply=()=>{setText(k,$('#deText').value);Object.assign(c,{moveX:+$('#deX').value||0,moveY:+$('#deY').value||0,scale:+$('#deScale').value||1,rotate:+$('#deRotate').value||0,width:+$('#deWidth').value||null,fontSize:+$('#deSize').value||null,fontWeight:$('#deWeight').value,fontFamily:$('#deFont').value,color:$('#deColor').value,textAlign:$('#deAlign').value,lineHeight:+$('#deLine').value||null,letterSpacing:+$('#deLetter').value||0});if(!selected.isContentEditable)selected.textContent=$('#deText').value;applyTextStyle(selected,k);updateOverlay();scheduleSave()};['deText','deX','deY','deScale','deRotate','deWidth','deSize','deWeight','deFont','deColor','deAlign','deLine','deLetter'].forEach(id=>$('#'+id).addEventListener('input',apply));$('#deReset').onclick=()=>{Object.assign(c,baseTransform());applyTextStyle(selected,k);renderPanel();updateOverlay();scheduleSave()}}
function renderImagePanel(){const p=$('#rafEditorPanel'),k=mediaKey(selected),m=draft.homeMedia[k],c=m[device()];p.innerHTML=`<div class="type">ZDJĘCIE</div><h3>${k}</h3><button id="deChoose" class="primary">Zmień zdjęcie</button><label>Kadr X</label><input id="deImgX" type="range" min="0" max="100" value="${c.x}"><label>Kadr Y</label><input id="deImgY" type="range" min="0" max="100" value="${c.y}"><label>Zoom</label><input id="deImgZoom" type="range" min="1" max="3" step=".02" value="${c.zoom}">`;const apply=()=>{c.x=+$('#deImgX').value;c.y=+$('#deImgY').value;c.zoom=+$('#deImgZoom').value;applyAll();scheduleSave()};['deImgX','deImgY','deImgZoom'].forEach(id=>$('#'+id).oninput=apply);$('#deChoose').onclick=openMedia}
function renderSectionPanel(){const p=$('#rafEditorPanel'),k=sectionKey(selected),c=scfg(k),cs=getComputedStyle(selected);p.innerHTML=`<div class="type">SEKCJA</div><h3>${k}</h3><label>Odstęp góra</label><input id="deTop" type="number"><label>Odstęp dół</label><input id="deBottom" type="number"><label>Kolor tła</label><input id="deBg" type="color"><label><input id="deHide" type="checkbox" style="width:auto"> Ukryj na tym urządzeniu</label>`;$('#deTop').value=c.paddingTop??(parseInt(cs.paddingTop)||0);$('#deBottom').value=c.paddingBottom??(parseInt(cs.paddingBottom)||0);$('#deBg').value=toHex(c.background||cs.backgroundColor);$('#deHide').checked=c.hidden===true;const apply=()=>{c.paddingTop=+$('#deTop').value;c.paddingBottom=+$('#deBottom').value;c.background=$('#deBg').value;c.hidden=$('#deHide').checked;applyAll();scheduleSave()};['deTop','deBottom','deBg','deHide'].forEach(id=>$('#'+id).addEventListener('change',apply))}

function togglePreview(){const on=document.body.classList.toggle('raf-preview-mode');$('#rafEditorPanel').style.display=on?'none':'';$('#rafEditorNav').style.display=on?'none':'';$('#rafPreviewBtn').textContent=on?'Wróć do edycji':'Podgląd';if(on){removeOverlay();$$('.raf-direct-selected').forEach(x=>x.classList.remove('raf-direct-selected'))}else if(selected){selected.classList.add('raf-direct-selected');renderOverlay()}}
async function publish(){const b=$('#rafPublishBtn');b.disabled=true;b.textContent='PUBLIKOWANIE…';try{await Promise.all([set(ref(db,`${WEBSITE_ROOT}/public/site`),draft.site),set(ref(db,`${WEBSITE_ROOT}/public/homeContent`),draft.homeContent),set(ref(db,`${WEBSITE_ROOT}/public/homeMedia`),draft.homeMedia),set(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),draft.visualStyles)]);status('Opublikowano ✓');b.textContent='OPUBLIKOWANO ✓';setTimeout(()=>b.textContent='OPUBLIKUJ',1500)}catch(e){console.error(e);alert('Błąd publikacji: '+e.message);b.textContent='OPUBLIKUJ'}finally{b.disabled=false}}
async function loadMedia(){const grid=$('#rafMediaGrid');grid.innerHTML='<p>Ładowanie…</p>';const res=await listAll(sRef(storage,'website/media'));library=[];for(const it of res.items){if(!/\.(jpe?g|png|webp|gif|avif)$/i.test(it.name))continue;try{library.push({name:it.name,url:await getDownloadURL(it)})}catch{}}grid.innerHTML=library.map((x,i)=>`<div class="rafMediaItem" data-i="${i}"><img loading="lazy" src="${x.url}"><div>${x.name}</div></div>`).join('');$$('.rafMediaItem',grid).forEach(el=>el.onclick=()=>{draft.homeMedia[mediaKey(selected)].url=library[+el.dataset.i].url;applyAll();$('#rafMediaModal').classList.remove('open');scheduleSave()})}
function openMedia(){$('#rafMediaModal').classList.add('open');if(!library.length)loadMedia().catch(console.error)}
function uploadMedia(){for(const file of [...$('#rafMediaUpload').files]){const path=`website/media/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const task=uploadBytesResumable(sRef(storage,path),file);task.on('state_changed',null,console.error,()=>loadMedia())}}

async function init(){injectUI();status('Ładowanie…');const pubSnap=await get(ref(db,`${WEBSITE_ROOT}/public`)),pub=normalize(pubSnap.val()||{}),draftSnap=await get(ref(db,`${WEBSITE_ROOT}/public/editorDraft`));draft=draftSnap.exists()?normalize(draftSnap.val()):clone(pub);draft.site={...pub.site,...draft.site};draft.homeContent={...pub.homeContent,...draft.homeContent};draft.homeMedia={...pub.homeMedia,...draft.homeMedia};draft.visualStyles={texts:{...(pub.visualStyles?.texts||{}),...(draft.visualStyles?.texts||{})},sections:{...(pub.visualStyles?.sections||{}),...(draft.visualStyles?.sections||{})}};ensure();applyAll();bindPage();status('Gotowe ✓')}
init().catch(e=>{console.error(e);status('Błąd edytora');alert('Błąd edytora: '+e.message)});
