import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { getStorage, ref as sRef, listAll, getDownloadURL, uploadBytesResumable } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";

const app=initializeApp(firebaseConfig),db=getDatabase(app),storage=getStorage(app);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const frame=$('#siteFrame'),inspector=$('#inspector'),deviceFrame=$('#deviceFrame'),draftState=$('#draftState');
const mediaModal=$('#mediaModal'),mediaGrid=$('#mediaGrid'),mediaCount=$('#mediaCount');
let device='desktop',selected=null,draft=null,published=null,library=[],previewMode=false,cropMode=false;
let undoStack=[],redoStack=[],saveTimer=null;
const clone=x=>JSON.parse(JSON.stringify(x));
const baseDev=()=>({x:50,y:50,zoom:1});
const mediaDefaults={heroMedia:{url:''},photoPortal:{url:'assets/portal-photo.png'},filmPortal:{url:'assets/portal-film.png'},aboutPortrait:{url:'assets/about-portrait.jpg'}};

function status(t){draftState.textContent=t}
function normPublic(raw={}){return{site:raw.site||{},homeContent:raw.homeContent||{},homeMedia:raw.homeMedia||{},visualStyles:raw.visualStyles||{texts:{},sections:{}},updatedAt:Date.now()}}
function ensureMedia(){draft.homeMedia||={};for(const[k,v]of Object.entries(mediaDefaults)){draft.homeMedia[k]||={url:v.url,desktop:baseDev(),tablet:baseDev(),mobile:baseDev()};for(const d of['desktop','tablet','mobile'])draft.homeMedia[k][d]={...baseDev(),...(draft.homeMedia[k][d]||{})}}}
function ensureStyles(){draft.visualStyles||={};draft.visualStyles.texts||={};draft.visualStyles.sections||={}}
function pushHistory(){undoStack.push(clone(draft));if(undoStack.length>40)undoStack.shift();redoStack=[]}
function scheduleDraft(){status('Zapisywanie roboczo…');clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,450)}
async function saveDraft(){try{draft.updatedAt=Date.now();await set(ref(db,`${WEBSITE_ROOT}/public/editorDraft`),draft);status('Wersja robocza ✓')}catch(e){status('Błąd zapisu roboczego');console.error(e)}}
function doc(){return frame.contentDocument}
function win(){return frame.contentWindow}
function textKey(el){if(['heroK','heroT','heroD'].includes(el.id))return el.id;return el.dataset.homeText||''}
function mediaKey(el){return el.dataset.homeMedia||''}
function sectionKey(el){if(el.matches('header.hero'))return'Hero';return el.dataset.homeSection||''}
function textValue(key){if(['heroK','heroT','heroD'].includes(key))return draft.site?.[key]??'';return draft.homeContent?.[key]??''}
function setTextValue(key,val){if(['heroK','heroT','heroD'].includes(key)){draft.site||={};draft.site[key]=val}else{draft.homeContent||={};draft.homeContent[key]=val}}
function styleCfg(key){ensureStyles();draft.visualStyles.texts[key]||={};draft.visualStyles.texts[key][device]||={};return draft.visualStyles.texts[key][device]}
function sectionCfg(key){ensureStyles();draft.visualStyles.sections[key]||={};draft.visualStyles.sections[key][device]||={};return draft.visualStyles.sections[key][device]}

function installFrameEditing(){const d=doc();if(!d)return;let style=d.querySelector('#rafVisualEditorStyle');if(!style){style=d.createElement('style');style.id='rafVisualEditorStyle';d.head.appendChild(style)}style.textContent=`body.ve-editing [data-home-text],body.ve-editing #heroK,body.ve-editing #heroT,body.ve-editing #heroD,body.ve-editing [data-home-media]{outline:1px dashed transparent;outline-offset:4px;cursor:pointer}body.ve-editing [data-home-text]:hover,body.ve-editing #heroK:hover,body.ve-editing #heroT:hover,body.ve-editing #heroD:hover,body.ve-editing [data-home-media]:hover{outline-color:#35a7ff}body.ve-editing [data-home-section]:hover,body.ve-editing header.hero:hover{box-shadow:inset 0 0 0 1px #35a7ff66}body.ve-editing .ve-selected{outline:2px solid #35a7ff!important;outline-offset:5px}body.ve-editing [contenteditable=true]{outline:2px solid #fff!important}body.ve-editing.ve-crop [data-home-media].ve-selected{cursor:move}body.ve-preview .ve-selected{outline:0!important}`;d.body.classList.add('ve-editing');bindSelectable();applyDraftToFrame();setTimeout(applyDraftToFrame,500)}
function bindSelectable(){const d=doc();const nodes=[...d.querySelectorAll('[data-home-text],[data-home-media],[data-home-section],#heroK,#heroT,#heroD,header.hero')];for(const el of nodes){if(el.dataset.veBound)return;el.dataset.veBound='1';el.addEventListener('click',e=>{if(previewMode)return;e.preventDefault();e.stopPropagation();const target=e.target.closest('[data-home-text],[data-home-media],#heroK,#heroT,#heroD')||e.target.closest('[data-home-section],header.hero')||el;selectElement(target)});if(el.matches('[data-home-text],#heroK,#heroT,#heroD')){el.addEventListener('dblclick',e=>{if(previewMode)return;e.preventDefault();e.stopPropagation();selectElement(el);startInlineEdit(el)});el.addEventListener('input',()=>{const key=textKey(el);if(!key)return;setTextValue(key,el.innerText);scheduleDraft()})}}}
function selectElement(el){const d=doc();d.querySelectorAll('.ve-selected').forEach(x=>x.classList.remove('ve-selected'));el.classList.add('ve-selected');selected=el;cropMode=false;d.body.classList.remove('ve-crop');renderInspector()}
function startInlineEdit(el){el.contentEditable='true';el.focus();const end=()=>{el.contentEditable='false';el.removeEventListener('blur',end);setTextValue(textKey(el),el.innerText);scheduleDraft();renderInspector()};el.addEventListener('blur',end)}
function applyTextStyles(el,key){const cfg=draft.visualStyles?.texts?.[key]?.[device]||{};for(const[k,v]of Object.entries(cfg)){if(v===''||v==null)continue;if(k==='fontSize')el.style.fontSize=v+'px';else if(k==='letterSpacing')el.style.letterSpacing=v+'px';else if(k==='lineHeight')el.style.lineHeight=v;else if(k==='fontFamily')el.style.fontFamily=v;else if(k==='fontWeight')el.style.fontWeight=v;else if(k==='color')el.style.color=v;else if(k==='textAlign')el.style.textAlign=v;else if(k==='maxWidth')el.style.maxWidth=v+'px'}}
function applySectionStyles(el,key){const cfg=draft.visualStyles?.sections?.[key]?.[device]||{};if(cfg.paddingTop!=null)el.style.paddingTop=cfg.paddingTop+'px';if(cfg.paddingBottom!=null)el.style.paddingBottom=cfg.paddingBottom+'px';if(cfg.background)el.style.background=cfg.background;if(cfg.hidden===true)el.style.display='none';else el.style.display=''}
function applyDraftToFrame(){const d=doc();if(!d||!draft)return;d.querySelectorAll('[data-home-text],#heroK,#heroT,#heroD').forEach(el=>{const key=textKey(el),val=textValue(key);if(val!==undefined&&val!==''){if(el.dataset.multiline==='1'||key==='heroT')el.innerHTML=String(val).replace(/\n/g,'<br>');else el.textContent=val}el.removeAttribute('style');applyTextStyles(el,key)});d.querySelectorAll('[data-home-media]').forEach(el=>{const key=mediaKey(el),m=draft.homeMedia?.[key];if(!m)return;const c={...baseDev(),...(m[device]||{})};if(m.url)el.src=m.url;el.style.objectFit='cover';el.style.objectPosition=`${c.x}% ${c.y}%`;el.style.transformOrigin=`${c.x}% ${c.y}%`;el.style.transform=`scale(${c.zoom})`;if(key==='heroMedia'&&m.url)el.style.opacity='1'});d.querySelectorAll('[data-home-section],header.hero').forEach(el=>applySectionStyles(el,sectionKey(el)))}
function commonHeader(type,name){return`<div class="type">${type}</div><h3>${name}</h3>`}
function toHex(c){if(/^#[0-9a-f]{6}$/i.test(c))return c;const m=String(c).match(/\d+/g);if(!m)return'#ffffff';return'#'+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,'0')).join('')}
function renderInspector(){if(!selected){inspector.innerHTML='<div class="veEmpty"><b>Wybierz element</b><p>Kliknij tekst, zdjęcie albo sekcję na podglądzie.</p></div>';return}if(selected.matches('[data-home-media]'))return renderImageInspector();if(selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return renderTextInspector();return renderSectionInspector()}
function renderTextInspector(){const key=textKey(selected),cfg=styleCfg(key),val=textValue(key)||selected.innerText,cs=win().getComputedStyle(selected);inspector.innerHTML=commonHeader('TEKST',key)+`<label>Treść</label><textarea id="iText"></textarea><div class="veHint">Dwuklik na tekście = pisanie bezpośrednio na stronie.</div><label>Czcionka</label><select id="iFont"><option value="Inter,system-ui,Arial,sans-serif">Inter / systemowa</option><option value="Arial,sans-serif">Arial</option><option value="Trebuchet MS,sans-serif">Trebuchet</option><option value="Verdana,sans-serif">Verdana</option><option value="Georgia,serif">Georgia</option></select><div class="veRow"><div><label>Rozmiar px</label><input id="iSize" type="number" min="8" max="220"></div><div><label>Grubość</label><select id="iWeight"><option>300</option><option>400</option><option>500</option><option>600</option><option>700</option><option>800</option><option>900</option></select></div></div><div class="veRow"><div><label>Kolor</label><input id="iColor" type="color"></div><div><label>Wyrównanie</label><select id="iAlign"><option value="left">Lewo</option><option value="center">Środek</option><option value="right">Prawo</option></select></div></div><div class="veRow"><div><label>Interlinia</label><input id="iLine" type="number" min="0.6" max="3" step="0.05"></div><div><label>Litery px</label><input id="iLetter" type="number" min="-10" max="30" step="0.5"></div></div><label>Maks. szerokość px (0 = auto)</label><input id="iMax" type="number" min="0" max="1600"><div class="veBtns"><button id="resetText">Reset wyglądu</button></div>`;$('#iText').value=val;$('#iFont').value=cfg.fontFamily||'Inter,system-ui,Arial,sans-serif';$('#iSize').value=cfg.fontSize||Math.round(parseFloat(cs.fontSize));$('#iWeight').value=cfg.fontWeight||cs.fontWeight;$('#iColor').value=toHex(cfg.color||cs.color);$('#iAlign').value=cfg.textAlign||cs.textAlign||'left';$('#iLine').value=cfg.lineHeight||1;$('#iLetter').value=cfg.letterSpacing||0;$('#iMax').value=cfg.maxWidth||0;const change=()=>{setTextValue(key,$('#iText').value);Object.assign(cfg,{fontFamily:$('#iFont').value,fontSize:+$('#iSize').value,fontWeight:$('#iWeight').value,color:$('#iColor').value,textAlign:$('#iAlign').value,lineHeight:+$('#iLine').value,letterSpacing:+$('#iLetter').value,maxWidth:+$('#iMax').value||null});applyDraftToFrame();scheduleDraft()};['iFont','iSize','iWeight','iColor','iAlign','iLine','iLetter','iMax'].forEach(id=>$('#'+id).onchange=()=>{pushHistory();change()});$('#iText').oninput=()=>{setTextValue(key,$('#iText').value);applyDraftToFrame();scheduleDraft()};$('#resetText').onclick=()=>{pushHistory();delete draft.visualStyles.texts[key][device];applyDraftToFrame();renderInspector();scheduleDraft()}}
function renderImageInspector(){const key=mediaKey(selected),m=draft.homeMedia[key],cfg=m[device];inspector.innerHTML=commonHeader('ZDJĘCIE',key)+`<div class="veHint">Kliknij „Kadruj na stronie”, potem przeciągaj zdjęcie myszką.</div><div class="veBtns"><button id="chooseImg" class="primary">Zmień zdjęcie</button><button id="cropBtn">✥ Kadruj na stronie</button></div><label>Kadr poziomo <span id="xVal"></span></label><input id="iX" type="range" min="0" max="100"><label>Kadr pionowo <span id="yVal"></span></label><input id="iY" type="range" min="0" max="100"><label>Zoom <span id="zVal"></span></label><input id="iZoom" type="range" min="1" max="3" step="0.02"><div class="veBtns"><button id="centerImg">Wyśrodkuj</button><button id="resetImg">Reset kadru</button></div>`;$('#iX').value=cfg.x;$('#iY').value=cfg.y;$('#iZoom').value=cfg.zoom;const show=()=>{$('#xVal').textContent=$('#iX').value+'%';$('#yVal').textContent=$('#iY').value+'%';$('#zVal').textContent=Number($('#iZoom').value).toFixed(2)+'×'};show();const apply=()=>{cfg.x=+$('#iX').value;cfg.y=+$('#iY').value;cfg.zoom=+$('#iZoom').value;show();applyDraftToFrame();scheduleDraft()};['iX','iY','iZoom'].forEach(id=>$('#'+id).oninput=apply);$('#chooseImg').onclick=openMedia;$('#centerImg').onclick=()=>{$('#iX').value=50;$('#iY').value=50;apply()};$('#resetImg').onclick=()=>{$('#iX').value=50;$('#iY').value=50;$('#iZoom').value=1;apply()};$('#cropBtn').onclick=toggleCrop}
function renderSectionInspector(){const key=sectionKey(selected),cfg=sectionCfg(key),cs=win().getComputedStyle(selected);inspector.innerHTML=commonHeader('SEKCJA',key)+`<label>Odstęp góra px</label><input id="sTop" type="number" min="0" max="400"><label>Odstęp dół px</label><input id="sBottom" type="number" min="0" max="400"><label>Kolor tła</label><input id="sBg" type="color"><label><input id="sHide" type="checkbox" style="width:auto"> Ukryj na tym urządzeniu</label><div class="veBtns"><button id="sReset">Reset sekcji</button></div>`;$('#sTop').value=cfg.paddingTop??(parseInt(cs.paddingTop)||0);$('#sBottom').value=cfg.paddingBottom??(parseInt(cs.paddingBottom)||0);$('#sBg').value=toHex(cfg.background||cs.backgroundColor);$('#sHide').checked=cfg.hidden===true;const apply=()=>{Object.assign(cfg,{paddingTop:+$('#sTop').value,paddingBottom:+$('#sBottom').value,background:$('#sBg').value,hidden:$('#sHide').checked});applyDraftToFrame();scheduleDraft()};['sTop','sBottom','sBg','sHide'].forEach(id=>$('#'+id).onchange=()=>{pushHistory();apply()});$('#sReset').onclick=()=>{pushHistory();delete draft.visualStyles.sections[key][device];applyDraftToFrame();renderInspector();scheduleDraft()}}
function toggleCrop(){cropMode=!cropMode;doc().body.classList.toggle('ve-crop',cropMode);$('#cropBtn').textContent=cropMode?'✓ Zakończ kadrowanie':'✥ Kadruj na stronie';if(!cropMode)return;const el=selected,key=mediaKey(el),cfg=draft.homeMedia[key][device];let start=null,base=null;el.onpointerdown=e=>{if(!cropMode)return;e.preventDefault();start={x:e.clientX,y:e.clientY};base={x:cfg.x,y:cfg.y};el.setPointerCapture?.(e.pointerId)};el.onpointermove=e=>{if(!start||!cropMode)return;const r=el.getBoundingClientRect();cfg.x=Math.max(0,Math.min(100,base.x-(e.clientX-start.x)/Math.max(1,r.width)*100));cfg.y=Math.max(0,Math.min(100,base.y-(e.clientY-start.y)/Math.max(1,r.height)*100));applyDraftToFrame()};el.onpointerup=()=>{if(start){start=null;scheduleDraft()}}}
async function loadMedia(){mediaGrid.innerHTML='<p>Ładowanie…</p>';try{const res=await listAll(sRef(storage,'website/media'));library=[];for(const it of res.items){if(!/\.(jpe?g|png|webp|gif|avif)$/i.test(it.name))continue;try{library.push({name:it.name,url:await getDownloadURL(it)})}catch{}}mediaCount.textContent=library.length+' zdjęć';mediaGrid.innerHTML=library.map((x,i)=>`<div class="veMediaItem" data-i="${i}"><img loading="lazy" src="${x.url}"><div>${x.name}</div></div>`).join('');$$('.veMediaItem',mediaGrid).forEach(el=>el.onclick=()=>chooseMedia(+el.dataset.i))}catch(e){mediaGrid.innerHTML='<p>Nie udało się wczytać biblioteki.</p>';console.error(e)}}
function openMedia(){mediaModal.hidden=false;if(!library.length)loadMedia()}
function chooseMedia(i){if(!selected?.matches('[data-home-media]'))return;pushHistory();draft.homeMedia[mediaKey(selected)].url=library[i].url;applyDraftToFrame();mediaModal.hidden=true;scheduleDraft();renderInspector()}
$('#mediaClose').onclick=()=>mediaModal.hidden=true;$('#mediaUpload').onchange=()=>[...$('#mediaUpload').files].forEach(file=>{const path=`website/media/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,task=uploadBytesResumable(sRef(storage,path),file);mediaCount.textContent='Wysyłanie '+file.name;task.on('state_changed',null,()=>mediaCount.textContent='Błąd uploadu',async()=>loadMedia())});
function setDevice(d){device=d;deviceFrame.className='veDeviceFrame '+d;$$('[data-device]').forEach(b=>b.classList.toggle('active',b.dataset.device===d));setTimeout(()=>{applyDraftToFrame();renderInspector()},200)}
$$('[data-device]').forEach(b=>b.onclick=()=>setDevice(b.dataset.device));
$$('[data-jump]').forEach(b=>b.onclick=()=>{const d=doc(),k=b.dataset.jump,el=k==='hero'?d.querySelector('header.hero'):d.querySelector(`[data-home-section="${k}"]`);el?.scrollIntoView({behavior:'smooth',block:'start'});if(el)selectElement(el)});
$('#previewBtn').onclick=()=>{previewMode=!previewMode;doc().body.classList.toggle('ve-editing',!previewMode);doc().body.classList.toggle('ve-preview',previewMode);$('#previewBtn').textContent=previewMode?'Wróć do edycji':'Podgląd'};
$('#undoBtn').onclick=()=>{if(!undoStack.length)return;redoStack.push(clone(draft));draft=undoStack.pop();ensureMedia();ensureStyles();applyDraftToFrame();renderInspector();scheduleDraft()};
$('#redoBtn').onclick=()=>{if(!redoStack.length)return;undoStack.push(clone(draft));draft=redoStack.pop();ensureMedia();ensureStyles();applyDraftToFrame();renderInspector();scheduleDraft()};
$('#publishBtn').onclick=async()=>{const btn=$('#publishBtn');btn.disabled=true;btn.textContent='PUBLIKOWANIE…';try{await set(ref(db,`${WEBSITE_ROOT}/public/site`),draft.site||{});await set(ref(db,`${WEBSITE_ROOT}/public/homeContent`),draft.homeContent||{});await set(ref(db,`${WEBSITE_ROOT}/public/homeMedia`),draft.homeMedia||{});await set(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),draft.visualStyles||{});published=clone(draft);status('Opublikowano ✓');btn.textContent='OPUBLIKOWANO ✓';setTimeout(()=>btn.textContent='OPUBLIKUJ',1600)}catch(e){alert('Nie udało się opublikować: '+e.message);btn.textContent='OPUBLIKUJ'}finally{btn.disabled=false}};
async function init(){status('Ładowanie…');const pubSnap=await get(ref(db,`${WEBSITE_ROOT}/public`));published=normPublic(pubSnap.val()||{});const draftSnap=await get(ref(db,`${WEBSITE_ROOT}/public/editorDraft`));draft=draftSnap.exists()?draftSnap.val():clone(published);draft.site={...(published.site||{}),...(draft.site||{})};draft.homeContent={...(published.homeContent||{}),...(draft.homeContent||{})};draft.homeMedia={...(published.homeMedia||{}),...(draft.homeMedia||{})};draft.visualStyles={texts:{...(published.visualStyles?.texts||{}),...(draft.visualStyles?.texts||{})},sections:{...(published.visualStyles?.sections||{}),...(draft.visualStyles?.sections||{})}};ensureMedia();ensureStyles();const ready=()=>{installFrameEditing();status('Gotowe ✓')};frame.addEventListener('load',ready,{once:true});if(frame.contentDocument?.readyState==='complete')ready()}
init().catch(e=>{status('Błąd edytora');console.error(e);inspector.innerHTML='<div class="veEmpty"><b>Błąd edytora</b><p>Odśwież stronę. Jeśli problem wróci, sprawdzimy log.</p></div>'});