import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { getStorage, ref as sRef, listAll, getDownloadURL, uploadBytesResumable } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";

const app=initializeApp(firebaseConfig),db=getDatabase(app),storage=getStorage(app);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const frame=$('#siteFrame'),inspector=$('#inspector'),deviceFrame=$('#deviceFrame'),draftState=$('#draftState');
const mediaModal=$('#mediaModal'),mediaGrid=$('#mediaGrid'),mediaCount=$('#mediaCount');
let device='desktop',selected=null,draft=null,library=[],previewMode=false,cropMode=false;
let undoStack=[],redoStack=[],saveTimer=null,overlay=null;
const clone=x=>JSON.parse(JSON.stringify(x));
const baseDev=()=>({x:50,y:50,zoom:1});
const baseTransform=()=>({moveX:0,moveY:0,scale:1,rotate:0,width:null});
const mediaDefaults={heroMedia:{url:''},photoPortal:{url:'assets/portal-photo.png'},filmPortal:{url:'assets/portal-film.png'},aboutPortrait:{url:'assets/about-portrait.jpg'}};
function status(t){draftState.textContent=t}
function normPublic(raw={}){return{site:raw.site||{},homeContent:raw.homeContent||{},homeMedia:raw.homeMedia||{},visualStyles:raw.visualStyles||{texts:{},sections:{}},updatedAt:Date.now()}}
function ensureMedia(){draft.homeMedia||={};for(const[k,v]of Object.entries(mediaDefaults)){draft.homeMedia[k]||={url:v.url,desktop:baseDev(),tablet:baseDev(),mobile:baseDev()};for(const d of['desktop','tablet','mobile'])draft.homeMedia[k][d]={...baseDev(),...(draft.homeMedia[k][d]||{})}}}
function ensureStyles(){draft.visualStyles||={};draft.visualStyles.texts||={};draft.visualStyles.sections||={}}
function pushHistory(){undoStack.push(clone(draft));if(undoStack.length>50)undoStack.shift();redoStack=[]}
function scheduleDraft(){status('Zapisywanie roboczo…');clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,450)}
async function saveDraft(){try{draft.updatedAt=Date.now();await set(ref(db,`${WEBSITE_ROOT}/public/editorDraft`),draft);status('Wersja robocza ✓')}catch(e){status('Błąd zapisu roboczego');console.error(e)}}
function doc(){return frame.contentDocument} function win(){return frame.contentWindow}
function textKey(el){if(['heroK','heroT','heroD'].includes(el.id))return el.id;return el.dataset.homeText||''}
function mediaKey(el){return el.dataset.homeMedia||''}
function sectionKey(el){return el.matches('header.hero')?'Hero':el.dataset.homeSection||''}
function textValue(k){if(['heroK','heroT','heroD'].includes(k))return draft.site?.[k]??'';return draft.homeContent?.[k]??''}
function setTextValue(k,v){if(['heroK','heroT','heroD'].includes(k)){draft.site||={};draft.site[k]=v}else{draft.homeContent||={};draft.homeContent[k]=v}}
function styleCfg(k){ensureStyles();draft.visualStyles.texts[k]||={};draft.visualStyles.texts[k][device]||={};draft.visualStyles.texts[k][device]={...baseTransform(),...draft.visualStyles.texts[k][device]};return draft.visualStyles.texts[k][device]}
function sectionCfg(k){ensureStyles();draft.visualStyles.sections[k]||={};draft.visualStyles.sections[k][device]||={};return draft.visualStyles.sections[k][device]}
function toHex(c){if(/^#[0-9a-f]{6}$/i.test(c))return c;const m=String(c).match(/\d+/g);if(!m)return'#ffffff';return'#'+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,'0')).join('')}

function installFrameEditing(){const d=doc();if(!d)return;let s=d.querySelector('#rafVisualEditorStyle');if(!s){s=d.createElement('style');s.id='rafVisualEditorStyle';d.head.appendChild(s)}s.textContent=`
body.ve-editing [data-home-text],body.ve-editing #heroK,body.ve-editing #heroT,body.ve-editing #heroD,body.ve-editing [data-home-media]{outline:1px dashed transparent;outline-offset:4px;cursor:pointer}
body.ve-editing [data-home-text]:hover,body.ve-editing #heroK:hover,body.ve-editing #heroT:hover,body.ve-editing #heroD:hover,body.ve-editing [data-home-media]:hover{outline-color:#35a7ff}
body.ve-editing .ve-selected{outline:2px solid #35a7ff!important;outline-offset:4px}
body.ve-editing [contenteditable=true]{outline:2px solid white!important;cursor:text!important}
.ve-transform-box{position:absolute;z-index:99998;border:2px solid #35a7ff;pointer-events:none;box-sizing:border-box}
.ve-handle{position:absolute;width:16px;height:16px;border-radius:50%;background:#fff;border:2px solid #168ee6;pointer-events:auto;box-shadow:0 2px 8px #0008}
.ve-handle.scale{right:-9px;bottom:-9px;cursor:nwse-resize}.ve-handle.rotate{left:50%;top:-38px;transform:translateX(-50%);cursor:grab}.ve-handle.rotate:after{content:'';position:absolute;left:6px;top:14px;height:22px;border-left:2px solid #35a7ff}
.ve-move-handle{position:absolute;left:6px;top:-32px;height:24px;padding:0 8px;border-radius:7px;background:#168ee6;color:#fff;font:700 12px system-ui;display:flex;align-items:center;pointer-events:auto;cursor:move;white-space:nowrap}
.ve-size-label{position:absolute;right:5px;top:-28px;background:#111;color:#fff;border:1px solid #ffffff33;border-radius:6px;padding:3px 6px;font:11px system-ui;pointer-events:none}
body.ve-preview .ve-transform-box,body.ve-preview .ve-selected{display:none!important;outline:0!important}`;d.body.classList.add('ve-editing');
 // Edytor nie pozwala przypadkiem opuścić strony głównej.
 d.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&!previewMode){e.preventDefault();e.stopPropagation()}},true);
 bindSelectable();applyDraftToFrame();setTimeout(()=>{applyDraftToFrame();updateOverlay()},300);d.addEventListener('scroll',updateOverlay,{passive:true});win().addEventListener('resize',updateOverlay)}
function bindSelectable(){const d=doc();for(const el of d.querySelectorAll('[data-home-text],[data-home-media],[data-home-section],#heroK,#heroT,#heroD,header.hero')){if(el.dataset.veBound==='1')continue;el.dataset.veBound='1';el.addEventListener('click',e=>{if(previewMode)return;e.preventDefault();e.stopPropagation();const t=e.target.closest('[data-home-text],[data-home-media],#heroK,#heroT,#heroD')||e.target.closest('[data-home-section],header.hero')||el;selectElement(t)});if(el.matches('[data-home-text],#heroK,#heroT,#heroD')){el.addEventListener('dblclick',e=>{if(previewMode)return;e.preventDefault();e.stopPropagation();selectElement(el);startInlineEdit(el)});el.addEventListener('input',()=>{if(!el.isContentEditable)return;setTextValue(textKey(el),el.innerText);scheduleDraft();updateOverlay()})}}}
function selectElement(el){const d=doc();d.querySelectorAll('.ve-selected').forEach(x=>x.classList.remove('ve-selected'));el.classList.add('ve-selected');selected=el;cropMode=false;renderInspector();renderOverlay()}
function startInlineEdit(el){removeOverlay();el.contentEditable='true';el.focus();const end=()=>{el.contentEditable='false';el.removeEventListener('blur',end);setTextValue(textKey(el),el.innerText);scheduleDraft();renderInspector();renderOverlay()};el.addEventListener('blur',end)}
function removeOverlay(){overlay?.remove();overlay=null}
function renderOverlay(){removeOverlay();if(!selected||previewMode||!selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return;const d=doc();overlay=d.createElement('div');overlay.className='ve-transform-box';overlay.innerHTML='<div class="ve-move-handle">✥ PRZESUŃ</div><div class="ve-size-label"></div><div class="ve-handle rotate" title="Obróć"></div><div class="ve-handle scale" title="Skaluj"></div>';d.body.appendChild(overlay);bindTransformHandles();updateOverlay()}
function updateOverlay(){if(!overlay||!selected||!selected.isConnected)return;const r=selected.getBoundingClientRect(),w=win();overlay.style.left=(r.left+w.scrollX)+'px';overlay.style.top=(r.top+w.scrollY)+'px';overlay.style.width=r.width+'px';overlay.style.height=r.height+'px';$('.ve-size-label',overlay).textContent=Math.round(r.width)+' × '+Math.round(r.height)}
function bindTransformHandles(){const cfg=styleCfg(textKey(selected)),w=win();let mode='',start=null,startCfg=null,center=null,startAngle=0,startDist=0;
 const begin=(m,e)=>{e.preventDefault();e.stopPropagation();pushHistory();mode=m;start={x:e.clientX,y:e.clientY};startCfg={...cfg};const r=selected.getBoundingClientRect();center={x:r.left+r.width/2,y:r.top+r.height/2};startAngle=Math.atan2(e.clientY-center.y,e.clientX-center.x);startDist=Math.hypot(e.clientX-center.x,e.clientY-center.y);w.addEventListener('pointermove',move,true);w.addEventListener('pointerup',end,true)};
 const move=e=>{if(!mode)return;if(mode==='move'){cfg.moveX=startCfg.moveX+(e.clientX-start.x);cfg.moveY=startCfg.moveY+(e.clientY-start.y)}else if(mode==='scale'){const dist=Math.hypot(e.clientX-center.x,e.clientY-center.y);cfg.scale=Math.max(.2,Math.min(4,startCfg.scale*(dist/Math.max(10,startDist))))}else if(mode==='rotate'){const a=Math.atan2(e.clientY-center.y,e.clientX-center.x);cfg.rotate=startCfg.rotate+(a-startAngle)*180/Math.PI}applyTextStyles(selected,textKey(selected));updateOverlay();renderTransformNumbers()};
 const end=()=>{mode='';w.removeEventListener('pointermove',move,true);w.removeEventListener('pointerup',end,true);scheduleDraft();renderInspector();updateOverlay()};
 $('.ve-move-handle',overlay).onpointerdown=e=>begin('move',e);$('.ve-handle.scale',overlay).onpointerdown=e=>begin('scale',e);$('.ve-handle.rotate',overlay).onpointerdown=e=>begin('rotate',e)}
function renderTransformNumbers(){if(!selected)return;const cfg=styleCfg(textKey(selected));const map={iMoveX:Math.round(cfg.moveX),iMoveY:Math.round(cfg.moveY),iScale:Number(cfg.scale).toFixed(2),iRotate:Math.round(cfg.rotate)};for(const[k,v]of Object.entries(map)){const el=$('#'+k);if(el)el.value=v}}

function applyTextStyles(el,k){const c=draft.visualStyles?.texts?.[k]?.[device]||{};el.style.fontSize=c.fontSize!=null?c.fontSize+'px':'';el.style.letterSpacing=c.letterSpacing!=null?c.letterSpacing+'px':'';el.style.lineHeight=c.lineHeight!=null?c.lineHeight:'';el.style.fontFamily=c.fontFamily||'';el.style.fontWeight=c.fontWeight||'';el.style.color=c.color||'';el.style.textAlign=c.textAlign||'';el.style.maxWidth=c.maxWidth?c.maxWidth+'px':'';el.style.width=c.width?c.width+'px':'';el.style.transformOrigin='center center';el.style.transform=`translate(${c.moveX||0}px,${c.moveY||0}px) rotate(${c.rotate||0}deg) scale(${c.scale||1})`;el.style.position='relative';el.style.zIndex=(c.moveX||c.moveY||c.rotate||c.scale!==1)?'4':''}
function applySectionStyles(el,k){const c=draft.visualStyles?.sections?.[k]?.[device]||{};el.style.paddingTop=c.paddingTop!=null?c.paddingTop+'px':'';el.style.paddingBottom=c.paddingBottom!=null?c.paddingBottom+'px':'';el.style.background=c.background||'';el.style.display=c.hidden===true?'none':''}
function applyDraftToFrame(){const d=doc();if(!d||!draft)return;d.querySelectorAll('[data-home-text],#heroK,#heroT,#heroD').forEach(el=>{if(el.isContentEditable)return;const k=textKey(el),v=textValue(k);if(v!==undefined&&v!==''){if(el.dataset.multiline==='1'||k==='heroT')el.innerHTML=String(v).replace(/\n/g,'<br>');else el.textContent=v}applyTextStyles(el,k)});d.querySelectorAll('[data-home-media]').forEach(el=>{const k=mediaKey(el),m=draft.homeMedia?.[k];if(!m)return;const c={...baseDev(),...(m[device]||{})};if(m.url)el.src=m.url;el.style.objectFit='cover';el.style.objectPosition=`${c.x}% ${c.y}%`;el.style.transformOrigin=`${c.x}% ${c.y}%`;el.style.transform=`scale(${c.zoom})`;if(k==='heroMedia'&&m.url)el.style.opacity='1'});d.querySelectorAll('[data-home-section],header.hero').forEach(el=>applySectionStyles(el,sectionKey(el)));updateOverlay()}
function commonHeader(type,name){return`<div class="type">${type}</div><h3>${name}</h3>`}
function renderInspector(){if(!selected){inspector.innerHTML='<div class="veEmpty"><b>Wybierz element</b><p>Kliknij tekst, zdjęcie albo sekcję na podglądzie.</p></div>';return}if(selected.matches('[data-home-media]'))return renderImageInspector();if(selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return renderTextInspector();return renderSectionInspector()}
function renderTextInspector(){const k=textKey(selected),c=styleCfg(k),v=textValue(k)||selected.innerText,cs=win().getComputedStyle(selected);inspector.innerHTML=commonHeader('TEKST / POLE',k)+`<div class="veHint"><b>1 klik</b> = zaznacz • <b>2 klik</b> = pisz. Ramka: „PRZESUŃ”, biały róg = skaluj, kółko u góry = obrót.</div><label>Treść</label><textarea id="iText"></textarea><div class="veRow"><div><label>X — przesunięcie</label><input id="iMoveX" type="number" step="1"></div><div><label>Y — przesunięcie</label><input id="iMoveY" type="number" step="1"></div></div><div class="veRow"><div><label>Skala</label><input id="iScale" type="number" min="0.2" max="4" step="0.05"></div><div><label>Obrót °</label><input id="iRotate" type="number" min="-180" max="180" step="1"></div></div><label>Szerokość pola px (0 = automatyczna)</label><input id="iWidth" type="number" min="0" max="1800"><label>Czcionka</label><select id="iFont"><option value="Inter,system-ui,Arial,sans-serif">Inter / systemowa</option><option value="Arial,sans-serif">Arial</option><option value="Trebuchet MS,sans-serif">Trebuchet</option><option value="Verdana,sans-serif">Verdana</option><option value="Georgia,serif">Georgia</option></select><div class="veRow"><div><label>Rozmiar px</label><input id="iSize" type="number" min="8" max="220"></div><div><label>Grubość</label><select id="iWeight"><option>300</option><option>400</option><option>500</option><option>600</option><option>700</option><option>800</option><option>900</option></select></div></div><div class="veRow"><div><label>Kolor</label><input id="iColor" type="color"></div><div><label>Wyrównanie</label><select id="iAlign"><option value="left">Lewo</option><option value="center">Środek</option><option value="right">Prawo</option></select></div></div><div class="veRow"><div><label>Interlinia</label><input id="iLine" type="number" min="0.6" max="3" step="0.05"></div><div><label>Litery px</label><input id="iLetter" type="number" min="-10" max="30" step="0.5"></div></div><div class="veBtns"><button id="resetTransform">Reset pozycji</button><button id="resetText">Reset całego tekstu</button></div>`;
 $('#iText').value=v;$('#iMoveX').value=c.moveX||0;$('#iMoveY').value=c.moveY||0;$('#iScale').value=c.scale||1;$('#iRotate').value=c.rotate||0;$('#iWidth').value=c.width||0;$('#iFont').value=c.fontFamily||'Inter,system-ui,Arial,sans-serif';$('#iSize').value=c.fontSize||Math.round(parseFloat(cs.fontSize));$('#iWeight').value=c.fontWeight||cs.fontWeight;$('#iColor').value=toHex(c.color||cs.color);$('#iAlign').value=c.textAlign||cs.textAlign||'left';$('#iLine').value=c.lineHeight||1;$('#iLetter').value=c.letterSpacing||0;
 const read=()=>{setTextValue(k,$('#iText').value);Object.assign(c,{moveX:+$('#iMoveX').value||0,moveY:+$('#iMoveY').value||0,scale:+$('#iScale').value||1,rotate:+$('#iRotate').value||0,width:+$('#iWidth').value||null,fontFamily:$('#iFont').value,fontSize:+$('#iSize').value,fontWeight:$('#iWeight').value,color:$('#iColor').value,textAlign:$('#iAlign').value,lineHeight:+$('#iLine').value,letterSpacing:+$('#iLetter').value});applyDraftToFrame();scheduleDraft()};
 $('#iText').oninput=()=>{setTextValue(k,$('#iText').value);if(!selected.isContentEditable){selected.textContent=$('#iText').value}scheduleDraft();updateOverlay()};['iMoveX','iMoveY','iScale','iRotate','iWidth','iFont','iSize','iWeight','iColor','iAlign','iLine','iLetter'].forEach(id=>$('#'+id).oninput=read);$('#resetTransform').onclick=()=>{pushHistory();Object.assign(c,baseTransform());applyDraftToFrame();renderInspector();scheduleDraft()};$('#resetText').onclick=()=>{pushHistory();delete draft.visualStyles.texts[k][device];applyDraftToFrame();renderInspector();renderOverlay();scheduleDraft()}}
function renderImageInspector(){const k=mediaKey(selected),m=draft.homeMedia[k],c=m[device];inspector.innerHTML=commonHeader('ZDJĘCIE',k)+`<div class="veHint">Zmień zdjęcie albo kadruj suwakiem. „Kadruj na stronie” pozwala przeciągać obraz.</div><div class="veBtns"><button id="chooseImg" class="primary">Zmień zdjęcie</button><button id="cropBtn">✥ Kadruj na stronie</button></div><label>Kadr poziomo <span id="xVal"></span></label><input id="iX" type="range" min="0" max="100"><label>Kadr pionowo <span id="yVal"></span></label><input id="iY" type="range" min="0" max="100"><label>Zoom <span id="zVal"></span></label><input id="iZoom" type="range" min="1" max="3" step="0.02"><div class="veBtns"><button id="resetImg">Reset kadru</button></div>`;$('#iX').value=c.x;$('#iY').value=c.y;$('#iZoom').value=c.zoom;const go=()=>{c.x=+$('#iX').value;c.y=+$('#iY').value;c.zoom=+$('#iZoom').value;$('#xVal').textContent=c.x+'%';$('#yVal').textContent=c.y+'%';$('#zVal').textContent=c.zoom.toFixed(2)+'×';applyDraftToFrame();scheduleDraft()};go();['iX','iY','iZoom'].forEach(id=>$('#'+id).oninput=go);$('#chooseImg').onclick=openMedia;$('#resetImg').onclick=()=>{$('#iX').value=50;$('#iY').value=50;$('#iZoom').value=1;go()};$('#cropBtn').onclick=toggleCrop}
function renderSectionInspector(){const k=sectionKey(selected),c=sectionCfg(k),cs=win().getComputedStyle(selected);inspector.innerHTML=commonHeader('SEKCJA',k)+`<label>Odstęp góra px</label><input id="sTop" type="number" min="0" max="400"><label>Odstęp dół px</label><input id="sBottom" type="number" min="0" max="400"><label>Kolor tła</label><input id="sBg" type="color"><label><input id="sHide" type="checkbox" style="width:auto"> Ukryj na tym urządzeniu</label>`;$('#sTop').value=c.paddingTop??(parseInt(cs.paddingTop)||0);$('#sBottom').value=c.paddingBottom??(parseInt(cs.paddingBottom)||0);$('#sBg').value=toHex(c.background||cs.backgroundColor);$('#sHide').checked=c.hidden===true;const go=()=>{Object.assign(c,{paddingTop:+$('#sTop').value,paddingBottom:+$('#sBottom').value,background:$('#sBg').value,hidden:$('#sHide').checked});applyDraftToFrame();scheduleDraft()};['sTop','sBottom','sBg','sHide'].forEach(id=>$('#'+id).onchange=go)}
function toggleCrop(){cropMode=!cropMode;$('#cropBtn').textContent=cropMode?'✓ Zakończ kadrowanie':'✥ Kadruj na stronie';if(!cropMode){selected.onpointerdown=selected.onpointermove=selected.onpointerup=null;return}const el=selected,c=draft.homeMedia[mediaKey(el)][device];let st=null,b=null;el.onpointerdown=e=>{e.preventDefault();st={x:e.clientX,y:e.clientY};b={x:c.x,y:c.y};el.setPointerCapture?.(e.pointerId)};el.onpointermove=e=>{if(!st)return;const r=el.getBoundingClientRect();c.x=Math.max(0,Math.min(100,b.x-(e.clientX-st.x)/r.width*100));c.y=Math.max(0,Math.min(100,b.y-(e.clientY-st.y)/r.height*100));applyDraftToFrame()};el.onpointerup=()=>{st=null;scheduleDraft();renderInspector()}}
async function loadMedia(){mediaGrid.innerHTML='<p>Ładowanie…</p>';const res=await listAll(sRef(storage,'website/media'));library=[];for(const it of res.items){if(!/\.(jpe?g|png|webp|gif|avif)$/i.test(it.name))continue;try{library.push({name:it.name,url:await getDownloadURL(it)})}catch{}}mediaCount.textContent=library.length+' zdjęć';mediaGrid.innerHTML=library.map((x,i)=>`<div class="veMediaItem" data-i="${i}"><img loading="lazy" src="${x.url}"><div>${x.name}</div></div>`).join('');$$('.veMediaItem',mediaGrid).forEach(el=>el.onclick=()=>{draft.homeMedia[mediaKey(selected)].url=library[+el.dataset.i].url;applyDraftToFrame();mediaModal.hidden=true;scheduleDraft()})}
function openMedia(){mediaModal.hidden=false;if(!library.length)loadMedia().catch(console.error)}$('#mediaClose').onclick=()=>mediaModal.hidden=true;$('#mediaUpload').onchange=()=>[...$('#mediaUpload').files].forEach(file=>{const task=uploadBytesResumable(sRef(storage,`website/media/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`),file);task.on('state_changed',null,console.error,loadMedia)});
function setDevice(d){device=d;deviceFrame.className='veDeviceFrame '+d;$$('[data-device]').forEach(b=>b.classList.toggle('active',b.dataset.device===d));setTimeout(()=>{applyDraftToFrame();renderInspector();renderOverlay()},180)}$$('[data-device]').forEach(b=>b.onclick=()=>setDevice(b.dataset.device));
function jumpHome(key){const d=doc();if(!d)return;const el=key==='hero'?d.querySelector('header.hero'):d.querySelector(`[data-home-section="${key}"]`);if(el){el.scrollIntoView({behavior:'smooth',block:'start'});selectElement(el);return}frame.src='index.html?editor=3';frame.addEventListener('load',()=>{installFrameEditing();setTimeout(()=>jumpHome(key),100)},{once:true})}
$$('[data-jump]').forEach(b=>b.onclick=e=>{e.preventDefault();jumpHome(b.dataset.jump)});
$('#previewBtn').onclick=()=>{previewMode=!previewMode;doc().body.classList.toggle('ve-editing',!previewMode);doc().body.classList.toggle('ve-preview',previewMode);$('#previewBtn').textContent=previewMode?'Wróć do edycji':'Podgląd';if(previewMode)removeOverlay();else renderOverlay()};
$('#undoBtn').onclick=()=>{if(!undoStack.length)return;redoStack.push(clone(draft));draft=undoStack.pop();ensureMedia();ensureStyles();applyDraftToFrame();renderInspector();renderOverlay();scheduleDraft()};$('#redoBtn').onclick=()=>{if(!redoStack.length)return;undoStack.push(clone(draft));draft=redoStack.pop();ensureMedia();ensureStyles();applyDraftToFrame();renderInspector();renderOverlay();scheduleDraft()};
$('#publishBtn').onclick=async()=>{const b=$('#publishBtn');b.disabled=true;b.textContent='PUBLIKOWANIE…';try{await Promise.all([set(ref(db,`${WEBSITE_ROOT}/public/site`),draft.site||{}),set(ref(db,`${WEBSITE_ROOT}/public/homeContent`),draft.homeContent||{}),set(ref(db,`${WEBSITE_ROOT}/public/homeMedia`),draft.homeMedia||{}),set(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),draft.visualStyles||{})]);status('Opublikowano ✓');b.textContent='OPUBLIKOWANO ✓';setTimeout(()=>b.textContent='OPUBLIKUJ',1500)}catch(e){alert('Błąd publikacji: '+e.message);b.textContent='OPUBLIKUJ'}finally{b.disabled=false}};
async function init(){status('Ładowanie…');const p=await get(ref(db,`${WEBSITE_ROOT}/public`)),pub=normPublic(p.val()||{}),ds=await get(ref(db,`${WEBSITE_ROOT}/public/editorDraft`));draft=ds.exists()?ds.val():clone(pub);draft.site={...pub.site,...(draft.site||{})};draft.homeContent={...pub.homeContent,...(draft.homeContent||{})};draft.homeMedia={...pub.homeMedia,...(draft.homeMedia||{})};draft.visualStyles={texts:{...(pub.visualStyles?.texts||{}),...(draft.visualStyles?.texts||{})},sections:{...(pub.visualStyles?.sections||{}),...(draft.visualStyles?.sections||{})}};ensureMedia();ensureStyles();const ready=()=>{installFrameEditing();status('Gotowe ✓')};frame.addEventListener('load',ready,{once:true});if(frame.contentDocument?.readyState==='complete')ready()}
init().catch(e=>{status('Błąd');console.error(e)});