import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { getStorage, ref as sRef, listAll, getDownloadURL, uploadBytesResumable } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";

const app=initializeApp(firebaseConfig),db=getDatabase(app),storage=getStorage(app);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const frame=$('#siteFrame'),inspector=$('#inspector'),deviceFrame=$('#deviceFrame'),draftState=$('#draftState');
const mediaModal=$('#mediaModal'),mediaGrid=$('#mediaGrid'),mediaCount=$('#mediaCount');
let device='desktop',selected=null,draft=null,library=[],previewMode=false,overlay=null,saveTimer=null;
let undoStack=[],redoStack=[];
const clone=x=>JSON.parse(JSON.stringify(x));
const baseDev=()=>({x:50,y:50,zoom:1});
const baseTransform=()=>({moveX:0,moveY:0,scale:1,rotate:0,width:null});
const mediaDefaults={heroMedia:{url:''},photoPortal:{url:'assets/portal-photo.png'},filmPortal:{url:'assets/portal-film.png'},aboutPortrait:{url:'assets/about-portrait.jpg'}};
const status=t=>draftState.textContent=t;
const doc=()=>frame.contentDocument, win=()=>frame.contentWindow;
function textKey(el){return ['heroK','heroT','heroD'].includes(el.id)?el.id:(el.dataset.homeText||'')}
function mediaKey(el){return el.dataset.homeMedia||''}
function sectionKey(el){return el.matches('header.hero')?'Hero':(el.dataset.homeSection||'')}
function norm(raw={}){return{site:raw.site||{},homeContent:raw.homeContent||{},homeMedia:raw.homeMedia||{},visualStyles:raw.visualStyles||{texts:{},sections:{}}}}
function ensure(){draft.homeMedia||={};draft.visualStyles||={};draft.visualStyles.texts||={};draft.visualStyles.sections||={};for(const[k,v]of Object.entries(mediaDefaults)){draft.homeMedia[k]||={url:v.url,desktop:baseDev(),tablet:baseDev(),mobile:baseDev()};for(const d of['desktop','tablet','mobile'])draft.homeMedia[k][d]={...baseDev(),...(draft.homeMedia[k][d]||{})}}}
function styleCfg(k){draft.visualStyles.texts[k]||={};draft.visualStyles.texts[k][device]={...baseTransform(),...(draft.visualStyles.texts[k][device]||{})};return draft.visualStyles.texts[k][device]}
function sectionCfg(k){draft.visualStyles.sections[k]||={};draft.visualStyles.sections[k][device]||={};return draft.visualStyles.sections[k][device]}
function textValue(k){return ['heroK','heroT','heroD'].includes(k)?(draft.site?.[k]??''):(draft.homeContent?.[k]??'')}
function setTextValue(k,v){if(['heroK','heroT','heroD'].includes(k)){draft.site||={};draft.site[k]=v}else{draft.homeContent||={};draft.homeContent[k]=v}}
function pushHistory(){undoStack.push(clone(draft));if(undoStack.length>40)undoStack.shift();redoStack=[]}
function scheduleSave(){status('Zapisywanie roboczo…');clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,350)}
async function saveDraft(){try{await set(ref(db,`${WEBSITE_ROOT}/public/editorDraft`),draft);status('Wersja robocza ✓')}catch(e){status('Błąd zapisu');console.error(e)}}
function toHex(c){if(/^#[0-9a-f]{6}$/i.test(c))return c;const m=String(c).match(/\d+/g);return m?'#'+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,'0')).join(''):'#ffffff'}

function applyTextStyle(el,k){const c=draft.visualStyles?.texts?.[k]?.[device]||{};el.style.fontSize=c.fontSize!=null?c.fontSize+'px':'';el.style.letterSpacing=c.letterSpacing!=null?c.letterSpacing+'px':'';el.style.lineHeight=c.lineHeight!=null?c.lineHeight:'';el.style.fontFamily=c.fontFamily||'';el.style.fontWeight=c.fontWeight||'';el.style.color=c.color||'';el.style.textAlign=c.textAlign||'';el.style.width=c.width?c.width+'px':'';el.style.maxWidth=c.width?c.width+'px':'';el.style.transformOrigin='center center';el.style.transform=`translate(${Number(c.moveX)||0}px,${Number(c.moveY)||0}px) rotate(${Number(c.rotate)||0}deg) scale(${Number(c.scale)||1})`;el.style.position='relative';el.style.zIndex='4'}
function applyAll(){const d=doc();if(!d||!draft)return;d.querySelectorAll('[data-home-text],#heroK,#heroT,#heroD').forEach(el=>{if(el.isContentEditable)return;const k=textKey(el),v=textValue(k);if(v!==''&&v!=null){if(el.dataset.multiline==='1'||k==='heroT')el.innerHTML=String(v).replace(/\n/g,'<br>');else el.textContent=v}applyTextStyle(el,k)});d.querySelectorAll('[data-home-media]').forEach(el=>{const k=mediaKey(el),m=draft.homeMedia[k];if(!m)return;const c={...baseDev(),...(m[device]||{})};if(m.url)el.src=m.url;el.style.objectFit='cover';el.style.objectPosition=`${c.x}% ${c.y}%`;el.style.transformOrigin=`${c.x}% ${c.y}%`;el.style.transform=`scale(${c.zoom})`;if(k==='heroMedia'&&m.url)el.style.opacity='1'});d.querySelectorAll('[data-home-section],header.hero').forEach(el=>{const c=draft.visualStyles.sections?.[sectionKey(el)]?.[device]||{};el.style.paddingTop=c.paddingTop!=null?c.paddingTop+'px':'';el.style.paddingBottom=c.paddingBottom!=null?c.paddingBottom+'px':'';el.style.background=c.background||'';el.style.display=c.hidden===true?'none':''});updateOverlay()}

function install(){const d=doc();if(!d)return;let s=d.querySelector('#rafEditorV5Style');if(!s){s=d.createElement('style');s.id='rafEditorV5Style';d.head.appendChild(s)}s.textContent=`body.ve5 [data-home-text],body.ve5 #heroK,body.ve5 #heroT,body.ve5 #heroD,body.ve5 [data-home-media]{cursor:pointer}body.ve5 .ve5-selected{outline:2px solid #25a8ff!important;outline-offset:4px}.ve5-box{position:absolute;z-index:999999;border:2px solid #25a8ff;box-sizing:border-box;pointer-events:none}.ve5-move,.ve5-scale,.ve5-rotate{pointer-events:auto;touch-action:none;user-select:none}.ve5-move{position:absolute;left:4px;top:-31px;background:#168ee6;color:white;border-radius:7px;padding:5px 9px;font:700 12px system-ui;cursor:move}.ve5-scale,.ve5-rotate{position:absolute;width:16px;height:16px;border-radius:50%;background:#fff;border:2px solid #168ee6;box-sizing:border-box}.ve5-scale{right:-9px;bottom:-9px;cursor:nwse-resize}.ve5-rotate{left:50%;top:-39px;transform:translateX(-50%);cursor:grab}.ve5-rotate:after{content:'';position:absolute;left:6px;top:14px;height:22px;border-left:2px solid #25a8ff}.ve5-size{position:absolute;right:4px;top:-28px;background:#111;color:#fff;border:1px solid #ffffff30;border-radius:5px;padding:3px 6px;font:11px system-ui}`;d.body.classList.add('ve5');d.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&!previewMode){e.preventDefault();e.stopPropagation()}},true);for(const el of d.querySelectorAll('[data-home-text],[data-home-media],[data-home-section],#heroK,#heroT,#heroD,header.hero')){el.addEventListener('click',e=>{if(previewMode)return;e.preventDefault();e.stopPropagation();const t=e.target.closest('[data-home-text],[data-home-media],#heroK,#heroT,#heroD')||e.target.closest('[data-home-section],header.hero')||el;select(t)});if(el.matches('[data-home-text],#heroK,#heroT,#heroD'))el.addEventListener('dblclick',e=>{e.preventDefault();e.stopPropagation();startTextEdit(el)})}d.addEventListener('scroll',updateOverlay,{passive:true});win().addEventListener('resize',updateOverlay);applyAll()}
function select(el){doc().querySelectorAll('.ve5-selected').forEach(x=>x.classList.remove('ve5-selected'));el.classList.add('ve5-selected');selected=el;renderInspector();renderOverlay()}
function startTextEdit(el){removeOverlay();el.contentEditable='true';el.focus();const done=()=>{el.contentEditable='false';el.removeEventListener('blur',done);setTextValue(textKey(el),el.innerText);scheduleSave();renderInspector();renderOverlay()};el.addEventListener('input',()=>{setTextValue(textKey(el),el.innerText);scheduleSave()});el.addEventListener('blur',done)}
function removeOverlay(){overlay?.remove();overlay=null}
function renderOverlay(){removeOverlay();if(!selected||previewMode||!selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return;const d=doc();overlay=d.createElement('div');overlay.className='ve5-box';overlay.innerHTML='<div class="ve5-move">✥ PRZESUŃ</div><div class="ve5-size"></div><div class="ve5-rotate"></div><div class="ve5-scale"></div>';d.body.appendChild(overlay);bindTransform();updateOverlay()}
function updateOverlay(){if(!overlay||!selected?.isConnected)return;const r=selected.getBoundingClientRect(),w=win();overlay.style.left=(r.left+w.scrollX)+'px';overlay.style.top=(r.top+w.scrollY)+'px';overlay.style.width=r.width+'px';overlay.style.height=r.height+'px';$('.ve5-size',overlay).textContent=`${Math.round(r.width)} × ${Math.round(r.height)}`}
function bindTransform(){const d=doc();const c=styleCfg(textKey(selected));let act=null;const begin=(mode,e)=>{e.preventDefault();e.stopPropagation();pushHistory();const r=selected.getBoundingClientRect();act={mode,pid:e.pointerId,sx:e.clientX,sy:e.clientY,start:{...c},cx:r.left+r.width/2,cy:r.top+r.height/2};act.dist=Math.max(10,Math.hypot(e.clientX-act.cx,e.clientY-act.cy));act.angle=Math.atan2(e.clientY-act.cy,e.clientX-act.cx);try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}};const move=e=>{if(!act||e.pointerId!==act.pid)return;e.preventDefault();if(act.mode==='move'){c.moveX=act.start.moveX+(e.clientX-act.sx);c.moveY=act.start.moveY+(e.clientY-act.sy)}else if(act.mode==='scale'){const dist=Math.max(10,Math.hypot(e.clientX-act.cx,e.clientY-act.cy));c.scale=Math.max(.2,Math.min(4,act.start.scale*(dist/act.dist)))}else{const a=Math.atan2(e.clientY-act.cy,e.clientX-act.cx);c.rotate=act.start.rotate+(a-act.angle)*180/Math.PI;if(e.shiftKey)c.rotate=Math.round(c.rotate/15)*15}applyTextStyle(selected,textKey(selected));syncInspectorTransform();updateOverlay()};const end=e=>{if(!act||e.pointerId!==act.pid)return;act=null;scheduleSave();renderInspector();updateOverlay()};overlay.querySelector('.ve5-move').addEventListener('pointerdown',e=>begin('move',e));overlay.querySelector('.ve5-scale').addEventListener('pointerdown',e=>begin('scale',e));overlay.querySelector('.ve5-rotate').addEventListener('pointerdown',e=>begin('rotate',e));d.addEventListener('pointermove',move,{capture:true});d.addEventListener('pointerup',end,{capture:true,once:false})}
function syncInspectorTransform(){if(!selected)return;const c=styleCfg(textKey(selected));if($('#iMoveX'))$('#iMoveX').value=Math.round(c.moveX);if($('#iMoveY'))$('#iMoveY').value=Math.round(c.moveY);if($('#iScale'))$('#iScale').value=Number(c.scale).toFixed(2);if($('#iRotate'))$('#iRotate').value=Math.round(c.rotate)}

function renderInspector(){if(!selected){inspector.innerHTML='<b>Wybierz element</b>';return}if(selected.matches('[data-home-media]'))return renderImage();if(selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return renderText();return renderSection()}
function renderText(){const k=textKey(selected),c=styleCfg(k),cs=win().getComputedStyle(selected);inspector.innerHTML=`<div class="type">TEKST / POLE</div><h3>${k}</h3><div class="veHint">1 klik = zaznacz • 2 klik = pisz • PRZESUŃ = przeciągnij</div><label>Treść</label><textarea id="iText"></textarea><div class="veRow"><div><label>X</label><input id="iMoveX" type="number"></div><div><label>Y</label><input id="iMoveY" type="number"></div></div><div class="veRow"><div><label>Skala</label><input id="iScale" type="number" step=".05" min=".2" max="4"></div><div><label>Obrót °</label><input id="iRotate" type="number"></div></div><label>Szerokość pola px</label><input id="iWidth" type="number" min="0"><label>Rozmiar tekstu px</label><input id="iSize" type="number" min="8" max="220"><label>Kolor</label><input id="iColor" type="color"><label>Wyrównanie</label><select id="iAlign"><option value="left">Lewo</option><option value="center">Środek</option><option value="right">Prawo</option></select><div class="veBtns"><button id="resetTransform">Reset pozycji</button></div>`;$('#iText').value=textValue(k)||selected.innerText;$('#iMoveX').value=Math.round(c.moveX);$('#iMoveY').value=Math.round(c.moveY);$('#iScale').value=c.scale;$('#iRotate').value=Math.round(c.rotate);$('#iWidth').value=c.width||0;$('#iSize').value=c.fontSize||Math.round(parseFloat(cs.fontSize));$('#iColor').value=toHex(c.color||cs.color);$('#iAlign').value=c.textAlign||cs.textAlign||'left';const apply=()=>{setTextValue(k,$('#iText').value);Object.assign(c,{moveX:+$('#iMoveX').value||0,moveY:+$('#iMoveY').value||0,scale:+$('#iScale').value||1,rotate:+$('#iRotate').value||0,width:+$('#iWidth').value||null,fontSize:+$('#iSize').value||null,color:$('#iColor').value,textAlign:$('#iAlign').value});if(!selected.isContentEditable)selected.textContent=$('#iText').value;applyTextStyle(selected,k);updateOverlay();scheduleSave()};for(const id of['iText','iMoveX','iMoveY','iScale','iRotate','iWidth','iSize','iColor','iAlign'])$('#'+id).addEventListener('input',apply);$('#resetTransform').onclick=()=>{Object.assign(c,baseTransform());applyTextStyle(selected,k);renderInspector();updateOverlay();scheduleSave()}}
function renderImage(){const k=mediaKey(selected),m=draft.homeMedia[k],c=m[device];inspector.innerHTML=`<div class="type">ZDJĘCIE</div><h3>${k}</h3><button id="chooseImg" class="primary">Zmień zdjęcie</button><label>Kadr X</label><input id="iX" type="range" min="0" max="100" value="${c.x}"><label>Kadr Y</label><input id="iY" type="range" min="0" max="100" value="${c.y}"><label>Zoom</label><input id="iZoom" type="range" min="1" max="3" step=".02" value="${c.zoom}">`;const go=()=>{c.x=+$('#iX').value;c.y=+$('#iY').value;c.zoom=+$('#iZoom').value;applyAll();scheduleSave()};for(const id of['iX','iY','iZoom'])$('#'+id).oninput=go;$('#chooseImg').onclick=openMedia}
function renderSection(){const k=sectionKey(selected),c=sectionCfg(k),cs=win().getComputedStyle(selected);inspector.innerHTML=`<div class="type">SEKCJA</div><h3>${k}</h3><label>Odstęp góra</label><input id="sTop" type="number"><label>Odstęp dół</label><input id="sBottom" type="number"><label>Kolor tła</label><input id="sBg" type="color"><label><input id="sHide" type="checkbox" style="width:auto"> Ukryj</label>`;$('#sTop').value=c.paddingTop??parseInt(cs.paddingTop)||0;$('#sBottom').value=c.paddingBottom??parseInt(cs.paddingBottom)||0;$('#sBg').value=toHex(c.background||cs.backgroundColor);$('#sHide').checked=c.hidden===true;const go=()=>{Object.assign(c,{paddingTop:+$('#sTop').value,paddingBottom:+$('#sBottom').value,background:$('#sBg').value,hidden:$('#sHide').checked});applyAll();scheduleSave()};for(const id of['sTop','sBottom','sBg','sHide'])$('#'+id).onchange=go}

async function loadMedia(){mediaGrid.innerHTML='<p>Ładowanie…</p>';const res=await listAll(sRef(storage,'website/media'));library=[];for(const it of res.items){if(!/\.(jpe?g|png|webp|gif|avif)$/i.test(it.name))continue;try{library.push({name:it.name,url:await getDownloadURL(it)})}catch{}}mediaCount.textContent=library.length+' zdjęć';mediaGrid.innerHTML=library.map((x,i)=>`<div class="veMediaItem" data-i="${i}"><img loading="lazy" src="${x.url}"><div>${x.name}</div></div>`).join('');$$('.veMediaItem',mediaGrid).forEach(el=>el.onclick=()=>{draft.homeMedia[mediaKey(selected)].url=library[+el.dataset.i].url;applyAll();mediaModal.hidden=true;scheduleSave()})}
function openMedia(){mediaModal.hidden=false;if(!library.length)loadMedia().catch(console.error)}
$('#mediaClose').onclick=()=>mediaModal.hidden=true;$('#mediaUpload').onchange=()=>[...$('#mediaUpload').files].forEach(file=>{const t=uploadBytesResumable(sRef(storage,`website/media/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`),file);t.on('state_changed',null,console.error,loadMedia)});
function setDevice(d){device=d;deviceFrame.className='veDeviceFrame '+d;$$('[data-device]').forEach(b=>b.classList.toggle('active',b.dataset.device===d));setTimeout(()=>{applyAll();renderInspector();renderOverlay()},120)}$$('[data-device]').forEach(b=>b.onclick=()=>setDevice(b.dataset.device));
$$('[data-jump]').forEach(b=>b.onclick=e=>{e.preventDefault();const k=b.dataset.jump,d=doc(),el=k==='hero'?d.querySelector('header.hero'):d.querySelector(`[data-home-section="${k}"]`);if(el){el.scrollIntoView({behavior:'smooth',block:'start'});select(el)}});
$('#previewBtn').onclick=()=>{previewMode=!previewMode;$('#previewBtn').textContent=previewMode?'Wróć do edycji':'Podgląd';if(previewMode)removeOverlay();else renderOverlay()};
$('#undoBtn').onclick=()=>{if(!undoStack.length)return;redoStack.push(clone(draft));draft=undoStack.pop();ensure();applyAll();renderInspector();renderOverlay();scheduleSave()};$('#redoBtn').onclick=()=>{if(!redoStack.length)return;undoStack.push(clone(draft));draft=redoStack.pop();ensure();applyAll();renderInspector();renderOverlay();scheduleSave()};
$('#publishBtn').onclick=async()=>{const b=$('#publishBtn');b.disabled=true;b.textContent='PUBLIKOWANIE…';try{await Promise.all([set(ref(db,`${WEBSITE_ROOT}/public/site`),draft.site||{}),set(ref(db,`${WEBSITE_ROOT}/public/homeContent`),draft.homeContent||{}),set(ref(db,`${WEBSITE_ROOT}/public/homeMedia`),draft.homeMedia||{}),set(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),draft.visualStyles||{})]);status('Opublikowano ✓');b.textContent='OPUBLIKOWANO ✓';setTimeout(()=>b.textContent='OPUBLIKUJ',1500)}catch(e){alert('Błąd publikacji: '+e.message);b.textContent='OPUBLIKUJ'}finally{b.disabled=false}};
async function init(){status('Ładowanie…');const p=await get(ref(db,`${WEBSITE_ROOT}/public`)),pub=norm(p.val()||{}),ds=await get(ref(db,`${WEBSITE_ROOT}/public/editorDraft`));draft=ds.exists()?ds.val():clone(pub);draft.site={...pub.site,...(draft.site||{})};draft.homeContent={...pub.homeContent,...(draft.homeContent||{})};draft.homeMedia={...pub.homeMedia,...(draft.homeMedia||{})};draft.visualStyles={texts:{...(pub.visualStyles?.texts||{}),...(draft.visualStyles?.texts||{})},sections:{...(pub.visualStyles?.sections||{}),...(draft.visualStyles?.sections||{})}};ensure();const ready=()=>{install();status('Gotowe ✓')};frame.addEventListener('load',ready,{once:true});if(frame.contentDocument?.readyState==='complete')ready()}
init().catch(e=>{status('Błąd');console.error(e)});