import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { getStorage, ref as sRef, listAll, getDownloadURL, uploadBytesResumable } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";

const app = initializeApp(firebaseConfig);
const db = getDatabase(app);
const storage = getStorage(app);
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const frame = $('#siteFrame');
const inspector = $('#inspector');
const deviceFrame = $('#deviceFrame');
const draftState = $('#draftState');
const mediaModal = $('#mediaModal');
const mediaGrid = $('#mediaGrid');
const mediaCount = $('#mediaCount');
let draft = null, selected = null, overlay = null, device = 'desktop', previewMode = false, saveTimer = null, library = [], drag = null;
const clone = x => JSON.parse(JSON.stringify(x));
const mediaDefaults = {heroMedia:{url:''},photoPortal:{url:'assets/portal-photo.png'},filmPortal:{url:'assets/portal-film.png'},aboutPortrait:{url:'assets/about-portrait.jpg'}};
const baseMedia = () => ({x:50,y:50,zoom:1});
const baseTransform = () => ({moveX:0,moveY:0,scale:1,rotate:0,width:null});
const doc = () => frame.contentDocument;
const win = () => frame.contentWindow;
const status = t => { if (draftState) draftState.textContent = t; };
function textKey(el){if(!el)return'';if(['heroK','heroT','heroD'].includes(el.id))return el.id;return el.dataset.homeText||''}
function mediaKey(el){return el?.dataset?.homeMedia||''}
function sectionKey(el){if(!el)return'';return el.matches('header.hero')?'Hero':(el.dataset.homeSection||'')}
function normalize(raw={}){return{site:raw.site||{},homeContent:raw.homeContent||{},homeMedia:raw.homeMedia||{},visualStyles:raw.visualStyles||{texts:{},sections:{}}}}
function ensureDraft(){draft.site||={};draft.homeContent||={};draft.homeMedia||={};draft.visualStyles||={};draft.visualStyles.texts||={};draft.visualStyles.sections||={};for(const[k,v]of Object.entries(mediaDefaults)){draft.homeMedia[k]||={url:v.url,desktop:baseMedia(),tablet:baseMedia(),mobile:baseMedia()};for(const d of['desktop','tablet','mobile'])draft.homeMedia[k][d]={...baseMedia(),...(draft.homeMedia[k][d]||{})}}}
function textCfg(key){draft.visualStyles.texts[key]||={};draft.visualStyles.texts[key][device]={...baseTransform(),...(draft.visualStyles.texts[key][device]||{})};return draft.visualStyles.texts[key][device]}
function sectionCfg(key){draft.visualStyles.sections[key]||={};draft.visualStyles.sections[key][device]||={};return draft.visualStyles.sections[key][device]}
function getText(key){return['heroK','heroT','heroD'].includes(key)?(draft.site[key]??''):(draft.homeContent[key]??'')}
function setText(key,value){if(['heroK','heroT','heroD'].includes(key))draft.site[key]=value;else draft.homeContent[key]=value}
function scheduleSave(){status('Zapisywanie roboczo…');clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,450)}
async function saveDraft(){try{await set(ref(db,`${WEBSITE_ROOT}/public/editorDraft`),draft);status('Wersja robocza ✓')}catch(e){console.error(e);status('Błąd zapisu')}}
function toHex(c){if(/^#[0-9a-f]{6}$/i.test(c))return c;const m=String(c).match(/\d+/g);return m?'#'+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,'0')).join(''):'#ffffff'}
function applyTextStyle(el,key){const c=draft.visualStyles?.texts?.[key]?.[device]||{};el.style.fontSize=c.fontSize!=null?`${c.fontSize}px`:'';el.style.color=c.color||'';el.style.textAlign=c.textAlign||'';el.style.width=c.width?`${c.width}px`:'';el.style.maxWidth=c.width?`${c.width}px`:'';el.style.transformOrigin='center center';el.style.transform=`translate(${Number(c.moveX)||0}px, ${Number(c.moveY)||0}px) rotate(${Number(c.rotate)||0}deg) scale(${Number(c.scale)||1})`;el.style.position='relative';el.style.zIndex='5'}
function applyAll(){const d=doc();if(!d||!draft)return;d.querySelectorAll('[data-home-text],#heroK,#heroT,#heroD').forEach(el=>{if(!el.isContentEditable){const key=textKey(el),value=getText(key);if(value!==''&&value!=null){if(el.dataset.multiline==='1'||key==='heroT')el.innerHTML=String(value).replace(/\n/g,'<br>');else el.textContent=value}}applyTextStyle(el,textKey(el))});d.querySelectorAll('[data-home-media]').forEach(el=>{const key=mediaKey(el),m=draft.homeMedia[key];if(!m)return;const c={...baseMedia(),...(m[device]||{})};if(m.url)el.src=m.url;el.style.objectFit='cover';el.style.objectPosition=`${c.x}% ${c.y}%`;el.style.transformOrigin=`${c.x}% ${c.y}%`;el.style.transform=`scale(${c.zoom})`;if(key==='heroMedia'&&m.url)el.style.opacity='1'});d.querySelectorAll('[data-home-section],header.hero').forEach(el=>{const c=draft.visualStyles.sections?.[sectionKey(el)]?.[device]||{};el.style.paddingTop=c.paddingTop!=null?`${c.paddingTop}px`:'';el.style.paddingBottom=c.paddingBottom!=null?`${c.paddingBottom}px`:'';el.style.background=c.background||'';el.style.display=c.hidden===true?'none':''});updateOverlay()}
function install(){const d=doc();if(!d)return;let style=d.querySelector('#rafEditorV6Style');if(!style){style=d.createElement('style');style.id='rafEditorV6Style';d.head.appendChild(style)}style.textContent=`body.rafEdit [data-home-text],body.rafEdit #heroK,body.rafEdit #heroT,body.rafEdit #heroD,body.rafEdit [data-home-media]{cursor:pointer}body.rafEdit .raf-selected{outline:2px solid #22a8ff!important;outline-offset:4px}.raf-box{position:absolute;z-index:999999;border:2px solid #22a8ff;box-sizing:border-box;pointer-events:none}.raf-move,.raf-scale,.raf-rotate{pointer-events:auto;touch-action:none;user-select:none}.raf-move{position:absolute;left:4px;top:-31px;background:#168ee6;color:#fff;border-radius:7px;padding:5px 9px;font:700 12px system-ui;cursor:move}.raf-scale,.raf-rotate{position:absolute;width:16px;height:16px;border-radius:50%;background:#fff;border:2px solid #168ee6;box-sizing:border-box}.raf-scale{right:-9px;bottom:-9px;cursor:nwse-resize}.raf-rotate{left:50%;top:-39px;transform:translateX(-50%);cursor:grab}.raf-rotate:after{content:'';position:absolute;left:6px;top:14px;height:22px;border-left:2px solid #22a8ff}.raf-size{position:absolute;right:4px;top:-28px;background:#111;color:#fff;border:1px solid #ffffff30;border-radius:5px;padding:3px 6px;font:11px system-ui}`;d.body.classList.add('rafEdit');d.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&!previewMode){e.preventDefault();e.stopPropagation()}},true);for(const el of d.querySelectorAll('[data-home-text],[data-home-media],[data-home-section],#heroK,#heroT,#heroD,header.hero')){if(el.dataset.rafBound==='1')continue;el.dataset.rafBound='1';el.addEventListener('click',e=>{if(previewMode)return;e.preventDefault();e.stopPropagation();const target=e.target.closest('[data-home-text],[data-home-media],#heroK,#heroT,#heroD')||e.target.closest('[data-home-section],header.hero')||el;select(target)});if(el.matches('[data-home-text],#heroK,#heroT,#heroD'))el.addEventListener('dblclick',e=>{if(previewMode)return;e.preventDefault();e.stopPropagation();select(el);beginInlineEdit(el)})}d.addEventListener('pointermove',onPointerMove,true);d.addEventListener('pointerup',onPointerUp,true);d.addEventListener('pointercancel',onPointerUp,true);d.addEventListener('scroll',updateOverlay,{passive:true});win().addEventListener('resize',updateOverlay);applyAll()}
function select(el){const d=doc();d.querySelectorAll('.raf-selected').forEach(x=>x.classList.remove('raf-selected'));el.classList.add('raf-selected');selected=el;renderInspector();renderOverlay()}
function beginInlineEdit(el){removeOverlay();el.contentEditable='true';el.focus();const key=textKey(el);const onInput=()=>{setText(key,el.innerText);scheduleSave()};const onBlur=()=>{el.contentEditable='false';el.removeEventListener('input',onInput);el.removeEventListener('blur',onBlur);setText(key,el.innerText);scheduleSave();renderInspector();renderOverlay()};el.addEventListener('input',onInput);el.addEventListener('blur',onBlur)}
function removeOverlay(){overlay?.remove();overlay=null}
function renderOverlay(){removeOverlay();if(!selected||previewMode||!selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return;const d=doc();overlay=d.createElement('div');overlay.className='raf-box';overlay.innerHTML='<div class="raf-move">✥ PRZESUŃ</div><div class="raf-size"></div><div class="raf-rotate"></div><div class="raf-scale"></div>';d.body.appendChild(overlay);overlay.querySelector('.raf-move').addEventListener('pointerdown',e=>beginTransform('move',e));overlay.querySelector('.raf-scale').addEventListener('pointerdown',e=>beginTransform('scale',e));overlay.querySelector('.raf-rotate').addEventListener('pointerdown',e=>beginTransform('rotate',e));updateOverlay()}
function updateOverlay(){if(!overlay||!selected?.isConnected)return;const r=selected.getBoundingClientRect(),w=win();overlay.style.left=`${r.left+w.scrollX}px`;overlay.style.top=`${r.top+w.scrollY}px`;overlay.style.width=`${r.width}px`;overlay.style.height=`${r.height}px`;const size=overlay.querySelector('.raf-size');if(size)size.textContent=`${Math.round(r.width)} × ${Math.round(r.height)}`}
function beginTransform(mode,e){if(!selected)return;e.preventDefault();e.stopPropagation();const cfg=textCfg(textKey(selected));const r=selected.getBoundingClientRect();drag={mode,pid:e.pointerId,sx:e.clientX,sy:e.clientY,start:{...cfg},cx:r.left+r.width/2,cy:r.top+r.height/2};drag.dist=Math.max(10,Math.hypot(e.clientX-drag.cx,e.clientY-drag.cy));drag.angle=Math.atan2(e.clientY-drag.cy,e.clientX-drag.cx);try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}}
function onPointerMove(e){if(!drag||e.pointerId!==drag.pid||!selected)return;e.preventDefault();const cfg=textCfg(textKey(selected));if(drag.mode==='move'){cfg.moveX=drag.start.moveX+(e.clientX-drag.sx);cfg.moveY=drag.start.moveY+(e.clientY-drag.sy)}else if(drag.mode==='scale'){const dist=Math.max(10,Math.hypot(e.clientX-drag.cx,e.clientY-drag.cy));cfg.scale=Math.max(.2,Math.min(4,drag.start.scale*(dist/drag.dist)))}else if(drag.mode==='rotate'){const a=Math.atan2(e.clientY-drag.cy,e.clientX-drag.cx);cfg.rotate=drag.start.rotate+(a-drag.angle)*180/Math.PI;if(e.shiftKey)cfg.rotate=Math.round(cfg.rotate/15)*15}applyTextStyle(selected,textKey(selected));syncInspector();updateOverlay()}
function onPointerUp(e){if(!drag||e.pointerId!==drag.pid)return;drag=null;scheduleSave();renderInspector();updateOverlay()}
function syncInspector(){if(!selected)return;const c=textCfg(textKey(selected));if($('#iMoveX'))$('#iMoveX').value=Math.round(c.moveX);if($('#iMoveY'))$('#iMoveY').value=Math.round(c.moveY);if($('#iScale'))$('#iScale').value=Number(c.scale).toFixed(2);if($('#iRotate'))$('#iRotate').value=Math.round(c.rotate)}
function renderInspector(){if(!selected){inspector.innerHTML='<div class="veEmpty"><b>Wybierz element</b><p>Kliknij tekst, zdjęcie albo sekcję.</p></div>';return}if(selected.matches('[data-home-media]'))return renderImageInspector();if(selected.matches('[data-home-text],#heroK,#heroT,#heroD'))return renderTextInspector();return renderSectionInspector()}
function renderTextInspector(){const key=textKey(selected),c=textCfg(key),cs=win().getComputedStyle(selected);inspector.innerHTML=`<div class="type">TEKST / POLE</div><h3>${key}</h3><div class="veHint">1 klik = zaznacz • 2 klik = pisz • PRZESUŃ = przeciągnij</div><label>Treść</label><textarea id="iText"></textarea><div class="veRow"><div><label>X</label><input id="iMoveX" type="number"></div><div><label>Y</label><input id="iMoveY" type="number"></div></div><div class="veRow"><div><label>Skala</label><input id="iScale" type="number" min=".2" max="4" step=".05"></div><div><label>Obrót °</label><input id="iRotate" type="number"></div></div><label>Szerokość pola px</label><input id="iWidth" type="number" min="0"><label>Rozmiar tekstu px</label><input id="iSize" type="number" min="8" max="220"><label>Kolor</label><input id="iColor" type="color"><label>Wyrównanie</label><select id="iAlign"><option value="left">Lewo</option><option value="center">Środek</option><option value="right">Prawo</option></select><div class="veBtns"><button id="resetTransform">Reset pozycji</button></div>`;$('#iText').value=getText(key)||selected.innerText;$('#iMoveX').value=Math.round(c.moveX);$('#iMoveY').value=Math.round(c.moveY);$('#iScale').value=c.scale;$('#iRotate').value=Math.round(c.rotate);$('#iWidth').value=c.width||0;$('#iSize').value=c.fontSize||Math.round(parseFloat(cs.fontSize));$('#iColor').value=toHex(c.color||cs.color);$('#iAlign').value=c.textAlign||cs.textAlign||'left';const apply=()=>{setText(key,$('#iText').value);c.moveX=+$('#iMoveX').value||0;c.moveY=+$('#iMoveY').value||0;c.scale=+$('#iScale').value||1;c.rotate=+$('#iRotate').value||0;c.width=+$('#iWidth').value||null;c.fontSize=+$('#iSize').value||null;c.color=$('#iColor').value;c.textAlign=$('#iAlign').value;if(!selected.isContentEditable)selected.textContent=$('#iText').value;applyTextStyle(selected,key);updateOverlay();scheduleSave()};for(const id of['iText','iMoveX','iMoveY','iScale','iRotate','iWidth','iSize','iColor','iAlign'])$('#'+id).addEventListener('input',apply);$('#resetTransform').onclick=()=>{Object.assign(c,baseTransform());applyTextStyle(selected,key);renderInspector();updateOverlay();scheduleSave()}}
function renderImageInspector(){const key=mediaKey(selected),c=draft.homeMedia[key][device];inspector.innerHTML=`<div class="type">ZDJĘCIE</div><h3>${key}</h3><button id="chooseImg" class="primary">Zmień zdjęcie</button><label>Kadr X</label><input id="iX" type="range" min="0" max="100" value="${c.x}"><label>Kadr Y</label><input id="iY" type="range" min="0" max="100" value="${c.y}"><label>Zoom</label><input id="iZoom" type="range" min="1" max="3" step=".02" value="${c.zoom}">`;const apply=()=>{c.x=+$('#iX').value;c.y=+$('#iY').value;c.zoom=+$('#iZoom').value;applyAll();scheduleSave()};for(const id of['iX','iY','iZoom'])$('#'+id).oninput=apply;$('#chooseImg').onclick=openMedia}
function renderSectionInspector(){const key=sectionKey(selected),c=sectionCfg(key),cs=win().getComputedStyle(selected);inspector.innerHTML=`<div class="type">SEKCJA</div><h3>${key}</h3><label>Odstęp góra</label><input id="sTop" type="number"><label>Odstęp dół</label><input id="sBottom" type="number"><label>Kolor tła</label><input id="sBg" type="color"><label><input id="sHide" type="checkbox" style="width:auto"> Ukryj na tym urządzeniu</label>`;$('#sTop').value=c.paddingTop??(parseInt(cs.paddingTop)||0);$('#sBottom').value=c.paddingBottom??(parseInt(cs.paddingBottom)||0);$('#sBg').value=toHex(c.background||cs.backgroundColor);$('#sHide').checked=c.hidden===true;const apply=()=>{c.paddingTop=+$('#sTop').value;c.paddingBottom=+$('#sBottom').value;c.background=$('#sBg').value;c.hidden=$('#sHide').checked;applyAll();scheduleSave()};for(const id of['sTop','sBottom','sBg','sHide'])$('#'+id).addEventListener('change',apply)}
async function loadMedia(){mediaGrid.innerHTML='<p>Ładowanie…</p>';const res=await listAll(sRef(storage,'website/media'));library=[];for(const it of res.items){if(!/\.(jpe?g|png|webp|gif|avif)$/i.test(it.name))continue;try{library.push({name:it.name,url:await getDownloadURL(it)})}catch{}}mediaCount.textContent=`${library.length} zdjęć`;mediaGrid.innerHTML=library.map((x,i)=>`<div class="veMediaItem" data-i="${i}"><img loading="lazy" src="${x.url}"><div>${x.name}</div></div>`).join('');$$('.veMediaItem',mediaGrid).forEach(el=>el.onclick=()=>{draft.homeMedia[mediaKey(selected)].url=library[+el.dataset.i].url;applyAll();mediaModal.hidden=true;scheduleSave()})}
function openMedia(){mediaModal.hidden=false;if(!library.length)loadMedia().catch(console.error)}
$('#mediaClose').onclick=()=>mediaModal.hidden=true;
$('#mediaUpload').onchange=()=>[...$('#mediaUpload').files].forEach(file=>{const path=`website/media/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const task=uploadBytesResumable(sRef(storage,path),file);task.on('state_changed',null,console.error,loadMedia)});
function setDevice(d){device=d;deviceFrame.className=`veDeviceFrame ${d}`;$$('[data-device]').forEach(b=>b.classList.toggle('active',b.dataset.device===d));setTimeout(()=>{applyAll();renderInspector();renderOverlay()},150)}
$$('[data-device]').forEach(b=>b.onclick=()=>setDevice(b.dataset.device));
$$('[data-jump]').forEach(b=>b.onclick=e=>{e.preventDefault();const key=b.dataset.jump,d=doc();const el=key==='hero'?d.querySelector('header.hero'):d.querySelector(`[data-home-section="${key}"]`);if(el){el.scrollIntoView({behavior:'smooth',block:'start'});select(el)}});
$('#previewBtn').onclick=()=>{previewMode=!previewMode;$('#previewBtn').textContent=previewMode?'Wróć do edycji':'Podgląd';if(previewMode)removeOverlay();else renderOverlay()};
$('#undoBtn').onclick=()=>{};$('#redoBtn').onclick=()=>{};
$('#publishBtn').onclick=async()=>{const btn=$('#publishBtn');btn.disabled=true;btn.textContent='PUBLIKOWANIE…';try{await Promise.all([set(ref(db,`${WEBSITE_ROOT}/public/site`),draft.site||{}),set(ref(db,`${WEBSITE_ROOT}/public/homeContent`),draft.homeContent||{}),set(ref(db,`${WEBSITE_ROOT}/public/homeMedia`),draft.homeMedia||{}),set(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),draft.visualStyles||{})]);status('Opublikowano ✓');btn.textContent='OPUBLIKOWANO ✓';setTimeout(()=>btn.textContent='OPUBLIKUJ',1500)}catch(e){console.error(e);alert('Błąd publikacji: '+e.message);btn.textContent='OPUBLIKUJ'}finally{btn.disabled=false}};
async function init(){status('Ładowanie…');const pubSnap=await get(ref(db,`${WEBSITE_ROOT}/public`)),pub=normalize(pubSnap.val()||{}),draftSnap=await get(ref(db,`${WEBSITE_ROOT}/public/editorDraft`));draft=draftSnap.exists()?normalize(draftSnap.val()):clone(pub);draft.site={...pub.site,...(draft.site||{})};draft.homeContent={...pub.homeContent,...(draft.homeContent||{})};draft.homeMedia={...pub.homeMedia,...(draft.homeMedia||{})};draft.visualStyles={texts:{...(pub.visualStyles?.texts||{}),...(draft.visualStyles?.texts||{})},sections:{...(pub.visualStyles?.sections||{}),...(draft.visualStyles?.sections||{})}};ensureDraft();const ready=()=>{install();status('Gotowe ✓')};frame.addEventListener('load',ready,{once:true});if(frame.contentDocument?.readyState==='complete')ready()}
init().catch(e=>{console.error(e);status('Błąd edytora')});