// RAF.studio — PRO editor v6.1
import { getApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase,ref,get,set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { PRO61_DEFAULTS,merge61,render61 } from './public-pro-v61.js?v=6.1.0';
const db=getDatabase(getApp()),$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],cp=x=>structuredClone(x),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let data=cp(PRO61_DEFAULTS),undo=[],redo=[],saveTimer=null,lastSource='pro';
const save=()=>{clearTimeout(saveTimer);saveTimer=setTimeout(()=>set(ref(db,'website/public/proV6Draft'),data),400);const st=$('#rafStatus3');if(st)st.textContent='● Zmiany robocze'};
function commit(){undo.push(cp(data));if(undo.length>80)undo.shift();redo=[];lastSource='pro';buttons()}
function apply(){merge61(data);render61();save();buttons()}
function undoPro(){if(!undo.length)return;redo.push(cp(data));data=undo.pop();apply();refreshOpen()}
function redoPro(){if(!redo.length)return;undo.push(cp(data));data=redo.pop();apply();refreshOpen()}
window.rafPro61Undo=undoPro;window.rafPro61Redo=redoPro;window.rafPro61Active=()=>lastSource==='pro'&&($('#rafProModal61')?.classList.contains('open')||!!$('.pro61-selected'));
function buttons(){const u=$('#u3'),r=$('#r3');if(u)u.style.opacity=undo.length?'1':'.5';if(r)r.style.opacity=redo.length?'1':'.5'}
function css(){if($('#proEditor61Css'))return;const s=document.createElement('style');s.id='proEditor61Css';s.textContent=`#rafProModal61{position:fixed;inset:62px 20px 20px;z-index:1000040;background:#0d0d0f;border:1px solid #ffffff20;border-radius:18px;display:none;color:#fff;overflow:hidden;font:13px system-ui;box-shadow:0 30px 90px #000b}#rafProModal61.open{display:grid;grid-template-columns:210px 1fr}.proNav61{padding:16px;border-right:1px solid #ffffff14;display:flex;flex-direction:column;gap:6px}.proNav61 button,.proBody61 button{background:#171719;color:#eee;border:1px solid #ffffff16;border-radius:9px;padding:10px;cursor:pointer}.proNav61 button.active{background:#fff;color:#111}.proBody61{padding:22px;overflow:auto}.proGrid61{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.proCard61{background:#131315;border:1px solid #ffffff14;border-radius:14px;padding:15px}.proCard61 label{display:block;color:#aaa;font-size:11px;margin:9px 0}.proCard61 input,.proCard61 select,.proCard61 textarea{width:100%;box-sizing:border-box;background:#080809;color:#fff;border:1px solid #343438;border-radius:8px;padding:9px}.proClose61{position:absolute;right:12px;top:10px}.proLayer61{display:flex;justify-content:space-between;padding:11px;margin:6px 0;border:1px solid #ffffff15;border-radius:10px;background:#111;cursor:grab}.pro61-selected{outline:2px solid #24a8ff!important;outline-offset:4px}.pro61-mini{font-size:10px;color:#888}.pro61-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pro61-actions{display:flex;gap:7px;flex-wrap:wrap}@media(max-width:800px){#rafProModal61.open{grid-template-columns:1fr}.proNav61{flex-direction:row;overflow:auto;border-right:0;border-bottom:1px solid #ffffff14}}`;document.head.appendChild(s)}
function top(){const t=$('#rafTop3');if(!t||$('#proBtn61'))return;$('#proBtn60')?.remove();const b=document.createElement('button');b.id='proBtn61';b.textContent='⚡ PRO';b.onclick=()=>open('global');t.insertBefore(b,$('#add3')||t.firstChild)}
function modal(){if($('#rafProModal61'))return;const m=document.createElement('div');m.id='rafProModal61';m.innerHTML=`<button class="proClose61">✕</button><aside class="proNav61">${[['global','Global Styles'],['buttons','Przyciski'],['gradient','Gradienty'],['hero','HERO video'],['stats','W liczbach'],['sections','Sekcje'],['motion','Animacje'],['contact','Formularz'],['performance','Waga strony']].map(([k,n])=>`<button data-tab="${k}">${n}</button>`).join('')}</aside><main class="proBody61"></main>`;document.body.appendChild(m);$('.proClose61',m).onclick=()=>m.classList.remove('open');$$('[data-tab]',m).forEach(x=>x.onclick=()=>renderTab(x.dataset.tab))}
let currentTab='global';function open(t='global'){modal();$('#rafProModal61').classList.add('open');renderTab(t)}function refreshOpen(){if($('#rafProModal61')?.classList.contains('open'))renderTab(currentTab)}
function field(id,l,v,type='text',extra=''){return `<label>${l}<input id="${id}" type="${type}" value="${esc(v)}" ${extra}></label>`}
function bind(id,fn,event='input'){const e=$('#'+id);if(!e)return;let pushed=false;const push=()=>{if(!pushed){commit();pushed=true}};e.addEventListener('focus',push,{once:true});e.addEventListener(event,()=>{push();fn(e);apply()})}
function renderTab(tab){currentTab=tab;$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));const b=$('.proBody61');if(!b)return;
if(tab==='global'){const g=data.global;b.innerHTML=`<h2>Global Styles</h2><div class="proGrid61"><div class="proCard61"><h3>Kolory</h3>${field('gBg','Tło',g.bg,'color')}${field('gTx','Tekst',g.text,'color')}${field('gMu','Tekst dodatkowy',g.muted,'color')}${field('gAc','Accent',g.accent,'color')}</div><div class="proCard61"><h3>Typografia</h3>${field('gH1','H1 px',g.h1,'number')}${field('gH2','H2 px',g.h2,'number')}${field('gBo','Tekst px',g.body,'number')}${field('gRa','Rogi px',g.radius,'number')}</div></div>`;bind('gBg',e=>g.bg=e.value);bind('gTx',e=>g.text=e.value);bind('gMu',e=>g.muted=e.value);bind('gAc',e=>g.accent=e.value);bind('gH1',e=>g.h1=+e.value);bind('gH2',e=>g.h2=+e.value);bind('gBo',e=>g.body=+e.value);bind('gRa',e=>g.radius=+e.value);return}
if(tab==='buttons'){const x=data.button;b.innerHTML=`<h2>Przyciski</h2><div class="proCard61"><label>Styl<select id="bStyle"><option value="pill">Pełny / Pill</option><option value="outline">Outline</option></select></label>${field('bBg','Tło',x.bg,'color')}${field('bTx','Tekst',x.text,'color')}${field('bBr','Obramowanie',x.border,'color')}${field('bRa','Rogi',x.radius,'number')}<label>Hover<select id="bHv"><option value="lift">Lekko w górę</option><option value="none">Brak</option></select></label></div>`;$('#bStyle').value=x.style;$('#bHv').value=x.hover;bind('bStyle',e=>x.style=e.value,'change');bind('bBg',e=>x.bg=e.value);bind('bTx',e=>x.text=e.value);bind('bBr',e=>x.border=e.value);bind('bRa',e=>x.radius=+e.value);bind('bHv',e=>x.hover=e.value,'change');return}
if(tab==='gradient'){const x=data.gradient;b.innerHTML=`<h2>Gradienty</h2><div class="proCard61"><label><input id="grOn61" type="checkbox" ${x.enabled?'checked':''}> Włącz</label>${field('grA61','Kolor 1',x.from,'color')}${field('grB61','Kolor 2',x.to,'color')}${field('grAng61','Kąt',x.angle,'number')}</div>`;$('#grOn61').onchange=e=>{commit();x.enabled=e.target.checked;apply()};bind('grA61',e=>x.from=e.value);bind('grB61',e=>x.to=e.value);bind('grAng61',e=>x.angle=+e.value);return}
if(tab==='hero'){const x=data.heroVideo;b.innerHTML=`<h2>HERO — video</h2><div class="proGrid61"><div class="proCard61"><label><input id="hvOn61" type="checkbox" ${x.enabled?'checked':''}> Włącz video</label>${field('hvUrl61','YouTube / Vimeo / MP4',x.url)}<label>Dopasowanie<select id="hvFit61"><option value="cover">Wypełnij / cover</option><option value="contain">Cały film / contain</option></select></label>${field('hvOp61','Opacity %',x.opacity,'number','min="0" max="100"')}${field('hvZoom61','Zoom',x.zoom,'number','step="0.05" min="0.5" max="3"')}</div><div class="proCard61"><h3>Kadr</h3>${field('hvX61','Kadr X %',x.x,'number','min="0" max="100"')}${field('hvY61','Kadr Y %',x.y,'number','min="0" max="100"')}<label><input id="hvMob61" type="checkbox" ${x.mobileImage?'checked':''}> Telefon: używaj zdjęcia</label><label><input id="hvMute61" type="checkbox" ${x.mute!==false?'checked':''}> Wycisz</label><label><input id="hvLoop61" type="checkbox" ${x.loop!==false?'checked':''}> Pętla</label></div></div>`;$('#hvFit61').value=x.fit||'cover';for(const [id,key] of [['hvOn61','enabled'],['hvMob61','mobileImage'],['hvMute61','mute'],['hvLoop61','loop']])$('#'+id).onchange=e=>{commit();x[key]=e.target.checked;apply()};bind('hvUrl61',e=>x.url=e.value);bind('hvFit61',e=>x.fit=e.value,'change');bind('hvOp61',e=>x.opacity=+e.value);bind('hvZoom61',e=>x.zoom=+e.value);bind('hvX61',e=>x.x=+e.value);bind('hvY61',e=>x.y=+e.value);return}
if(tab==='stats'){const x=data.stats;b.innerHTML=`<h2>W LICZBACH — pełna konfiguracja</h2><div class="proGrid61"><div class="proCard61">${field('stTitle61','Tytuł',x.title)}${field('stSub61','Opis',x.subtitle)}${field('stCols61','Kolumny',x.columns,'number','min="1" max="6"')}${field('stTop61','Odstęp góra',x.paddingTop,'number')}${field('stBot61','Odstęp dół',x.paddingBottom,'number')}${field('stBg61','Tło',x.background||'#050505','color')}<label><input id="stOn61" type="checkbox" ${x.enabled?'checked':''}> Pokazuj sekcję</label></div><div class="proCard61"><h3>Wartości</h3>${x.items.map((it,i)=>`<div class="pro61-row">${field(`stv${i}`,'Wartość',it.value)}${field(`stl${i}`,'Opis',it.label)}</div>`).join('')}<button id="stAdd61">+ Dodaj licznik</button></div></div>`;bind('stTitle61',e=>x.title=e.value);bind('stSub61',e=>x.subtitle=e.value);bind('stCols61',e=>x.columns=+e.value);bind('stTop61',e=>x.paddingTop=+e.value);bind('stBot61',e=>x.paddingBottom=+e.value);bind('stBg61',e=>x.background=e.value);$('#stOn61').onchange=e=>{commit();x.enabled=e.target.checked;apply()};x.items.forEach((it,i)=>{bind(`stv${i}`,e=>it.value=e.value);bind(`stl${i}`,e=>it.label=e.value)});$('#stAdd61').onclick=()=>{commit();x.items.push({value:'100+',label:'nowa wartość'});apply();renderTab('stats')};return}
if(tab==='sections'){b.innerHTML=`<h2>Kolejność sekcji</h2><div class="proCard61" id="layers61">${data.sectionOrder.map(k=>`<div class="proLayer61" draggable="true" data-key="${k}"><span>☰ ${k}</span><small>przeciągnij</small></div>`).join('')}</div>`;let drag='';$$('.proLayer61').forEach(el=>{el.ondragstart=()=>drag=el.dataset.key;el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();if(!drag||drag===el.dataset.key)return;commit();const a=data.sectionOrder.filter(x=>x!==drag),i=a.indexOf(el.dataset.key);a.splice(i,0,drag);data.sectionOrder=a;apply();renderTab('sections')}});return}
if(tab==='motion'){const x=data.scroll,t=data.timeline;b.innerHTML=`<h2>Animacje</h2><div class="proGrid61"><div class="proCard61"><label><input id="moOn61" type="checkbox" ${x.enabled?'checked':''}> Animacje przy scrollu</label><label>Efekt<select id="moType61"><option value="fade-up">Fade up</option><option value="fade">Fade</option><option value="slide-left">Slide left</option><option value="zoom">Zoom</option></select></label>${field('moDur61','Czas ms',x.duration,'number')}${field('moSta61','Stagger ms',x.stagger,'number')}</div><div class="proCard61"><h3>Timeline HERO</h3>${field('tl161','Nagłówek',t.heroTitle,'number')}${field('tl261','Opis',t.heroDesc,'number')}${field('tl361','Przyciski',t.heroButtons,'number')}</div></div>`;$('#moType61').value=x.defaultAnimation;$('#moOn61').onchange=e=>{commit();x.enabled=e.target.checked;apply()};bind('moType61',e=>x.defaultAnimation=e.value,'change');bind('moDur61',e=>x.duration=+e.value);bind('moSta61',e=>x.stagger=+e.value);bind('tl161',e=>t.heroTitle=+e.value);bind('tl261',e=>t.heroDesc=+e.value);bind('tl361',e=>t.heroButtons=+e.value);return}
if(tab==='contact'){const x=data.contactForm;b.innerHTML=`<h2>Formularz kontaktowy</h2><div class="proCard61"><label><input id="cfOn61" type="checkbox" ${x.enabled?'checked':''}> Pokazuj</label>${field('cfTitle61','Tytuł',x.title)}<label>Lista usług<textarea id="cfOpt61">${esc(x.serviceOptions)}</textarea></label></div>`;$('#cfOn61').onchange=e=>{commit();x.enabled=e.target.checked;apply()};bind('cfTitle61',e=>x.title=e.value);bind('cfOpt61',e=>x.serviceOptions=e.value);return}
if(tab==='performance'){const rows=performance.getEntriesByType('resource').map(e=>({n:e.name,s:e.transferSize||e.encodedBodySize||0})).filter(x=>x.s).sort((a,z)=>z.s-a.s),total=rows.reduce((a,x)=>a+x.s,0);b.innerHTML=`<h2>Waga strony</h2><div class="proCard61"><h3>${(total/1048576).toFixed(2)} MB</h3>${rows.slice(0,10).map(x=>`<div style="display:flex;justify-content:space-between;border-top:1px solid #ffffff12;padding:7px 0"><span>${esc(x.n.split('/').pop())}</span><b>${(x.s/1048576).toFixed(2)} MB</b></div>`).join('')}</div>`}}
function elementPanel(el){const key=el.dataset.pro61;if(!key)return;$$('.pro61-selected').forEach(x=>x.classList.remove('pro61-selected'));el.classList.add('pro61-selected');lastSource='pro';data.elementStyles[key]||={};const s=data.elementStyles[key],isVal=/\.value$/.test(key)||/\.label$/.test(key)||/title|subtitle/.test(key);const text=el.textContent.trim();const p=$('#rafPanel3');if(!p)return;p.style.display='block';p.innerHTML=`<div class="pro61-mini">V6.1 / ${esc(key)}</div><h3>Element dynamiczny</h3>${isVal?field('dpText61','Treść',text):''}<div class="pro61-row">${field('dpX61','X',s.x||0,'number')}${field('dpY61','Y',s.y||0,'number')}</div><div class="pro61-row">${field('dpSize61','Rozmiar',s.fontSize||parseInt(getComputedStyle(el).fontSize)||16,'number')}${field('dpScale61','Skala',s.scale||1,'number','step="0.05"')}</div>${field('dpColor61','Kolor',s.color||'#ffffff','color')}<label>Wyrównanie<select id="dpAlign61"><option value="left">Lewo</option><option value="center">Środek</option><option value="right">Prawo</option></select></label>${field('dpWidth61','Szerokość px',s.width||0,'number')}<label>Grubość<select id="dpWeight61">${[300,400,500,600,700,800,900].map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label>`;if($('#dpAlign61'))$('#dpAlign61').value=s.align||'left';if($('#dpWeight61'))$('#dpWeight61').value=s.fontWeight||getComputedStyle(el).fontWeight||400;if(isVal)bind('dpText61',e=>{setDynamicText(key,e.value);el.textContent=e.value});bind('dpX61',e=>s.x=+e.value);bind('dpY61',e=>s.y=+e.value);bind('dpSize61',e=>s.fontSize=+e.value);bind('dpScale61',e=>s.scale=+e.value);bind('dpColor61',e=>s.color=e.value);bind('dpAlign61',e=>s.align=e.value,'change');bind('dpWidth61',e=>s.width=+e.value);bind('dpWeight61',e=>s.fontWeight=e.value,'change')}
function setDynamicText(key,v){if(key==='stats.title')data.stats.title=v;else if(key==='stats.subtitle')data.stats.subtitle=v;else{const m=key.match(/^stats\.(\d+)\.(value|label)$/);if(m&&data.stats.items[+m[1]])data.stats.items[+m[1]][m[2]]=v}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-pro61]');if(!el||e.target.closest('#rafProModal61'))return;e.preventDefault();e.stopPropagation();elementPanel(el)},true);
const [d,p]=await Promise.all([get(ref(db,'website/public/proV6Draft')),get(ref(db,'website/public/proV6'))]);data={...cp(PRO61_DEFAULTS),...(d.val()||p.val()||{})};for(const k of ['global','button','gradient','heroVideo','stats','contactForm','scroll','timeline'])data[k]={...PRO61_DEFAULTS[k],...(data[k]||{})};data.stats.items=Array.isArray(data.stats.items)?data.stats.items:cp(PRO61_DEFAULTS.stats.items);data.elementStyles=data.elementStyles||{};css();top();merge61(data);render61();buttons();
