import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { getStorage, ref as sRef, listAll, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";

const app=initializeApp(firebaseConfig), db=getDatabase(app), storage=getStorage(app);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clone=x=>JSON.parse(JSON.stringify(x));
const isFilm=location.pathname.toLowerCase().includes('film.html');
const type=isFilm?'film':'photo';
const key=isFilm?'films':'photos';
let items=[],selectedId=null,editDevice='desktop',dirty=false,library=[],saveTimer=null;
const AUTOSAVE_MS=120000;
const defaultsCfg=d=>({span:d==='mobile'?12:6,ratio:isFilm?'16/9':'4/3',x:50,y:50});

function status(t){const e=$('#peStatus');if(e)e.textContent=t||(dirty?'● Zmiany robocze':'✓ Zapisano')}
function markDirty(){dirty=true;status();clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,1600)}
async function saveDraft(){try{await set(ref(db,`${WEBSITE_ROOT}/public/editorPortfolioDraft/${key}`),items);dirty=false;status('✓ Wersja robocza zapisana')}catch(e){console.error(e);status('Błąd zapisu')}}
setInterval(()=>{if(dirty)saveDraft()},AUTOSAVE_MS);
function cfg(item,d=editDevice){item[d]||=defaultsCfg(d);return item[d]}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}

function inject(){
 const st=document.createElement('style');st.id='portfolioEditorCss';st.textContent=`
 body.pe-edit .portfolioCard{cursor:pointer}.portfolioCard.pe-selected{outline:3px solid #1aa8ff!important;outline-offset:4px}.peTop{position:fixed;top:8px;left:50%;transform:translateX(-50%);z-index:1000010;background:#111e;border:1px solid #ffffff25;border-radius:14px;padding:6px 8px;display:flex;gap:6px;align-items:center;backdrop-filter:blur(18px);font:12px system-ui;color:#fff}.peTop button,.pePanel button{border:1px solid #ffffff22;background:#ffffff0b;color:#fff;border-radius:8px;padding:7px 9px;cursor:pointer}.peTop .pub{background:#fff;color:#111;font-weight:900}.peTop .active{background:#fff;color:#111}.pePanel{position:fixed;right:8px;top:62px;bottom:8px;width:340px;z-index:1000009;background:#111e;border:1px solid #ffffff25;border-radius:15px;padding:13px;overflow:auto;backdrop-filter:blur(20px);font:12px system-ui;color:#fff}.pePanel label{display:block;color:#aaa;font-size:10px;margin:10px 0 4px}.pePanel input,.pePanel select{width:100%;background:#080809;color:#fff;border:1px solid #343438;border-radius:8px;padding:8px;font:inherit}.peRow{display:grid;grid-template-columns:1fr 1fr;gap:7px}.peBtns{display:flex;gap:6px;flex-wrap:wrap}.peMedia{position:fixed;inset:60px 30px 30px;z-index:1000012;background:#111;border:1px solid #ffffff25;border-radius:16px;padding:14px;display:none;overflow:auto;color:#fff;font:12px system-ui}.peMedia.open{display:block}.peGrid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:9px}.peCard{border:1px solid #ffffff22;border-radius:9px;overflow:hidden;cursor:pointer}.peCard img{width:100%;aspect-ratio:1;object-fit:cover;display:block}.peCard small{display:block;padding:5px}.peGhost{opacity:.45}.peDrag{cursor:grab}.peHint{color:#999;font-size:11px;line-height:1.5}.peType{font-size:9px;letter-spacing:.15em;color:#888}@media(max-width:900px){.pePanel{left:8px;right:8px;top:auto;bottom:8px;width:auto;height:310px}.peTop{left:6px;right:6px;transform:none;flex-wrap:wrap;justify-content:center}.peGrid{grid-template-columns:repeat(3,minmax(0,1fr))}}
 `;document.head.appendChild(st);document.body.classList.add('pe-edit');
 const top=document.createElement('div');top.className='peTop';top.innerHTML=`<b>RAF.studio EDYTOR</b><button id="peHome">Strona główna</button><button id="pePhoto" class="${!isFilm?'active':''}">Fotografia</button><button id="peFilm" class="${isFilm?'active':''}">Film</button><button id="peAdd">+ Kafelek</button><span id="peStatus">✓ Zapisano</span><button id="peExit">Wyjdź</button><button id="pePublish" class="pub">OPUBLIKUJ</button>`;document.body.appendChild(top);
 const p=document.createElement('div');p.className='pePanel';p.id='pePanel';p.innerHTML='<div class="peType">PORTFOLIO</div><h3>Kliknij kafelek</h3><p class="peHint">Wybierz element na stronie, aby edytować go wizualnie.</p>';document.body.appendChild(p);
 const m=document.createElement('div');m.className='peMedia';m.id='peMedia';document.body.appendChild(m);
 $('#peHome').onclick=()=>location.href='index.html?editor=direct';$('#pePhoto').onclick=()=>location.href='fotografia.html?editor=direct';$('#peFilm').onclick=()=>location.href='film.html?editor=direct';$('#peExit').onclick=()=>location.href=isFilm?'film.html':'fotografia.html';$('#peAdd').onclick=addItem;$('#pePublish').onclick=publish;
}

function renderGrid(){
 const g=$(isFilm?'#filmGrid':'#photoGrid');if(!g)return;g.innerHTML='';
 items.forEach(item=>{const d=cfg(item,currentDevice());const el=document.createElement('article');el.className='portfolioCard reveal in';if(item.visible===false)el.classList.add('peGhost');el.style.setProperty('--span',d.span||12);el.style.aspectRatio=d.ratio||defaultsCfg(currentDevice()).ratio;el.dataset.id=item.id;el.dataset.type=type;el.innerHTML=`<img src="${esc(item.image||'')}" alt="${esc(item.title||'')}"><div class="shade"></div><div class="cap"><small>${esc(item.category||'')}</small><b>${esc(item.title||'Bez tytułu')}</b>${isFilm?'<span class="play">▶</span>':''}</div>`;const im=$('img',el);im.style.objectPosition=`${d.x??50}% ${d.y??50}%`;el.onclick=e=>{e.preventDefault();e.stopPropagation();select(item.id)};g.appendChild(el)});
 if(selectedId)select(selectedId,false);
}
function currentDevice(){return innerWidth<=640?'mobile':innerWidth<=980?'tablet':'desktop'}
function select(id,render=true){selectedId=id;$$('.portfolioCard').forEach(x=>x.classList.toggle('pe-selected',x.dataset.id===id));if(render)renderPanel()}
function selected(){return items.find(x=>x.id===selectedId)}

function renderPanel(){const item=selected(),p=$('#pePanel');if(!item){p.innerHTML='<div class="peType">PORTFOLIO</div><h3>Kliknij kafelek</h3>';return}const c=cfg(item);p.innerHTML=`<div class="peType">${isFilm?'FILM':'FOTOGRAFIA'} / ${esc(item.id)}</div><h3>${esc(item.title||'Kafelek')}</h3><div class="peBtns"><button data-dev="desktop" class="${editDevice==='desktop'?'active':''}">PC</button><button data-dev="tablet" class="${editDevice==='tablet'?'active':''}">Tablet</button><button data-dev="mobile" class="${editDevice==='mobile'?'active':''}">Telefon</button></div><label>Tytuł<input id="peTitle" value="${esc(item.title||'')}"></label><label>Kategoria<input id="peCategory" value="${esc(item.category||'')}"></label><label>Zdjęcie<input id="peImage" value="${esc(item.image||'')}"></label><button id="peChoose">Wybierz z biblioteki</button>${isFilm?`<label>Film URL<input id="peVideo" value="${esc(item.video||'')}" placeholder="YouTube / Vimeo / MP4"></label>`:''}<div class="peRow"><div><label>Szerokość / span</label><select id="peSpan">${[3,4,5,6,7,8,9,10,11,12].map(n=>`<option value="${n}" ${Number(c.span)===n?'selected':''}>${n}/12</option>`).join('')}</select></div><div><label>Proporcje</label><select id="peRatio">${['1/1','4/3','3/2','16/9','2/3','3/4'].map(v=>`<option ${c.ratio===v?'selected':''}>${v}</option>`).join('')}</select></div></div><label>Kadr X: <span id="xVal">${c.x??50}</span>%</label><input id="peX" type="range" min="0" max="100" value="${c.x??50}"><label>Kadr Y: <span id="yVal">${c.y??50}</span>%</label><input id="peY" type="range" min="0" max="100" value="${c.y??50}"><label>Widoczność<select id="peVisible"><option value="1" ${item.visible!==false?'selected':''}>Widoczny</option><option value="0" ${item.visible===false?'selected':''}>Ukryty</option></select></label><div class="peBtns"><button id="peUp">← Wcześniej</button><button id="peDown">Później →</button><button id="peDuplicate">Duplikuj</button><button id="peDelete">Usuń</button></div>`;
 $$('.peBtns [data-dev]',p).forEach(b=>b.onclick=()=>{editDevice=b.dataset.dev;renderPanel()});
 const live=()=>{item.title=$('#peTitle').value;item.category=$('#peCategory').value;item.image=$('#peImage').value;if(isFilm)item.video=$('#peVideo').value;const cc=cfg(item);cc.span=+$ ('#peSpan').value;cc.ratio=$('#peRatio').value;cc.x=+$('#peX').value;cc.y=+$('#peY').value;item.visible=$('#peVisible').value==='1';markDirty();renderGrid();renderPanelValuesOnly()};
 for(const id of ['peTitle','peCategory','peImage','peSpan','peRatio','peX','peY','peVisible',...(isFilm?['peVideo']:[])])$('#'+id).addEventListener('input',live);
 $('#peChoose').onclick=openMedia;$('#peUp').onclick=()=>moveItem(-1);$('#peDown').onclick=()=>moveItem(1);$('#peDuplicate').onclick=duplicateItem;$('#peDelete').onclick=deleteItem;
}
function renderPanelValuesOnly(){const item=selected();if(!item)return;const c=cfg(item);if($('#xVal'))$('#xVal').textContent=Math.round(c.x);if($('#yVal'))$('#yVal').textContent=Math.round(c.y)}
function moveItem(dir){const i=items.findIndex(x=>x.id===selectedId),j=i+dir;if(i<0||j<0||j>=items.length)return;[items[i],items[j]]=[items[j],items[i]];markDirty();renderGrid();renderPanel()}
function duplicateItem(){const i=items.findIndex(x=>x.id===selectedId);if(i<0)return;const n=clone(items[i]);n.id=`${type}-${Date.now()}`;n.title=(n.title||'Kafelek')+' — kopia';items.splice(i+1,0,n);selectedId=n.id;markDirty();renderGrid();renderPanel()}
function deleteItem(){if(!selectedId||!confirm('Usunąć ten kafelek?'))return;items=items.filter(x=>x.id!==selectedId);selectedId=null;markDirty();renderGrid();renderPanel()}
function addItem(){const n={id:`${type}-${Date.now()}`,title:isFilm?'Nowy film':'Nowe zdjęcie',category:isFilm?'Film':'Fotografia',image:'',visible:true,desktop:defaultsCfg('desktop'),tablet:defaultsCfg('tablet'),mobile:defaultsCfg('mobile')};if(isFilm)n.video='';items.push(n);selectedId=n.id;markDirty();renderGrid();renderPanel()}

async function loadMedia(){const grid=$('#peMedia');grid.innerHTML='<p>Ładowanie biblioteki…</p>';const res=await listAll(sRef(storage,'website/media'));library=[];for(const it of res.items){if(!/\.(jpe?g|png|webp|gif|avif)$/i.test(it.name))continue;try{library.push({name:it.name,url:await getDownloadURL(it)})}catch{}}grid.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><b>Biblioteka zdjęć</b><button id="peMediaClose">✕ Zamknij</button></div><div class="peGrid">${library.map((x,i)=>`<div class="peCard" data-i="${i}"><img src="${x.url}" loading="lazy"><small>${esc(x.name)}</small></div>`).join('')}</div>`;$('#peMediaClose').onclick=()=>grid.classList.remove('open');$$('.peCard',grid).forEach(c=>c.onclick=()=>{const item=selected();if(!item)return;item.image=library[+c.dataset.i].url;markDirty();grid.classList.remove('open');renderGrid();renderPanel()})}
function openMedia(){const m=$('#peMedia');m.classList.add('open');loadMedia().catch(e=>{console.error(e);m.innerHTML='<p>Błąd biblioteki.</p>'})}

async function publish(){const b=$('#pePublish');b.disabled=true;b.textContent='PUBLIKOWANIE…';try{await set(ref(db,`${WEBSITE_ROOT}/public/${key}`),items);await set(ref(db,`${WEBSITE_ROOT}/public/editorPortfolioDraft/${key}`),items);dirty=false;status('✓ Opublikowano');b.textContent='OPUBLIKOWANO ✓';setTimeout(()=>b.textContent='OPUBLIKUJ',1300)}catch(e){console.error(e);alert('Błąd publikacji: '+e.message);b.textContent='OPUBLIKUJ'}finally{b.disabled=false}}

async function init(){inject();status('Ładowanie…');const [pub,draftSnap]=await Promise.all([get(ref(db,`${WEBSITE_ROOT}/public/${key}`)),get(ref(db,`${WEBSITE_ROOT}/public/editorPortfolioDraft/${key}`))]);items=clone(draftSnap.exists()?draftSnap.val():(pub.val()||[]));renderGrid();status('✓ Gotowe');}
init().catch(e=>{console.error(e);status('Błąd edytora')});
