// RAF.studio — rozszerzenie edytora Foto/Film v4: strona zawsze w edytorze + typografia treści strony
import { initializeApp,getApps,getApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase,ref,get,set } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig,WEBSITE_ROOT } from "./firebase-config.js";
const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getDatabase(app),$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const isFilm=location.pathname.toLowerCase().includes('film.html'),prefix=isFilm?'filmPage':'photoPage',dev=()=>innerWidth<=640?'mobile':innerWidth<=980?'tablet':'desktop';let draft=null,selected=null,timer=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function ensure(d){d||={};d.homeContent||={};d.visualStyles||={};d.visualStyles.texts||={};d.builder||={};return d}
async function load(){const s=await get(ref(db,`${WEBSITE_ROOT}/public/editorDraft`));draft=ensure(s.val()||{})}
async function save(){await set(ref(db,`${WEBSITE_ROOT}/public/editorDraft`),draft)}
function dirty(){const s=$('#peStatus');if(s)s.textContent='● Zmiany robocze';clearTimeout(timer);timer=setTimeout(()=>save().then(()=>{if(s)s.textContent='✓ Wersja robocza zapisana'}).catch(console.error),1400)}
function key(el){return el.dataset.homeText||''}
function cfg(k){draft.visualStyles.texts[k]||={};draft.visualStyles.texts[k][dev()]||={};return draft.visualStyles.texts[k][dev()]}
function apply(el,c){if(c.fontFamily)el.style.fontFamily=c.fontFamily;if(c.fontWeight)el.style.fontWeight=c.fontWeight;if(c.fontSize)el.style.fontSize=`${c.fontSize}px`;if(c.lineHeight)el.style.lineHeight=c.lineHeight;if(c.letterSpacing!=null)el.style.letterSpacing=`${c.letterSpacing}px`;if(c.color)el.style.color=c.color;if(c.textAlign)el.style.textAlign=c.textAlign;if(c.textTransform)el.style.textTransform=c.textTransform}
function paint(){$$('[data-home-text]').forEach(el=>{const k=key(el),by=draft.visualStyles.texts[k]||{},d=by[dev()]||{},c=dev()==='desktop'||d.inherit===false?d:{...(by.desktop||{}),...d};apply(el,c);if(draft.homeContent[k]!=null)el.textContent=draft.homeContent[k]})}
const fonts=['Inter','Arial','Helvetica','Gill Sans MT','Verdana','Trebuchet MS','Georgia','Times New Roman','Courier New','Impact','system-ui'];
function panel(el){selected=el;$$('.v4PageSel').forEach(x=>x.classList.remove('v4PageSel'));el.classList.add('v4PageSel');const k=key(el),c=cfg(k),cs=getComputedStyle(el),p=$('#pePanel');p.innerHTML=`<div class="peType">TEKST / ${k}</div><h3>Typografia</h3><label>Treść<textarea id="pvText" rows="4">${el.textContent}</textarea></label><label>Czcionka<select id="pvFont">${fonts.map(f=>`<option ${((c.fontFamily||cs.fontFamily).includes(f))?'selected':''}>${f}</option>`).join('')}</select></label><label>Styl<select id="pvWeight"><option value="300">Light</option><option value="400">Regular</option><option value="500">Medium</option><option value="600">Semi Bold</option><option value="700">Bold</option><option value="800">Extra Bold</option><option value="900">Black</option></select></label><div class="peRow"><div><label>Rozmiar<input id="pvSize" type="number"></label></div><div><label>Interlinia<input id="pvLine" type="number" step=".05"></label></div></div><div class="peRow"><div><label>Tracking<input id="pvTrack" type="number" step=".5"></label></div><div><label>Kolor<input id="pvColor" type="color"></label></div></div><label>Wyrównanie<select id="pvAlign"><option value="left">Lewo</option><option value="center">Środek</option><option value="right">Prawo</option></select></label><label>Litery<select id="pvTransform"><option value="none">Bez zmian</option><option value="uppercase">WIELKIE</option><option value="lowercase">małe</option><option value="capitalize">Każde Słowo</option></select></label>`;$('#pvWeight').value=String(c.fontWeight||parseInt(cs.fontWeight)||400);$('#pvSize').value=c.fontSize||parseInt(cs.fontSize)||16;$('#pvLine').value=c.lineHeight||((parseFloat(cs.lineHeight)/parseFloat(cs.fontSize))||1.2);$('#pvTrack').value=c.letterSpacing??(parseFloat(cs.letterSpacing)||0);const rgb=cs.color.match(/\d+/g)||[255,255,255];$('#pvColor').value=c.color||'#'+rgb.slice(0,3).map(v=>(+v).toString(16).padStart(2,'0')).join('');$('#pvAlign').value=c.textAlign||cs.textAlign||'left';$('#pvTransform').value=c.textTransform||'none';const sync=()=>{draft.homeContent[k]=$('#pvText').value;c.fontFamily=$('#pvFont').value;c.fontWeight=n($('#pvWeight').value,400);c.fontSize=n($('#pvSize').value,16);c.lineHeight=n($('#pvLine').value,1.2);c.letterSpacing=n($('#pvTrack').value);c.color=$('#pvColor').value;c.textAlign=$('#pvAlign').value;c.textTransform=$('#pvTransform').value;el.textContent=draft.homeContent[k];apply(el,c);dirty()};['pvText','pvFont','pvWeight','pvSize','pvLine','pvTrack','pvColor','pvAlign','pvTransform'].forEach(id=>$('#'+id).oninput=sync)}
function prepText(){const hero=$('.pageHero');if(!hero)return;const eyebrow=$('.eyebrow',hero),h1=$('h1',hero),desc=$('p',hero);if(eyebrow)eyebrow.dataset.homeText=prefix+'Eyebrow';if(h1)h1.dataset.homeText=prefix+'Title';if(desc)desc.dataset.homeText=prefix+'Desc';$$('.filterbar .pill').forEach((el,i)=>el.dataset.homeText=prefix+'Filter'+i);$$('[data-home-text]').forEach(el=>{el.style.cursor='pointer';el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();panel(el)});el.addEventListener('dblclick',e=>{e.preventDefault();e.stopPropagation();el.contentEditable='true';el.focus();el.oninput=()=>{draft.homeContent[key(el)]=el.innerText;dirty()};el.onblur=()=>{el.contentEditable='false';panel(el)}})})}
function chrome(){const top=$('.peTop');if(!top)return;$('#peHome')?.remove();$('#pePhoto')?.remove();$('#peFilm')?.remove();if(!$('#pageSelect4')){const d=document.createElement('div');d.className='pagePick4';d.innerHTML=`<span>Strona</span><select id="pageSelect4"><option value="index.html">Strona główna</option><option value="fotografia.html">Fotografia</option><option value="film.html">Film</option></select>`;top.insertBefore(d,top.querySelector('#peAdd'));$('#pageSelect4').value=isFilm?'film.html':'fotografia.html';$('#pageSelect4').onchange=e=>location.href=e.target.value+'?editor=direct'}const b=top.querySelector('b');if(b)b.innerHTML='<img src="https://galeria.raf-studio.pl/logo-white.png" style="width:82px;height:28px;object-fit:contain">'}
async function publishPage(){await save();const s=await get(ref(db,`${WEBSITE_ROOT}/public/editorDraft`)),d=s.val()||{};if(d.homeContent!==undefined)await set(ref(db,`${WEBSITE_ROOT}/public/homeContent`),d.homeContent||{});if(d.visualStyles!==undefined)await set(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),d.visualStyles||{});if(d.builder!==undefined)await set(ref(db,`${WEBSITE_ROOT}/public/builder`),d.builder||{})}
function css(){const s=document.createElement('style');s.textContent='.v4PageSel{outline:2px solid #19a8ff!important;outline-offset:4px}.pagePick4{display:flex;align-items:center;gap:6px;padding:0 7px}.pagePick4 span{font-size:10px;color:#888}.pagePick4 select{background:#0b0b0c;color:#fff;border:1px solid #343438;border-radius:8px;padding:7px}.pePanel textarea{width:100%;background:#080809;color:#fff;border:1px solid #343438;border-radius:8px;padding:8px;font:inherit;resize:vertical}';document.head.appendChild(s)}
async function init(){css();await load();for(let i=0;i<80&&!$('.peTop');i++)await sleep(50);chrome();prepText();paint();const pub=$('#pePublish');if(pub)pub.addEventListener('click',()=>setTimeout(()=>publishPage().catch(console.error),400),false);document.addEventListener('dblclick',e=>{const a=e.target.closest('a[href]');if(!a)return;let u;try{u=new URL(a.href,location.href)}catch{return}if(u.origin===location.origin&&/(index|fotografia|film)\.html$/.test(u.pathname)){e.preventDefault();u.searchParams.set('editor','direct');location.href=u.href}},true)}
init().catch(console.error);
