// RAF.studio — Professional runtime v6.0
import { getApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
const app=getApp(),db=getDatabase(app),$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const EDITOR=new URLSearchParams(location.search).has('editor');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
export const PRO_DEFAULTS={
 global:{bg:'#050505',text:'#f5f5f5',muted:'#9b9b9b',accent:'#ffffff',radius:16,h1:92,h2:64,body:16},
 button:{style:'pill',bg:'#ffffff',text:'#080808',border:'#ffffff',radius:999,hover:'lift'},
 gradient:{enabled:false,from:'#000000',to:'#151515',angle:135,opacity:100},
 heroVideo:{enabled:false,url:'',opacity:65,mobileImage:true},
 stats:{enabled:true,title:'W LICZBACH.',subtitle:'Kilka liczb o RAF.studio.',items:[{value:'150+',label:'realizacji'},{value:'80+',label:'klientów'},{value:'6+',label:'lat doświadczenia'},{value:'4K',label:'foto & video'}]},
 contactForm:{enabled:true,title:'NAPISZ DO MNIE',serviceOptions:'Fotografia|Film|Ślub|Event|Produkt|Inne'},
 scroll:{enabled:true,defaultAnimation:'fade-up',duration:700,stagger:100},
 timeline:{heroTitle:0,heroDesc:130,heroButtons:260},
 sectionOrder:['TwoWorlds','About','Offer','Stats','Reviews','Brands','Contact']
};
let data=structuredClone(PRO_DEFAULTS),io=null;
function merge(raw={}){data={...structuredClone(PRO_DEFAULTS),...raw};for(const k of ['global','button','gradient','heroVideo','stats','contactForm','scroll','timeline'])data[k]={...PRO_DEFAULTS[k],...(raw[k]||{})};if(!Array.isArray(raw.sectionOrder))data.sectionOrder=[...PRO_DEFAULTS.sectionOrder]}
function ensureCss(){if($('#rafPro60Css'))return;const s=document.createElement('style');s.id='rafPro60Css';s.textContent=`:root{--raf-bg:#050505;--raf-text:#f5f5f5;--raf-muted:#9b9b9b;--raf-accent:#fff;--raf-radius:16px}body{background:var(--raf-bg)!important;color:var(--raf-text)!important}.sectionHead p,.offerHead54 p,.trustedHead54 p{color:var(--raf-muted)!important}.btn,.googleBtn54{border-radius:var(--raf-btn-radius,999px)!important}.rafStats60{padding:78px 0}.rafStatsGrid60{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid #ffffff18;border-bottom:1px solid #ffffff18}.rafStat60{padding:30px 22px;border-right:1px solid #ffffff18}.rafStat60:last-child{border-right:0}.rafStat60 strong{display:block;font-size:clamp(38px,5vw,72px);line-height:1}.rafStat60 span{color:var(--raf-muted);font-size:13px}.rafContactForm60{margin-top:22px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.rafContactForm60 input,.rafContactForm60 select,.rafContactForm60 textarea{width:100%;box-sizing:border-box;background:#0d0d0e;border:1px solid #ffffff1c;color:#fff;padding:13px 14px;border-radius:12px}.rafContactForm60 textarea{grid-column:1/-1;min-height:120px;resize:vertical}.rafContactForm60 button{grid-column:1/-1;justify-self:start}.rafFormMsg60{grid-column:1/-1;font-size:12px;color:var(--raf-muted)}.rafHeroVideo60{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;pointer-events:none}.hero{overflow:hidden}.heroMedia{z-index:0}.heroContent{position:relative;z-index:2}.raf-scroll60{opacity:0}.raf-scroll60.raf-in60{animation:rafFadeUp60 var(--raf-dur,700ms) both;animation-delay:var(--raf-delay,0ms)}.raf-scroll60[data-raf-anim="fade"]{animation-name:rafFade60}.raf-scroll60[data-raf-anim="slide-left"]{animation-name:rafSlideLeft60}.raf-scroll60[data-raf-anim="zoom"]{animation-name:rafZoom60}@keyframes rafFadeUp60{from{opacity:0;translate:0 30px}to{opacity:1;translate:0 0}}@keyframes rafFade60{from{opacity:0}to{opacity:1}}@keyframes rafSlideLeft60{from{opacity:0;translate:40px 0}to{opacity:1;translate:0 0}}@keyframes rafZoom60{from{opacity:0;scale:.94}to{opacity:1;scale:1}}@media(max-width:800px){.rafStatsGrid60{grid-template-columns:repeat(2,1fr)}.rafContactForm60{grid-template-columns:1fr}.rafContactForm60 textarea,.rafContactForm60 button{grid-column:1}.rafStat60:nth-child(2n){border-right:0}}`;document.head.appendChild(s)}
function applyGlobal(){ensureCss();const g=data.global,b=data.button,gr=data.gradient,root=document.documentElement;root.style.setProperty('--raf-bg',g.bg);root.style.setProperty('--raf-text',g.text);root.style.setProperty('--raf-muted',g.muted);root.style.setProperty('--raf-accent',g.accent);root.style.setProperty('--raf-radius',`${g.radius}px`);root.style.setProperty('--raf-btn-radius',`${b.radius}px`);const ss=$('#rafProDynamic60')||document.head.appendChild(Object.assign(document.createElement('style'),{id:'rafProDynamic60'}));ss.textContent=`h1{font-size:clamp(50px,7vw,${Number(g.h1)||92}px)!important}h2{font-size:clamp(36px,5vw,${Number(g.h2)||64}px)!important}body{font-size:${Number(g.body)||16}px}.btn,.googleBtn54{background:${b.style==='outline'?'transparent':b.bg}!important;color:${b.style==='outline'?b.border:b.text}!important;border:1px solid ${b.border}!important}${b.hover==='lift'?'.btn:hover,.googleBtn54:hover{translate:0 -2px}':''}${gr.enabled?`.section{background:linear-gradient(${Number(gr.angle)||135}deg,${gr.from},${gr.to})}`:''}`}
function heroVideo(){const h=$('[data-raf-section="Hero"]'),media=h&&$('.heroMedia',h);if(!media)return;$('.rafHeroVideo60',media)?.remove();if(!data.heroVideo.enabled||!data.heroVideo.url)return;const url=data.heroVideo.url.trim();let el;if(/\.(mp4|webm)(\?|$)/i.test(url)){el=document.createElement('video');el.src=url;el.autoplay=true;el.muted=true;el.loop=true;el.playsInline=true;el.className='rafHeroVideo60'}else if(/youtu|vimeo/i.test(url)){const id=url.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{6,})/)?.[1];if(id){el=document.createElement('iframe');el.src=`https://www.youtube.com/embed/${id}?autoplay=1&mute=1&controls=0&loop=1&playlist=${id}&modestbranding=1`;el.allow='autoplay';el.className='rafHeroVideo60';el.style.border='0'}}if(el){el.style.opacity=(Number(data.heroVideo.opacity)||65)/100;media.prepend(el);const img=$('img',media);if(img)img.style.opacity=data.heroVideo.mobileImage&&innerWidth<700?'1':'0'}}
function stats(){const main=$('#rafMain');if(!main)return;let sec=$('#rafStats60');if(!sec){sec=document.createElement('section');sec.id='rafStats60';sec.className='section rafStats60';sec.dataset.rafSection='Stats';main.appendChild(sec)}sec.style.display=data.stats.enabled?'':'none';sec.innerHTML=`<div class="wrap"><div class="sectionHead"><h2>${esc(data.stats.title)}</h2><p>${esc(data.stats.subtitle)}</p></div><div class="rafStatsGrid60">${(data.stats.items||[]).map((x,i)=>`<div class="rafStat60" data-stat-index="${i}"><strong>${esc(x.value)}</strong><span>${esc(x.label)}</span></div>`).join('')}</div></div>`}
function order(){const main=$('#rafMain');if(!main)return;for(const key of data.sectionOrder||[]){const el=key==='Offer'?$('#rafOffer54'):key==='Stats'?$('#rafStats60'):$(`[data-raf-section="${key}"]`);if(el&&el.parentElement===main)main.appendChild(el)}}
function contact(){const box=$('[data-raf-section="Contact"] .contactBox');if(!box)return;$('#rafContactForm60')?.remove();if(!data.contactForm.enabled)return;const form=document.createElement('form');form.id='rafContactForm60';form.className='rafContactForm60';const opts=String(data.contactForm.serviceOptions||'Fotografia|Film').split('|').map(x=>`<option>${esc(x.trim())}</option>`).join('');form.innerHTML=`<input name="name" required placeholder="Imię i nazwisko"><input name="email" required type="email" placeholder="E-mail"><input name="phone" placeholder="Telefon"><select name="service"><option value="">Wybierz usługę</option>${opts}</select><textarea name="message" required placeholder="Napisz kilka słów o realizacji…"></textarea><button class="btn primary" type="submit">Wyślij zapytanie →</button><div class="rafFormMsg60"></div>`;box.appendChild(form);form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),mail=$('[data-email]')?.textContent?.trim()||'';const sub=encodeURIComponent(`Zapytanie RAF.studio — ${fd.get('service')||'kontakt'}`),body=encodeURIComponent(`Imię: ${fd.get('name')}\nE-mail: ${fd.get('email')}\nTelefon: ${fd.get('phone')}\nUsługa: ${fd.get('service')}\n\n${fd.get('message')}`);$('.rafFormMsg60',form).textContent='Otwieram wiadomość e-mail…';location.href=`mailto:${mail}?subject=${sub}&body=${body}`})}
function scrollAnimations(){if(io)io.disconnect();$$('.raf-scroll60').forEach(e=>e.classList.remove('raf-scroll60','raf-in60'));if(!data.scroll.enabled||EDITOR)return;const els=$$('.sectionHead,.offerCard54,.reviewCard54,.trustedLogo54,.rafStat60,.contactBox');els.forEach((e,i)=>{e.classList.add('raf-scroll60');e.dataset.rafAnim=e.dataset.rafAnim||data.scroll.defaultAnimation;e.style.setProperty('--raf-dur',`${Number(data.scroll.duration)||700}ms`);e.style.setProperty('--raf-delay',`${(i%5)*(Number(data.scroll.stagger)||100)}ms`)});io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('raf-in60');io.unobserve(x.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));const hero=$('[data-raf-section="Hero"]');if(hero){const map=[['#heroT',data.timeline.heroTitle],['#heroD',data.timeline.heroDesc],['.actions',data.timeline.heroButtons]];map.forEach(([s,d])=>{const e=$(s,hero);if(e){e.classList.add('raf-scroll60','raf-in60');e.dataset.rafAnim='fade-up';e.style.setProperty('--raf-delay',`${Number(d)||0}ms`)}})}}
export function render(){applyGlobal();stats();heroVideo();contact();order();scrollAnimations()}
if(!EDITOR)onValue(ref(db,'website/public/proV6'),s=>{merge(s.val()||{});render()});
export {merge};
