// RAF.studio — Professional runtime v6.1
import { getApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase,ref,onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
const db=getDatabase(getApp()),$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const EDITOR=new URLSearchParams(location.search).has('editor');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
export const PRO61_DEFAULTS={
 global:{bg:'#050505',text:'#f5f5f5',muted:'#9b9b9b',accent:'#ffffff',radius:16,h1:92,h2:64,body:16},
 button:{style:'pill',bg:'#ffffff',text:'#080808',border:'#ffffff',radius:999,hover:'lift'},
 gradient:{enabled:false,from:'#000000',to:'#151515',angle:135},
 heroVideo:{enabled:false,url:'',opacity:72,mobileImage:true,fit:'cover',x:50,y:50,zoom:1,mute:true,loop:true},
 stats:{enabled:true,title:'W LICZBACH.',subtitle:'Kilka liczb o RAF.studio.',columns:4,paddingTop:80,paddingBottom:80,background:'',items:[{value:'150+',label:'realizacji'},{value:'80+',label:'klientów'},{value:'6+',label:'lat doświadczenia'},{value:'4K',label:'foto & video'}]},
 contactForm:{enabled:true,title:'NAPISZ DO MNIE',serviceOptions:'Fotografia|Film|Ślub|Event|Produkt|Inne'},
 scroll:{enabled:true,defaultAnimation:'fade-up',duration:700,stagger:100},timeline:{heroTitle:0,heroDesc:130,heroButtons:260},
 sectionOrder:['TwoWorlds','About','Offer','Stats','Reviews','Brands','Contact'],elementStyles:{},layoutBaseline:'6.1'
};
let data=structuredClone(PRO61_DEFAULTS),io=null;
export function merge61(raw={}){data={...structuredClone(PRO61_DEFAULTS),...raw};for(const k of ['global','button','gradient','heroVideo','stats','contactForm','scroll','timeline'])data[k]={...PRO61_DEFAULTS[k],...(raw[k]||{})};data.stats.items=Array.isArray(raw?.stats?.items)?raw.stats.items:PRO61_DEFAULTS.stats.items;data.elementStyles=raw.elementStyles||{};if(!Array.isArray(data.sectionOrder))data.sectionOrder=[...PRO61_DEFAULTS.sectionOrder]}
function styleEl(el,key){if(!el)return;const s=data.elementStyles?.[key]||{};if(s.color)el.style.color=s.color;if(s.fontSize)el.style.fontSize=`${s.fontSize}px`;if(s.fontWeight)el.style.fontWeight=s.fontWeight;if(s.align)el.style.textAlign=s.align;if(s.width)el.style.width=`${s.width}px`;el.style.translate=`${Number(s.x)||0}px ${Number(s.y)||0}px`;el.style.scale=String(Number(s.scale)||1);if(s.opacity!=null)el.style.opacity=String(Number(s.opacity)/100);if(s.hidden)el.style.display='none';else if(el.style.display==='none')el.style.display=''}
function css(){if($('#rafPro61Css'))return;document.body.classList.add('raf-v61');const s=document.createElement('style');s.id='rafPro61Css';s.textContent=`.rafStats61{position:relative}.rafStatsGrid61{display:grid;grid-template-columns:repeat(var(--cols,4),minmax(0,1fr));border-top:1px solid #ffffff18;border-bottom:1px solid #ffffff18}.rafStat61{padding:30px 22px;border-right:1px solid #ffffff18;position:relative}.rafStat61:last-child{border-right:0}.rafStat61 strong{display:block;font-size:clamp(38px,5vw,72px);line-height:1}.rafStat61 span{color:var(--raf-muted);font-size:13px}.rafHeroVideoWrap61{position:absolute;inset:0;overflow:hidden;z-index:0;pointer-events:none}.rafHeroVideo61{position:absolute;left:var(--vx,50%);top:var(--vy,50%);transform:translate(-50%,-50%) scale(var(--vz,1));border:0}.rafHeroVideo61.cover{width:177.78vh;height:56.25vw;min-width:100%;min-height:100%}.rafHeroVideo61.contain{width:100%;height:100%;object-fit:contain}.rafHeroVideo61.native{width:100%;height:100%;object-fit:var(--vfit,cover)}.rafContactForm61{margin-top:22px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.rafContactForm61 input,.rafContactForm61 select,.rafContactForm61 textarea{width:100%;box-sizing:border-box;background:#0d0d0e;border:1px solid #ffffff1c;color:#fff;padding:13px 14px;border-radius:12px}.rafContactForm61 textarea{grid-column:1/-1;min-height:120px}.rafContactForm61 button{grid-column:1/-1;justify-self:start}.raf-scroll61{opacity:0}.raf-scroll61.raf-in61{animation:rafFadeUp61 var(--dur,700ms) both;animation-delay:var(--delay,0ms)}.raf-scroll61[data-anim="fade"]{animation-name:rafFade61}.raf-scroll61[data-anim="slide-left"]{animation-name:rafSlide61}.raf-scroll61[data-anim="zoom"]{animation-name:rafZoom61}@keyframes rafFadeUp61{from{opacity:0;translate:0 28px}to{opacity:1;translate:0 0}}@keyframes rafFade61{from{opacity:0}to{opacity:1}}@keyframes rafSlide61{from{opacity:0;translate:40px 0}to{opacity:1;translate:0 0}}@keyframes rafZoom61{from{opacity:0;scale:.95}to{opacity:1;scale:1}}@media(max-width:800px){.rafStatsGrid61{grid-template-columns:repeat(2,1fr)!important}.rafContactForm61{grid-template-columns:1fr}.rafContactForm61 textarea,.rafContactForm61 button{grid-column:1}.rafStat61:nth-child(2n){border-right:0}}`;document.head.appendChild(s)}
function applyGlobal(){css();const g=data.global,b=data.button,root=document.documentElement;root.style.setProperty('--raf-bg',g.bg);root.style.setProperty('--raf-text',g.text);root.style.setProperty('--raf-muted',g.muted);root.style.setProperty('--raf-accent',g.accent);root.style.setProperty('--raf-btn-radius',`${b.radius}px`);const st=$('#rafProDynamic61')||document.head.appendChild(Object.assign(document.createElement('style'),{id:'rafProDynamic61'}));st.textContent=`body.raf-v61{background:${g.bg}!important;color:${g.text}!important;font-size:${Number(g.body)||16}px}.btn,.googleBtn54{border-radius:${Number(b.radius)||999}px!important;background:${b.style==='outline'?'transparent':b.bg}!important;color:${b.style==='outline'?b.border:b.text}!important;border:1px solid ${b.border}!important}${b.hover==='lift'?'.btn:hover,.googleBtn54:hover{translate:0 -2px}':''}${data.gradient.enabled?`.section{background:linear-gradient(${Number(data.gradient.angle)||135}deg,${data.gradient.from},${data.gradient.to})}`:''}`}
function parseVideo(url){const u=String(url||'').trim();if(!u)return null;if(/\.(mp4|webm)(\?|$)/i.test(u))return{type:'video',src:u};const yt=u.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{6,})/i);if(yt)return{type:'youtube',id:yt[1]};const vm=u.match(/vimeo\.com\/(?:video\/)?(\d+)/i);if(vm)return{type:'vimeo',id:vm[1]};return null}
function heroVideo(){const hero=$('[data-raf-section="Hero"]'),media=hero&&$('.heroMedia',hero);if(!media)return;$('.rafHeroVideoWrap61',media)?.remove();const cfg=data.heroVideo,info=parseVideo(cfg.url);const img=$('img',media);if(!cfg.enabled||!info){if(img&&img.dataset.homeMedia)img.style.opacity='1';return}if(cfg.mobileImage&&innerWidth<700){if(img)img.style.opacity='1';return}const w=document.createElement('div');w.className='rafHeroVideoWrap61';w.style.opacity=String((Number(cfg.opacity)||72)/100);w.style.setProperty('--vx',`${Number(cfg.x)||50}%`);w.style.setProperty('--vy',`${Number(cfg.y)||50}%`);w.style.setProperty('--vz',String(Number(cfg.zoom)||1));let el;if(info.type==='video'){el=document.createElement('video');el.src=info.src;el.autoplay=true;el.muted=cfg.mute!==false;el.loop=cfg.loop!==false;el.playsInline=true;el.className=`rafHeroVideo61 native`;el.style.setProperty('--vfit',cfg.fit||'cover')}else{el=document.createElement('iframe');el.allow='autoplay; fullscreen';el.className=`rafHeroVideo61 ${cfg.fit==='contain'?'contain':'cover'}`;if(info.type==='youtube')el.src=`https://www.youtube.com/embed/${info.id}?autoplay=1&mute=${cfg.mute===false?0:1}&controls=0&loop=${cfg.loop===false?0:1}&playlist=${info.id}&playsinline=1&rel=0`;else el.src=`https://player.vimeo.com/video/${info.id}?autoplay=1&muted=${cfg.mute===false?0:1}&loop=${cfg.loop===false?0:1}&background=1`}
w.appendChild(el);media.prepend(w);if(img)img.style.opacity='0'}
function stats(){const main=$('#rafMain');if(!main)return;let sec=$('#rafStats61');if(!sec){sec=document.createElement('section');sec.id='rafStats61';sec.className='section rafStats61';sec.dataset.rafSection='Stats';main.appendChild(sec)}const x=data.stats;sec.style.display=x.enabled?'':'none';sec.style.paddingTop=`${Number(x.paddingTop)||80}px`;sec.style.paddingBottom=`${Number(x.paddingBottom)||80}px`;sec.style.background=x.background||'';sec.innerHTML=`<div class="wrap"><div class="sectionHead"><h2 data-pro61="stats.title">${esc(x.title)}</h2><p data-pro61="stats.subtitle">${esc(x.subtitle)}</p></div><div class="rafStatsGrid61" style="--cols:${Number(x.columns)||4}">${x.items.map((it,i)=>`<div class="rafStat61" data-stat-index="${i}"><strong data-pro61="stats.${i}.value">${esc(it.value)}</strong><span data-pro61="stats.${i}.label">${esc(it.label)}</span></div>`).join('')}</div></div>`;$$('[data-pro61]',sec).forEach(el=>styleEl(el,el.dataset.pro61));styleEl(sec,'stats.section')}
function order(){const main=$('#rafMain');if(!main)return;for(const k of data.sectionOrder){const el=k==='Offer'?$('#rafOffer54'):k==='Stats'?$('#rafStats61'):$(`[data-raf-section="${k}"]`);if(el&&el.parentElement===main)main.appendChild(el)}}
function contact(){const box=$('[data-raf-section="Contact"] .contactBox');if(!box)return;$('#rafContactForm61')?.remove();if(!data.contactForm.enabled)return;const f=document.createElement('form');f.id='rafContactForm61';f.className='rafContactForm61';const opts=String(data.contactForm.serviceOptions||'').split('|').map(v=>`<option>${esc(v.trim())}</option>`).join('');f.innerHTML=`<input name="name" required placeholder="Imię i nazwisko"><input name="email" required type="email" placeholder="E-mail"><input name="phone" placeholder="Telefon"><select name="service"><option value="">Wybierz usługę</option>${opts}</select><textarea name="message" required placeholder="Napisz kilka słów o realizacji…"></textarea><button class="btn primary" type="submit">Wyślij zapytanie →</button>`;box.appendChild(f);f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),mail=$('[data-email]')?.textContent?.trim()||'';location.href=`mailto:${mail}?subject=${encodeURIComponent('Zapytanie RAF.studio — '+(fd.get('service')||'kontakt'))}&body=${encodeURIComponent(`Imię: ${fd.get('name')}\nE-mail: ${fd.get('email')}\nTelefon: ${fd.get('phone')}\nUsługa: ${fd.get('service')}\n\n${fd.get('message')}`)}`}}
function motion(){if(io)io.disconnect();$$('.raf-scroll61').forEach(e=>e.classList.remove('raf-scroll61','raf-in61'));if(EDITOR||!data.scroll.enabled)return;const els=$$('.sectionHead,.offerCard54,.reviewCard54,.trustedLogo54,.rafStat61,.contactBox');els.forEach((e,i)=>{e.classList.add('raf-scroll61');e.dataset.anim=data.scroll.defaultAnimation;e.style.setProperty('--dur',`${Number(data.scroll.duration)||700}ms`);e.style.setProperty('--delay',`${(i%5)*(Number(data.scroll.stagger)||100)}ms`)});io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('raf-in61');io.unobserve(x.target)}}),{threshold:.12});els.forEach(e=>io.observe(e))}
export function render61(){applyGlobal();stats();heroVideo();contact();order();motion();for(const [key] of Object.entries(data.elementStyles||{})){const el=$(`[data-pro61="${CSS.escape(key)}"]`);if(el)styleEl(el,key)}}
if(!EDITOR)onValue(ref(db,'website/public/proV6'),s=>{merge61(s.val()||{});render61()});
