// RAF.studio — monitor Firebase Storage (główna strona)
import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getStorage, ref as sRef, listAll, getMetadata } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const app=getApps().length?getApp():initializeApp(firebaseConfig), storage=getStorage(app);
const LIMIT=5*1024*1024*1024;
const fmt=b=>b>=1024**3?`${(b/1024**3).toFixed(2)} GB`:b>=1024**2?`${(b/1024**2).toFixed(1)} MB`:`${(b/1024).toFixed(0)} KB`;

async function walk(r){const out=await listAll(r);let bytes=0,count=0;for(const item of out.items){try{const m=await getMetadata(item);bytes+=Number(m.size)||0;count++}catch{}}for(const p of out.prefixes){const x=await walk(p);bytes+=x.bytes;count+=x.count}return{bytes,count}}
function inject(){const dash=document.querySelector('[data-pane-view="dashboard"]');if(!dash||document.querySelector('#storageMonitorCard'))return null;const card=document.createElement('div');card.id='storageMonitorCard';card.className='adminCard';card.style.marginBottom='18px';card.innerHTML=`<div class="eyebrow">FIREBASE STORAGE</div><div style="display:flex;justify-content:space-between;gap:12px;align-items:end"><div><h3 style="margin-bottom:4px">Miejsce strony</h3><div id="storageAmount" style="font-size:22px;font-weight:900">Liczenie…</div><div id="storageFiles" class="tiny">Skanowanie website/…</div></div><button class="pill" id="storageRefresh">Odśwież</button></div><div style="height:10px;background:#ffffff0d;border:1px solid #ffffff15;border-radius:99px;overflow:hidden;margin-top:14px"><div id="storageBar" style="height:100%;width:0;background:#fff;transition:.35s"></div></div><div id="storagePct" class="tiny" style="margin-top:7px">Limit odniesienia: 5 GB</div>`;const anchor=dash.querySelector('.statusGrid');if(anchor)anchor.before(card);else dash.appendChild(card);document.querySelector('#storageRefresh').onclick=refresh;return card}
async function refresh(){inject();const a=document.querySelector('#storageAmount'),f=document.querySelector('#storageFiles'),b=document.querySelector('#storageBar'),p=document.querySelector('#storagePct');if(!a)return;a.textContent='Liczenie…';f.textContent='Skanowanie website/…';try{const r=await walk(sRef(storage,'website'));const pct=Math.min(100,r.bytes/LIMIT*100);a.textContent=`${fmt(r.bytes)} / 5 GB`;f.textContent=`${r.count} plików w głównym Storage strony`;b.style.width=`${pct}%`;p.textContent=`Wykorzystano ${pct.toFixed(2)}% z 5 GB`;if(pct>80)b.style.background='#ffb347';if(pct>95)b.style.background='#ff5d5d'}catch(e){console.error(e);a.textContent='Nie udało się policzyć';f.textContent=e.message||String(e)}}
if(inject())refresh();else setTimeout(()=>{inject();refresh()},500);
