import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app);let current={};
const VISUAL_QUERY=new URLSearchParams(location.search),EDITOR_MODE=VISUAL_QUERY.has('editor')||VISUAL_QUERY.has('tplPreview');
const dev=()=>innerWidth<=640?'mobile':innerWidth<=980?'tablet':'desktop';
function textKey(el){return ['heroK','heroT','heroD'].includes(el.id)?el.id:(el.dataset.homeText||'')}
function sectionKey(el){return el.matches('header.hero')?'Hero':(el.dataset.homeSection||'')}
function resetText(el){['fontSize','letterSpacing','lineHeight','fontFamily','fontWeight','color','textAlign','maxWidth','width','transform','transformOrigin','position','zIndex','opacity','display','animation'].forEach(k=>el.style[k]='')}
function cfgFor(byDev,d){const desk=byDev?.desktop||{};if(d==='desktop')return desk;const c=byDev?.[d]||{};return c.inherit===false?c:{...desk,...c}}
function ensureCss(){if(document.querySelector('#rafVisualAnimCss'))return;const s=document.createElement('style');s.id='rafVisualAnimCss';s.textContent='@keyframes rafTextFade{from{opacity:0}to{opacity:1}}@keyframes rafTextSlide{from{opacity:0;transform:translateY(24px)}to{opacity:1}}@keyframes rafTextZoom{from{opacity:0;transform:scale(.94)}to{opacity:1}}';document.head.appendChild(s)}
function apply(){ensureCss();const d=dev();document.querySelectorAll('[data-home-text],#heroK,#heroT,#heroD').forEach(el=>{resetText(el);const c=cfgFor(current.texts?.[textKey(el)]||{},d);if(c.fontSize!=null)el.style.fontSize=c.fontSize+'px';if(c.letterSpacing!=null)el.style.letterSpacing=c.letterSpacing+'px';if(c.lineHeight!=null)el.style.lineHeight=c.lineHeight;if(c.fontFamily)el.style.fontFamily=c.fontFamily;if(c.fontWeight)el.style.fontWeight=c.fontWeight;if(c.color)el.style.color=c.color;if(c.textAlign)el.style.textAlign=c.textAlign;if(c.width)el.style.width=c.width+'px';if(c.width)el.style.maxWidth=c.width+'px';el.style.transformOrigin='center center';el.style.transform=`translate(${Number(c.moveX)||0}px,${Number(c.moveY)||0}px) rotate(${Number(c.rotate)||0}deg) scale(${Number(c.scale)||1})`;if(c.moveX||c.moveY||c.rotate||Number(c.scale)!==1){el.style.position='relative'}el.style.zIndex=c.zIndex!=null?String(c.zIndex):'';if(c.hidden===true)el.style.display='none';if(c.opacity!=null)el.style.opacity=String(c.opacity);const dur=Number(c.animationDuration)||700;if(c.animation==='fade')el.style.animation=`rafTextFade ${dur}ms both`;if(c.animation==='slide')el.style.animation=`rafTextSlide ${dur}ms both`;if(c.animation==='zoom')el.style.animation=`rafTextZoom ${dur}ms both`});document.querySelectorAll('[data-home-section],header.hero').forEach(el=>{const c=cfgFor(current.sections?.[sectionKey(el)]||{},d);el.style.paddingTop=c.paddingTop!=null?c.paddingTop+'px':'';el.style.paddingBottom=c.paddingBottom!=null?c.paddingBottom+'px':'';el.style.minHeight=c.minHeight!=null?c.minHeight+'px':'';el.style.background=c.background||'';el.style.display=c.hidden===true?'none':''})}
if(!EDITOR_MODE){onValue(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),s=>{current=s.val()||{};apply()});addEventListener('resize',apply)}
