import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig, WEBSITE_ROOT } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app);let current={};
const EDITOR_MODE=new URLSearchParams(location.search).has('editor');
function dev(){return innerWidth<=640?'mobile':innerWidth<=980?'tablet':'desktop'}
function textKey(el){return el.id==='heroK'||el.id==='heroT'||el.id==='heroD'?el.id:el.dataset.homeText||''}
function sectionKey(el){return el.matches('header.hero')?'Hero':el.dataset.homeSection||''}
function resetText(el){['fontSize','letterSpacing','lineHeight','fontFamily','fontWeight','color','textAlign','maxWidth','width','transform','transformOrigin','position','zIndex'].forEach(k=>el.style[k]='')}
function apply(){const d=dev();document.querySelectorAll('[data-home-text],#heroK,#heroT,#heroD').forEach(el=>{resetText(el);const c=current.texts?.[textKey(el)]?.[d]||{};if(c.fontSize!=null)el.style.fontSize=c.fontSize+'px';if(c.letterSpacing!=null)el.style.letterSpacing=c.letterSpacing+'px';if(c.lineHeight!=null)el.style.lineHeight=c.lineHeight;if(c.fontFamily)el.style.fontFamily=c.fontFamily;if(c.fontWeight)el.style.fontWeight=c.fontWeight;if(c.color)el.style.color=c.color;if(c.textAlign)el.style.textAlign=c.textAlign;if(c.maxWidth)el.style.maxWidth=c.maxWidth+'px';if(c.width)el.style.width=c.width+'px';el.style.transformOrigin='center center';el.style.transform=`translate(${c.moveX||0}px,${c.moveY||0}px) rotate(${c.rotate||0}deg) scale(${c.scale||1})`;if(c.moveX||c.moveY||c.rotate||c.scale&&c.scale!==1){el.style.position='relative';el.style.zIndex='4'}});document.querySelectorAll('[data-home-section],header.hero').forEach(el=>{const c=current.sections?.[sectionKey(el)]?.[d]||{};el.style.paddingTop=c.paddingTop!=null?c.paddingTop+'px':'';el.style.paddingBottom=c.paddingBottom!=null?c.paddingBottom+'px':'';el.style.background=c.background||'';el.style.display=c.hidden===true?'none':''})}
if(!EDITOR_MODE){onValue(ref(db,`${WEBSITE_ROOT}/public/visualStyles`),s=>{current=s.val()||{};apply()});addEventListener('resize',apply)}